# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Mini-Project: Implementation of Linear Regression using OOPs

**DISCLAIMER:** THIS NOTEBOOK IS PROVIDED ONLY AS A REFERENCE SOLUTION NOTEBOOK FOR THE MINI-PROJECT. THERE MAY BE OTHER POSSIBLE APPROACHES/METHODS TO ACHIEVE THE SAME RESULTS.

## Learning Objectives

At the end of the mini-project, you will be able to :

- understand the power and flexibility of the Object-oriented programming (OOP) paradigm
- build OOP based classes and methods and use them to implement Linear Regression for solving real world data related queries

## Problem Statement

Implement linear regression using classes and methods built with OOP.

## Information

#### Object oriented programming in a nutshell

Object oriented programming is based around the concept of "objects". Objects have two kinds of attributes (accessed via . sytax): data attributes (or instance variables) and function attributes (or methods). Object data is typically modified by object methods.

To know more about OOPs click [here](https://docs.python.org/3/tutorial/classes.html)

#### Linear Regression

In statistics, linear regression is a linear approach to modelling the relationship between a scalar response and one or more explanatory variables (also known as dependent and independent variables). The case of one explanatory variable is called simple linear regression; for more than one, the process is called multiple linear regression.

To know more about Linear regression  click [here](http://www.mit.edu/~6.s085/notes/lecture3.pdf)

## Grading = 10 Points

There are total 10 exercises and 1 point for each.

##### Importing Necessary Packages

In [ ]:
import numpy as np # Numpy Package
import pandas as pd # Pandas Package

#### Exercise 1: Generate 50 points with an approximate relationship of y = 3x + 1, with normally distributed errors.

**Hint:** np.linspace(), np.random.randn()

In [ ]:
np.random.seed(0)
numberofPoints = 50   # Number of data points
x = np.linspace(0, 10, numberofPoints)
y = x * 3 + 1 + 1 * np.random.randn(numberofPoints) # Standard deviation 1
print(x) # Printing the x values
print(y) # Printing the y values

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 2.76405235  2.01240211  3.20322778  5.07762789  5.31653758  3.08394661
  5.62355781  5.13435708  5.79474033  6.92080258  7.26649255  9.18896738
  9.1079765   9.08085869 10.0152918  10.5173478  12.28999744 11.203005
 12.33347586 11.77855732 10.69190814 14.51076145 15.33382395 14.33946763
 17.96363218 14.85175677 16.96412586 17.34342839 19.67563636 20.22446081
 19.52229436 20.35775436 19.70405099 19.22328516 21.46841438 22.5849204
 24.27110701 24.85544107 23.87797931 24.57524827 24.44124295 24.68202288
 25.00801552 29.27730601 27.42912333 28.11294611 27.91046995 30.55300056
 28.77385725 30.78725972]

#### Exercise 2: Define a class named **LinearRegression** and add a short description of linear regression using built in method \_\_repr\_\_

**Hint:** [How to use \_\_repr\_\_ method](https://www.educative.io/edpresso/what-is-the-repr-method-in-python)

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"

In [ ]:
type(LinearRegression) # Checking for the type

type

In [ ]:
help(LinearRegression) # Checking for the description of the class

Help on class LinearRegression in module __main__:

class LinearRegression(builtins.object)
 |  Methods defined here:
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [ ]:
LinearRegression() # Creating an instance of a class

We are working on Linear Regression

#### Exercise 3: In the above defined Linear Regression class, add a method which takes list of values as input and returns the mean of those values. 

**Note:** Don't use built-in method to calculate the mean

**Hint:** 
1. The mean is the average of the numbers
2. [How to define a method in a class](https://docs.python.org/3/tutorial/classes.html#scopes-and-namespaces-example)

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)

In [ ]:
Lr = LinearRegression() # Instance of a LinearRegression class

In [ ]:
x_mean = Lr.getMean(x) # Accessing getMean method from the class

In [ ]:
x_mean

5.0

#### Exercise 4: In the above defined Linear Regression class, add a method which takes list of values as input and returns the variance of those values.

**Note:** Don't use built-in method to calculate the variance

**Hint:** 

1. The Variance is the average of the squared differences from the Mean
2. [How to access one method in different method inside a class](https://docs.python.org/3/tutorial/classes.html#scopes-and-namespaces-example)

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)
    # Function to calculate the variance
    def getVariance(self,values):
        mean = self.getMean(values)
        return sum([(x-mean)**2 for x in values])

In [ ]:
Lr = LinearRegression() # Instance of a class LinearRegression

In [ ]:
Lr.getMean(x), Lr.getMean(y) # Accessing the getMean method

(5.0, 16.0)

In [ ]:
Lr.getVariance(x), Lr.getVariance(y) # Accessing the getVariance method

(433.6734693877552, 3600.079227775663)

#### Exercise 5: In the above defined Linear Regression class, add a method which takes two values as input and returns the covariance of those values.

**Note:** Don't use built-in method to calculate the covariance

**Hint:** [How to calculate the covariance of two values](https://www.statisticshowto.com/probability-and-statistics/statistics-definitions/covariance/)

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)
    # Function to calculate the variance
    def getVariance(self,values):
        mean = self.getMean(values)
        return sum([(x-mean)**2 for x in values])
    # Function to calculate the covariance
    def getcovariance(self, x, y):
        xmean = self.getMean(x) # Mean of x values
        ymean = self.getMean(y) # Mean of y values
        covar = 0.0
        for i in range(len(x)):
            covar += (x[i] - xmean) * (y[i] - ymean)
        return covar

In [ ]:
Lr = LinearRegression() # Creating a instance of a class LinearRegression

In [ ]:
Lr.getcovariance(x,y) # Accessing the getcovariance method

1239.802085763181

#### Exercise 6: In the above defined Linear Regression class, add a method named 'fit' which takes two values as input (x, y) and returns the estimated coefficients.

**Hint:**

- Equation of line : $  y = b_{0} + b_{1} * x $
- The estimated coefficients i.e. values of $b_{0}$ and $b_{1}$ are calculated as below
    - $ b_{1} = covariance(x,y) / variance(x) $ and
    - $ b_{0} = mean(y) - b_{1} * mean(x)$

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)
    # Function to calculate the variance
    def getVariance(self,values):
        mean = self.getMean(values)
        return sum([(x-mean)**2 for x in values])
    # Function to calculate the covariance
    def getcovariance(self, x, y):
        xmean = self.getMean(x)
        ymean = self.getMean(y)
        covar = 0.0
        for i in range(len(x)):
            covar += (x[i] - xmean)*(y[i] - ymean)
        return covar
    # Function to calculate the estimated coefficients
    def fit(self,x,y):
        # Calculating mean of x and y
        mean_x, mean_y = self.getMean(x), self.getMean(y)
        # Calculating covariance between x and y and finding the b1 value
        b1 = self.getcovariance(x, y) / self.getVariance(x)
        # finding b0 value
        b0 = mean_y - b1 * mean_x
        # returning the estimated coefficients
        return [b0, b1]

In [ ]:
Lr = LinearRegression() # Instance of a Linear Regression class

In [ ]:
Lr.fit(x,y) # Accessing the fit method defined in the LinearRegression class

[1.7058112464950934, 2.8588377507009812]

#### Exercise 7: In the above defined Linear Regression class, add a method named predict which takes two values as input (x, y) and returns the predicted values.

**Hint:** substitute the estimated coefficients values calculated above in the equation of line i.e $  y = b_{0} + b_{1} * x $

In [ ]:
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)
    # Function to calculate the variance
    def getVariance(self,values):
        mean = self.getMean(values)
        return sum([(x-mean)**2 for x in values])
    # Function to calculate the covariance
    def getcovariance(self, x, y):
        xmean = self.getMean(x)
        ymean = self.getMean(y)
        covar = 0.0
        for i in range(len(x)):
            covar += (x[i] - xmean)*(y[i] - ymean)
        return covar
    # Function to calculate the estimated coefficients
    def fit(self,x,y):
        # Calculating mean of x and y
        mean_x, mean_y = self.getMean(x), self.getMean(y)
        # Calculating covariance between x and y and finding the b1 value
        b1 = self.getcovariance(x, y) / self.getVariance(x)
        # finding b0 value
        b0 = mean_y - b1 * mean_x
        # returning the estimated coefficients
        return [b0, b1]
    def predict(self, x, y):
        predictions = [] # Defining a empty list to store prediction values
        b0, b1 = self.fit(x, y) # Calculating the estimated coeffients
        for row in x: # Iterating over x values
            ynew = b0 + b1 * row # Calculating y values
            predictions.append(ynew)
        return predictions

In [ ]:
Lr = LinearRegression() # Instance of the class

In [ ]:
Lr.predict(x,y) # Predicitng the values

[1.7058112464950934,
 2.289247522148355,
 2.872683797801616,
 3.456120073454878,
 4.039556349108139,
 4.622992624761401,
 5.206428900414663,
 5.789865176067924,
 6.3733014517211855,
 6.956737727374446,
 7.540174003027708,
 8.123610278680971,
 8.70704655433423,
 9.290482829987493,
 9.873919105640754,
 10.457355381294017,
 11.040791656947277,
 11.624227932600538,
 12.2076642082538,
 12.791100483907062,
 13.374536759560323,
 13.957973035213584,
 14.541409310866847,
 15.124845586520108,
 15.708281862173369,
 16.291718137826628,
 16.87515441347989,
 17.458590689133153,
 18.042026964786416,
 18.62546324043968,
 19.20889951609294,
 19.792335791746197,
 20.37577206739946,
 20.959208343052723,
 21.542644618705985,
 22.126080894359248,
 22.709517170012504,
 23.292953445665766,
 23.87638972131903,
 24.45982599697229,
 25.043262272625554,
 25.626698548278817,
 26.210134823932073,
 26.793571099585336,
 27.3770073752386,
 27.96044365089186,
 28.543879926545124,
 29.127316202198386,
 29.710752477851642,
 30.294188753504905]

#### Data

The dataset choosen for this experiment is **Pizza Franchise** dataset. The dataset contains following data

X = annual franchise fee ($1000)

Y = start up cost ($1000) for a pizza franchise

Download the dataset [here](https://cdn.iisc.talentsprint.com/CDS/Datasets/pizza.csv)

#### Exercise 8: Using the above defined class LinearRegression, calculate the Estimated coeffients, fit the model, and predict the values on the Pizza Franchise dataset.

In [ ]:
!wget -qq https://cdn.iisc.talentsprint.com/CDS/Datasets/pizza.csv

In [ ]:
import pandas as pd # Importing pandas package
df = pd.read_csv("pizza.csv") # Loading pizza dataset

In [ ]:
df.head() # Checking for the first five rows from the dataset

      X     Y
0  1000  1050
1  1125  1150
2  1087  1213
3  1070  1275
4  1100  1300

In [ ]:
Lr = LinearRegression()  # Instance of a class LinearRegression

In [ ]:
Lr.fit(df['X'], df['Y']) # Fitting the values

[867.8473661249864, 0.3731504707892536]

In [ ]:
Predicted_values = Lr.predict(df['X'], df['Y']) # Predicting the values

In [ ]:
Predicted_values

[1240.99783691424,
 1287.6416457628966,
 1273.461927872905,
 1267.1183698694877,
 1278.3128839931653,
 1296.970407532628,
 1334.2854546115534,
 1296.970407532628,
 1278.3128839931653,
 1371.6005016904787,
 1343.6142163812847,
 1380.9292634602102,
 1306.2991693023594,
 1315.6279310720906,
 1306.2991693023594,
 1352.9429781510162,
 1338.016959319446,
 1364.1374922746936,
 1362.2717399207475,
 1315.6279310720906,
 1324.9566928418221,
 1274.5813792852728,
 1268.984122223434,
 1270.8498745773802,
 1270.8498745773802,
 1308.1649216563055,
 1324.9566928418221,
 1306.2991693023594,
 1334.2854546115534,
 1334.2854546115534,
 1147.7102192169266,
 1287.6416457628966,
 1129.0526956774638,
 1203.6827898353147,
 1203.6827898353147,
 1185.025266295852]

#### Exercise 9: In the above defined Linear Regression class, add a method named RMSE which takes two values as input (x, y) and returns the error value.

**Hint:**

- [How to calculate RMSE value](https://towardsdatascience.com/what-does-rmse-really-mean-806b65f2e48e)

In [ ]:
from math import sqrt
class LinearRegression:   
    def __repr__(self):
        return "We are working on Linear Regression"
    # Function to calculate the mean
    def getMean(self, values):
        return sum(values) // len(values)
    # Function to calculate the variance
    def getVariance(self,values):
        mean = self.getMean(values)
        return sum([(x-mean)**2 for x in values])
    # Function to calculate the covariance
    def getcovariance(self, x, y):
        xmean = self.getMean(x)
        ymean = self.getMean(y)
        covar = 0.0
        for i in range(len(x)):
            covar += (x[i] - xmean)*(y[i] - ymean)
        return covar
    # Function to calculate the estimated coefficients
    def fit(self,x,y):
        # Calculating mean of x and y
        mean_x, mean_y = self.getMean(x), self.getMean(y)
        # Calculating covariance between x and y and finding the b1 value
        b1 = self.getcovariance(x, y) / self.getVariance(x)
        # finding b0 value
        b0 = mean_y - b1 * mean_x
        # returning the estimated coefficients
        return [b0, b1]
    def predict(self, x, y):
        predictions = [] # Defining a empty list to store prediction values
        b0, b1 = self.fit(x, y) # Calculating the estimated coeffients
        for row in x: # Iterating over x values
            ynew = b0 + b1 * row # Calculating y values
            predictions.append(ynew)
        return predictions
    # Function to calculate RMSE Value
    def rmse(self, actual, predicted):
        sum_err = 0.0
        for i in range(len(actual)):
            pred_err = predicted[i] - actual[i]
            sum_err += pred_err ** 2
        mean_err = sum_err / float(len(actual))
        return sqrt(mean_err)

#### Data

The dataset choosen for this exercise is **List Price Vs. Best Price for a New GMC Pickup** dataset. The dataset contains following data

X = List price (in $1000) for a GMC pickup truck

Y = Best price (in $1000) for a GMC pickup truck

Download the dataset [here](https://cdn.iisc.talentsprint.com/CDS/Datasets/gmc.csv)

#### Exercise 10: Using above defined class LinearRegression, 

- calculate the Estimated coeffients, fit the model, and predict the values on the List Price Vs. Best Price for a New GMC Pickup dataset.
- calculate the RMSE error on predicted and actual values of List Price Vs. Best Price for a New GMC Pickup dataset using the function defined above.

In [ ]:
!wget -qq https://cdn.iisc.talentsprint.com/CDS/Datasets/gmc.csv

In [ ]:
data = pd.read_csv("gmc.csv") # Loading the dataset

In [ ]:
data.head() # Checking for the top five rows

      X     Y
0  12.4  11.2
1  14.3  12.5
2  14.5  12.7
3  14.9  13.1
4  16.1  14.1

In [ ]:
Lr = LinearRegression() # Instance of a class

In [ ]:
Lr.fit(data['X'], data['Y']) # Fitting the data

[0.661634702253636, 0.8434332528086097]

In [ ]:
Predicted_values = Lr.predict(data['X'], data['Y']) # Predicting the values

In [ ]:
Lr.rmse(data['Y'], Predicted_values) # Calculating rmse value

0.14379661242306657

### Optional

* Use the built-in `sklearn LinearRegression` package to determine the coefficients for the above problems. 
* Compare the coefficients obtained using OOP based implementation vs coefficients from `sklearn LinearRegression` package.