In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
'''
Loading Gensim and nltk libraries
'''
# pip install gensim
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(400)

In [3]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [4]:
df = pd.read_csv("/content/2022_Sep3_17k_hydrated_tweets.csv")

In [5]:
df.drop(columns=['id_str',"in_reply_to_screen_name","is_retweet"], inplace=True)

In [6]:
# Function to Clean the Tweet.

import re
def clean_tweet(tweet):
    return ' '.join(re.sub('(\\\\n)|(b\"[^0-9A-Za-z A-Za-z0-9 \t]+)|(b\'[^0-9A-Za-z]+)|(b\"[A-Za-z0-9]+)|(b\'[A-Za-z0-9]+)|(b\'#[A-Za-z0-9]+)|(b\'@[A-Za-z0-9]+)|(\\\\x[A-Za-z0-9]+)|(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|([RT])', ' ', str(tweet).lower()).split())

In [7]:
# Call function to get Clean tweets
df["CleanTweet"] = df['text'].apply(lambda x : clean_tweet(x))
df.tail()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
15666,12,Twitter Web App,b'UK to begin new COVID-19 vaccination campaig...,Sun Sep 04 02:00:01 +0000 2022,4,to begin new covid 19 vaccination campaign
15667,0,WordPress.com,"b'(URGENT) S. Korea reports 72,144 new COVID-1...",Sun Sep 04 02:00:57 +0000 2022,0,urgent s korea reports 72 144 new covid 19 cases
15668,1,Twitter for Android,b'@ethanjweiss Thanks for your honesty in post...,Sun Sep 04 02:03:29 +0000 2022,0,ethanjweiss thanks for your honesty in posting...
15669,0,WordPress.com,b'Brockton to spray city following West Nile V...,Sun Sep 04 02:03:25 +0000 2022,0,to spray city following west nile virus discovery
15670,0,Twitter for iPhone,b'Antiviral Therapy | COVID-19 Treatment Guide...,Sun Sep 04 02:02:49 +0000 2022,0,therapy covid 19 treatment guidelines

In [8]:
df.drop(df.index[df.CleanTweet.eq("")], inplace=True)

In [ ]:
df.head()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
0,1,Twitter for Android,"b""Don't believe it. https://t.co/VFfhPArn1a""",Sat Sep 03 04:09:04 +0000 2022,0,t believe it
1,0,cmssocialservice,b'Surat records 11 new Covid-19 cases https://...,Sat Sep 03 04:06:03 +0000 2022,0,records 11 new covid 19 cases
2,38,TweetDeck,b'Hennepin County will no longer require COVID...,Sat Sep 03 04:09:00 +0000 2022,6,county will no longer require covid 19 vaccine...
3,2,Twitter Web App,"b'As of Sept 1, the capital has given over 63....",Sat Sep 03 04:08:52 +0000 2022,0,of sept 1 the capital has given over 63 2 mill...
4,1,Twitter for Android,b'@KushThrough @BlazedRTs @rtsmallstreams @Rts...,Sat Sep 03 04:15:46 +0000 2022,3,kushthrough ww nowplaying x lilroyce her ev

In [9]:
stemmer = SnowballStemmer(language='english')
def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

# Tokenize and lemmatize
def preprocess(text):
    result=[]
    for token in gensim.utils.simple_preprocess(text) :
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
            
    return result

In [10]:
complete_text = ' '.join(df["CleanTweet"])

In [11]:
data = df.CleanTweet.values.tolist()

In [ ]:
pprint(data[:2])

['t believe it', 'records 11 new covid 19 cases']

In [ ]:
complete_text

't believe it records 11 new covid 19 cases county will no longer require covid 19 vaccines for its employees of sept 1 the capital has given over 63 2 million doses of covid19 vaccines to over 23 6 million people kushthrough ww nowplaying x lilroyce her ev can t be good for you themixmedic nowplaying x lilroyce her evil spine feat makrazy total of 174 new cases of covid 19 were reported during the last 24 hours across the state odisha odishanews appointed by the israeli moh to investigate covid 19 vaccine side effects warned the ministry it could b covid 19 closed our campuses down the idea that every student has a computer a word processing program sta thetruthsucks12 why get poked in 2021 when covid 19 has a 98 survival rate got a bridge in brooklyn for sale yo federal government is fucking trash dubai reins in hospitality as covid 19 cases rise is hilarious you can make this up the camp counselor who tried to overturn a decisive democratic election pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri fucking idiots odisha reports 174 new cases of covid19 in the last 24 hours of which 0 18 years 13 in quarantine 102 local contacts 72 invented and cured coronavirus donald trump was very smart russia bombed the lab in ukraine that was genera not a way to handle the pandemic science table members disagree with scrapping 5 day covid 19 isolation cbc ne covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity rate 1 98 in an almighty coronavirus metaphor at stechford baths station rd 19 or swine flu know how to differentiate between the geauxt17 had been in the house coronavirus task force for decades you said that right 19 journal for friday september 2 2022 records 46 new cases of coronavirus within 24 denise dewald wuhan used an unknown coronavirus test initially does argentina have access to this friday broadcast of the five fox news greg gutfeld proclaimed that he is disinformation after a co break on august 23 the botetourt county board of supervisors approved an additional 250 000 in personal pro deblvsbabygroot really does depend on the circumstances here is the workcover qld link profesterman thanks for the daily covid19 data amp i hope your dog maintains the waistline odisha covid19 report for 2nd sept new positive cases 174 of which 0 18 years 13 in quarantine 102 local c 6 months can now receive safe amp effective covid 19 vaccines talk to your child doctor amp help them is back in session but even before the first test has been given new numbers have confirmed what many teach that takes this murdering jab is just as stupid as you murderer make it stop america last is fucking with our country hard and they pull this shit again and again they xf0 assamese morning news hours 09 2022 covid19 covid19 could given that money to ukraine ashleigh roy but but you get a little excited clicking the link only to find it s a treatment you ve already tried amp didn t get mu can hear her now msmcmo trump had a cure for covid19 he said just inject disinfectant into your body covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours canmericanized if you believe that only 190 arrivecan tickets were issued since the app was made mandatory than y reptedbudd are you demanding answers from boss trump why he took top sci files why are 4 s time for our leaders to sit up pay attention and expand social security disability benefits to the millions world covid19 vaccine protection rates of 7 countries against infection in the delta amp omicron eras the avera reports first human case of west nile virus this survived covid 19 with them but we now loosing them to tumbwa records 11 new covid 19 cases blame bidentrump fuck them covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p president was just telling the god s truth you follow the evil liar con your trumpy con man demonized thous brendanjanus covid 19 vaccines available in the united states are safe and are effective a 28 2017 age 35 l 23rd last gs win vs sister age 36 9 2 22 pursuit of potus the lockdowns reduced mortality from covid 19 by just 0 2 those jobs should have never been lost in the first place happening in china this woman tried to take down jordan b peterson now she wants to take down her employer you would find the truth of the complete case file regarding the coronavirus from beginning to end imam mahdi n pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri big kristiiiii nowplaying x lilroyce her evil spine feat makrazy demise of society this administration is insane managed to beat covid19 for almost two years then one day newsom in laws moved to florida during the coronavirus hampshire covid 19 updates numbers for cases hospitalizations vaccinations 211 fresh covid 19 cases in india in the last 24 hours covid19 mask mandates are too much to ask for pres biden on covid 19 funds for local economies 2 after words sen tammy duckworth d il every day is a gift cdc director signs off on new covid 19 boosters quietly adds ivermectin to covid 19 treatment guidelines as antiviral therapy big league politics messiah s didthatchokeyou that s almost as stupid as getting the covid 19 vaccination new covid19 variants could emerge this winter the european union drug agency has said but existing va is stupid asean family newsfrommalaysia covid19 malaysia as 2 september 2022 confirmed cases 2 328 research pandemic telehealth utilization related to decrease opioid overdose riskgetting opioid utilizati t co tgmsvs5p8l covid 19 outbreak declared over at bethammi nursing home 3rd floor tbay thunderbay middaynews mumbai sees 402 new covid 19 cases as virus kills 3 mumbainews covid19 covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p i have contacted the clix as well your partner they said we don t have any problem the account is opened only y are living through an intense drought with water resources at all time low scientists may have found a way jon o90 why are you lying about this dems are saving lives republicans were against the gshodl brics also announce that americans are evil and project whatever problems they themselves c serehfas covid surely must be one of the most familiar medical pathogens ever studied by now if this is not ident administration has been shuffling money from other pockets to pay for the new shots after congress failed t another example of the laptop classes hypocrisy who wants to be he supported vaccine mandates and people lo sleepy look after yourself and don t overdo it on the caffeine covid19 socialdistancing emotionalconnection in our icu with frontal contusion gcs full absolutely doing fine for 5 days desaturated one day and his truly do have the biggest fucking joke of a government to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di medicaldevice regulatory daily stories via icis cdnhealth covid19 your unique nft covid 19 colorful variant 6280 now do you already own nfts gracelp they may still be good for a couple months hk watch how great ex cop ce mr lee to use smokescreen of covid to curb freedom n surveillance little kids aged korea reports less than 80 000 new covid 19 cases covid19 southkorea arirang news california gov gavin newsom in laws moved to florida during the chinese coronavirus pandemic 2 0 realdailywire covid19 return to work rebound isn t creating jobs stop distorting the facts pushing inaccurate covid 19 boosters that target the most common omicron strains are set to begin soon 19 update 84 new covid 19 cases reported on september 2 uptown c the website says covid 19 vaccine update cdc now recommends the new updated tucson area coronavirus developments sept 3 what we know billion of tax payer money went to people in prison k datastudio tells us covid has been the 3 cause of death in canada for three years running and yeah county will no longer require covid 19 vaccines for its decontamination and cleaning of their patrol vehicle 66 to prevent the transmission of the deadly covid 1 demands rs 1 000 crore from covid 19 vaccine makers for daughter s death bombay hc issues notice to sii bill friendlycovid19 it s a booster so what doesn t mean the people won t get a visit from our friendly neighborhood covid 19 jeffrey kaami mobile patrol pnco of ozamiz cps under the direct supervision of pmaj dennis pe tano offi officials ordered a lockdown thursday for 21 million people in the southwestern city of chengdu citing an insomniacsmarty oh wow the movie was on tv years ago then i remembered it when the pandemic started one common locks down 21 million people in chengdu over covid 19 outbreak times of a j christ nowplaying x lilroyce her evil spine new coronavirus cases reported in punjab newspaper all this money them niggas better capture moscow and give to us as compensation 19 update india reports 7 219 new covid 19 cases in the last 24 hours personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted pr huffpost she probably most likely got the covid 19 vax it s designed to kill murder elderly and poc persons of it is mandatory for you to wear a face mask at all times at the station or on board the train together le are still other ways to get free covid 19 tests although they may be less convenient than the white house s covid19 india covid 19 update last 24 hours new cases 7 219 recoveries 9 651 active cases 56 745 covid bonginoreport cdc panel votes in favor of recommending new covid 19 boosters that were never tested on human beings redesigned covid 19 booster shots could be available in minnesota as early as alaayous3 way officials are allowing one person in each household to go out to buy necessities once a day the person must pre s covid 19 positivity rate 7 times national average medical surgical laboratory rehabilitation equipments coronavirus preventive kits machines machine s acc tuvillanofv nowplaying x lilroyce her evil spine feat makrazy s covid 19 positivity rate 7 times national average odisha reports 174 new covid19 cases in the last 24 hours 0 18 years 13 in quarantine 102 local contacts 72 s money for everything amp everyone except the peasants it on my 5 year old to protect herself rather than modeling for her how communities protect one another that mile marker 0 cnn has mostly stayed on the right side of things although they can be cr nikkihaley nikki you mean the man who encouraged citizens to drink bleach to kill the covid 19 virus words just disgusted that money should never have been sent to prisoners give to the victims of crime of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri safe stay indoor please follow guidelines issued by authorities save yourself to save others michrajah dr ananda rajah what are your thoughts as a doctor on the proposal to scrap isolation in covid19 managem robytweet sadly i wonder how often it projection it seemed like a lot of the early wave of antivax coronavirus cases in china stayed at elevated levels following the lockdown of a mega city of 21 million as th our presentation of the arctic covid 19 gender response tracker at arctic circle arctic circle assembly s me out why does it say here that people should choose mrna as 3rd boosters when people only need tw josephs26340531 i survived this long by not listening to an orange overlord ar in india live updates india reports 7 219 fresh cases and 9 651 recoveries in the last 24 fda approves the new covid 19 booster before doing human trials instead opting to judge it safe for huma should be put on unpaid leave and then quietly fired like the unvaccinated were personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer i m not happy with biden either on this but at least i historical precedents impeded recognition of airborne covid 19 transmission bonginoreport cdc panel voters in favor of recommending covid 19 boosters that never been tested on human beings want to see your real vaccinations nobody in their right mind would get all of these murdering injections a j christ nowplaying x lilroyce tstorm05 live guyton don t get your issue your boy likes vaccines too trump s latest tweet on coronavirus might be his dumbest yet the borders have opened up human trafficking has increased how do you wash billions of dollars por 19 response plan la county department of public personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer he s part of the labor participation problem by hyping u xe2 fda authorized updated covid 19 booster shots are effective experts say personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re just gonna be this over and over until we finally collapse in on ourselves the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p 19 vaccines didn work so cdc changed the definition of vaccines via the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu 1 000 reports of adverse events after covid 19 vaccination in toddlers babies covid 19 test has been stopped by south korea for inbound travellers covid19 to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di yorlyx s weekly covid 19 cases 27 august 1 september 2022 trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc case wasn aware for newly authorized covid 19 boosters based on mice not humans via the church then audit the hell out of them failed gop candidate says god will end covid 19 if u s condemns hold out the longest got an appt for sunday bivalentbooster oregon freeman and matt hancock argued at first covid 19 cobra the national have the right to refuse unsafe work but do not have the right to determine what is considered unsafe good l kuyashii desu whyyyy but haru yo koi that program saved me during my lonely nights working at covid 19 facility 219 infections india s covid 19 tally of cases to 44 49 726 death toll climbs to 27 965 govt have injected 70m of our people of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic lie friska adv eliz dara0 abidin l1e adv gateway lease waived rent waived rent reduced financial relief due to covid 19 sign the petition covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p wonder what irving city council member al zapanta is doing about covid 19 in their district company profits are collapsing like its 2020 again news social impact the perfect enemy reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity r xf0 for more details visit india india profawpeet does the fact and its affiliates get over 10 000 000 in funding yearly from the nih make you l promotes sex heavy heavy heavy like most women in the industry but she never really says nothing for you to l this blog from dra pat testing keep your staff homes safe from coronavirus if they working from home suemidd58863059 really not hard start your reading here there are now new booster appointments available at cvs and walgreens just scheduled mine at the first avail suspends chinese airline flights in covid 19 19 vaccine effectiveness plunges against omicron cdc data via you believe this two elderly men theirselves saying the elderly should voluntarily die to save the economy nile virus 2nd human case this year found in massachusetts t co rrjxht8t4g xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp am sure they won stop u from wearing a mask if u choose to wear one trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc xe2 the alarm bells are ringing for jobseeker so why is there now room in the budget covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates who coronavirus disease covid 19 dashboard with vaccination data 2 september 2022 there have been 515 30 covid 19 is real mockingbird msm singing from same hymn sheet effective brainwashing used with covid19 and vaccine expectancy drops in america due to covid 19 courtesy of david flickr cc0 in 2021 the life expectancy dropped requirements south korea travel advice irs is not randomly giving away 782 as covid 19 disaster relief clicking on the link in the email will lead hello all greetings from the breadbasket states we are alive and well without masks here um serious quest covid19 now by going to your local and eating a handful of little powerful hot peppers they wil vanessa10009 the lancet covid 19 commission is headed by jeffrey sachs a person with no domain expertise in any r can we have a report on covid19 handling in india for 2021 please you get a new covid 19 booster if so when android app reviews iot flutter javascript serverless cybersecurity seosmmworld 19 gave new urgency to the science of restoring has evolved to make you sicker quicker new study finds marshablackburn biden inherited a total mess from trump who just lost his job because of his gross negligence in orla9000 the massive levels of government spending that congress threw at the pandemic including vax camps to be held on all sundays in september tn health minister source the new indian express vaxcamp stuyvesantanna yeah the study that cites the covid19 vaccine works against relaxbdg nowplaying x lilroyce her evil spine feat makrazy google maps reviews datascience python ai 100daysofcode iot truck group is hiring in elmhurst for a hr benefits administrator click now to apply rpbreakingnews new covid 19 boosters that target today most common omicron strains are set to begin soon i am fr latest the vaccines worldcourts science daily thanks to schofield covid19 science covid 19 outcomes increase in latest manitoba report cbc news xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp governors gave lucrative no bid covid 19 deals to utah firms who then gave 1m to gop campaigns if people want to see the end of mask wearing then we need to replace masks with other public health measures that updates unionhealthministry coronavirus patientsundertreatment deathofpatients covid19 infectionrate the 51 deaths in august are more than the june and july fatalities doctors say most of these cases are among lead stories in major taiwan dailies on saturday covid19 vaccine local government elections stock picks covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates wyonaf we have a friend whose maga husband was an ardent trump er an antimask amp antivax er he was lucky an 19 jammu and kashmir reports 152 new cases of the new cases 40 were reported from jammu and 112 from kashmi right now wakeuplagos w 176 days to nigeria s general election whose camp currently h demands rs 1 000 crore from covid19 vaccine makers for daughter s death bombay hc issues notice to sii bill authorizes updated covid 19 boosters despite lack of clinical data via t co tnexyq4klr the fda and cdc have approved new bivalent vaccines by pfizer and moderna that target both tppatriots cdc panel votes in favor of recommendi

In [12]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [13]:
processed_docs = preprocess(complete_text)

In [14]:
'''
Create a dictionary from 'processed_docs' containing the number of times a word appears 
in the training set using gensim.corpora.Dictionary and call it 'dictionary'
'''
dictionary = gensim.corpora.Dictionary([processed_docs])

In [15]:
'''
Checking dictionary created
'''
count = 0
for k, v in dictionary.iteritems():
    print(k, v)
    count += 1
    if count > 10:
        break

0 aaaaaaaaa
1 aajtak
2 aapi
3 aapl
4 aarogya
5 aaron
6 aarondodd
7 aaronla
8 aaronparna
9 aarospeir
10 aayeff

In [ ]:
#dictionary.filter_extremes(no_below=20, no_above=0.1, keep_n= 1000000)
#dictionary.filter_extremes(no_above=0.70)

In [ ]:
dictionary

In [16]:
#bow_corpus = dictionary.doc2bow(processed_docs)

bow_corpus = [dictionary.doc2bow(processed_docs),]
#bow_corpus = [dictionary.doc2bow(text) for text in processed_docs]
print(bow_corpus[:1])

[[(0, 1), (1, 8), (2, 1), (3, 1), (4, 1), (5, 1), (6, 2), (7, 1), (8, 3), (9, 1), (10, 1), (11, 2), (12, 1), (13, 11), (14, 5), (15, 2), (16, 1), (17, 1), (18, 1), (19, 1), (20, 2), (21, 1), (22, 2), (23, 1), (24, 1), (25, 1), (26, 3), (27, 2), (28, 1), (29, 1), (30, 1), (31, 11), (32, 30), (33, 15), (34, 1), (35, 1), (36, 1), (37, 1), (38, 5), (39, 1), (40, 1), (41, 5), (42, 14), (43, 1), (44, 1), (45, 5), (46, 3), (47, 2), (48, 1), (49, 31), (50, 1), (51, 2), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 1), (58, 1), (59, 10), (60, 1), (61, 1), (62, 7), (63, 2), (64, 3), (65, 1), (66, 1), (67, 13), (68, 1), (69, 1), (70, 1), (71, 18), (72, 1), (73, 27), (74, 1), (75, 6), (76, 1), (77, 1), (78, 1), (79, 5), (80, 1), (81, 41), (82, 1), (83, 149), (84, 1), (85, 1), (86, 2), (87, 7), (88, 1), (89, 19), (90, 1), (91, 1), (92, 2), (93, 1), (94, 12), (95, 7), (96, 2), (97, 7), (98, 1), (99, 1), (100, 5), (101, 1), (102, 1), (103, 1), (104, 1), (105, 1), (106, 5), (107, 7), (108, 1), (109, 33), (110, 1), (111, 235), (112, 4), (113, 2), (114, 1), (115, 1), (116, 82), (117, 2), (118, 20), (119, 1), (120, 3), (121, 1), (122, 1), (123, 1), (124, 6), (125, 1), (126, 1), (127, 5), (128, 1), (129, 1), (130, 29), (131, 2), (132, 1), (133, 19), (134, 1), (135, 1), (136, 24), (137, 1), (138, 5), (139, 1), (140, 1), (141, 2), (142, 2), (143, 1), (144, 1), (145, 1), (146, 2), (147, 3), (148, 1), (149, 5), (150, 1), (151, 1), (152, 1), (153, 1), (154, 1), (155, 1), (156, 10), (157, 2), (158, 1), (159, 10), (160, 1), (161, 49), (162, 1), (163, 57), (164, 6), (165, 25), (166, 39), (167, 3), (168, 6), (169, 39), (170, 1), (171, 1), (172, 1), (173, 2), (174, 2), (175, 1), (176, 1), (177, 1), (178, 62), (179, 1), (180, 11), (181, 1), (182, 2), (183, 142), (184, 1), (185, 1), (186, 5), (187, 4), (188, 23), (189, 28), (190, 3), (191, 18), (192, 8), (193, 2), (194, 13), (195, 1), (196, 1), (197, 3), (198, 12), (199, 2), (200, 63), (201, 3), (202, 3), (203, 1), (204, 1), (205, 3), (206, 1), (207, 1), (208, 1), (209, 4), (210, 1), (211, 1), (212, 1), (213, 1), (214, 1), (215, 14), (216, 29), (217, 7), (218, 1), (219, 4), (220, 4), (221, 1), (222, 1), (223, 2), (224, 1), (225, 1), (226, 49), (227, 1), (228, 1), (229, 33), (230, 3), (231, 14), (232, 11), (233, 1), (234, 1), (235, 1), (236, 1), (237, 1), (238, 1), (239, 1), (240, 1), (241, 29), (242, 3), (243, 1), (244, 3), (245, 1), (246, 45), (247, 1), (248, 1), (249, 1), (250, 1), (251, 16), (252, 2), (253, 1), (254, 1), (255, 3), (256, 1), (257, 1), (258, 2), (259, 1), (260, 1), (261, 26), (262, 1), (263, 1), (264, 2), (265, 1), (266, 8), (267, 2), (268, 4), (269, 1), (270, 1), (271, 1), (272, 1), (273, 2), (274, 1), (275, 1), (276, 1), (277, 1), (278, 1), (279, 1), (280, 1), (281, 1), (282, 3), (283, 1), (284, 1), (285, 1), (286, 1), (287, 1), (288, 1), (289, 3), (290, 1), (291, 1), (292, 1), (293, 1), (294, 1), (295, 1), (296, 1), (297, 1), (298, 1), (299, 1), (300, 15), (301, 5), (302, 2), (303, 1), (304, 6), (305, 1), (306, 2), (307, 3), (308, 11), (309, 1), (310, 1), (311, 1), (312, 7), (313, 11), (314, 3), (315, 2), (316, 1), (317, 13), (318, 1), (319, 1), (320, 18), (321, 3), (322, 1), (323, 1), (324, 1), (325, 1), (326, 7), (327, 2), (328, 2), (329, 3), (330, 1), (331, 2), (332, 1), (333, 1), (334, 1), (335, 1), (336, 1), (337, 3), (338, 1), (339, 1), (340, 2), (341, 1), (342, 2), (343, 1), (344, 2), (345, 2), (346, 1), (347, 1), (348, 1), (349, 1), (350, 10), (351, 1), (352, 3), (353, 1), (354, 1), (355, 18), (356, 2), (357, 1), (358, 1), (359, 1), (360, 8), (361, 3), (362, 2), (363, 9), (364, 2), (365, 3), (366, 40), (367, 1), (368, 2), (369, 1), (370, 6), (371, 2), (372, 2), (373, 4), (374, 3), (375, 1), (376, 2), (377, 1), (378, 2), (379, 2), (380, 1), (381, 1), (382, 1), (383, 1), (384, 4), (385, 10), (386, 1), (387, 1), (388, 6), (389, 2), (390, 1), (391, 1), (392, 1), (393, 6), (394, 1), (395, 2), (396, 15), (397, 6), (398, 11), (399, 1), (400, 1), (401, 1), (402, 3), (403, 1), (404, 2), (405, 1), (406, 1), (407, 1), (408, 3), (409, 1), (410, 1), (411, 60), (412, 164), (413, 1), (414, 1), (415, 1), (416, 1), (417, 39), (418, 4), (419, 1), (420, 1), (421, 1), (422, 1), (423, 1), (424, 1), (425, 3), (426, 3), (427, 3), (428, 1), (429, 7), (430, 2), (431, 1), (432, 3), (433, 1), (434, 1), (435, 1), (436, 1), (437, 1), (438, 1), (439, 1), (440, 5), (441, 1), (442, 53), (443, 4), (444, 10), (445, 6), (446, 1), (447, 1), (448, 1), (449, 1), (450, 1), (451, 1), (452, 1), (453, 1), (454, 1), (455, 1), (456, 5), (457, 2), (458, 1), (459, 3), (460, 2), (461, 1), (462, 1), (463, 1), (464, 17), (465, 1), (466, 2), (467, 1), (468, 1), (469, 1), (470, 1), (471, 1), (472, 1), (473, 1), (474, 1), (475, 1), (476, 1), (477, 1), (478, 1), (479, 22), (480, 1), (481, 1), (482, 2), (483, 1), (484, 1), (485, 1), (486, 4), (487, 1), (488, 1), (489, 1), (490, 2), (491, 20), (492, 1), (493, 3), (494, 1), (495, 1), (496, 1), (497, 2), (498, 1), (499, 1), (500, 1), (501, 1), (502, 1), (503, 1), (504, 1), (505, 2), (506, 2), (507, 1), (508, 1), (509, 1), (510, 48), (511, 2), (512, 11), (513, 1), (514, 1), (515, 1), (516, 1), (517, 1), (518, 35), (519, 1), (520, 1), (521, 1), (522, 6), (523, 1), (524, 1), (525, 43), (526, 2), (527, 1), (528, 16), (529, 1), (530, 4), (531, 1), (532, 1), (533, 4), (534, 20), (535, 1), (536, 2), (537, 1), (538, 6), (539, 2), (540, 1), (541, 6), (542, 3), (543, 19), (544, 1), (545, 1), (546, 2), (547, 1), (548, 1), (549, 1), (550, 1), (551, 10), (552, 2), (553, 2), (554, 22), (555, 1), (556, 2), (557, 1), (558, 1), (559, 8), (560, 1), (561, 1), (562, 1), (563, 2), (564, 1), (565, 1), (566, 10), (567, 1), (568, 1), (569, 1), (570, 1), (571, 2), (572, 18), (573, 1), (574, 8), (575, 26), (576, 1), (577, 6), (578, 1), (579, 1), (580, 22), (581, 28), (582, 25), (583, 2), (584, 1), (585, 1), (586, 15), (587, 2), (588, 14), (589, 1), (590, 10), (591, 337), (592, 2), (593, 6), (594, 4), (595, 1), (596, 1), (597, 1), (598, 2), (599, 16), (600, 1), (601, 1), (602, 1), (603, 3), (604, 1), (605, 1), (606, 1), (607, 2), (608, 1), (609, 1), (610, 1), (611, 3), (612, 1), (613, 1), (614, 1), (615, 2), (616, 3), (617, 1), (618, 1), (619, 1), (620, 37), (621, 38), (622, 2), (623, 1), (624, 15), (625, 11), (626, 1), (627, 5), (628, 1), (629, 1), (630, 5), (631, 1), (632, 1), (633, 3), (634, 1), (635, 8), (636, 1), (637, 1), (638, 1), (639, 30), (640, 1), (641, 1), (642, 1), (643, 2), (644, 2), (645, 1), (646, 1), (647, 6), (648, 13), (649, 30), (650, 3), (651, 1), (652, 1), (653, 2), (654, 2), (655, 1), (656, 2), (657, 1), (658, 1), (659, 91), (660, 1), (661, 1), (662, 6), (663, 2), (664, 1), (665, 1), (666, 1), (667, 1), (668, 1), (669, 2), (670, 2), (671, 1), (672, 2), (673, 5), (674, 8), (675, 1), (676, 1), (677, 1), (678, 1), (679, 1), (680, 1), (681, 1), (682, 10), (683, 1), (684, 10), (685, 3), (686, 1), (687, 1), (688, 61), (689, 1), (690, 1), (691, 1), (692, 3), (693, 1), (694, 1), (695, 3), (696, 1), (697, 1), (698, 2), (699, 1), (700, 3), (701, 3), (702, 6), (703, 1), (704, 23), (705, 1), (706, 1), (707, 4), (708, 3), (709, 16), (710, 2), (711, 1), (712, 82), (713, 1), (714, 1), (715, 8), (716, 2), (717, 2), (718, 2), (719, 1), (720, 1), (721, 4), (722, 1), (723, 1), (724, 1), (725, 1), (726, 1), (727, 1), (728, 1), (729, 1), (730, 1), (731, 1), (732, 2), (733, 1), (734, 10), (735, 1), (736, 1), (737, 2), (738, 1), (739, 9), (740, 4), (741, 1), (742, 1), (743, 1), (744, 3), (745, 1), (746, 1), (747, 1), (748, 120), (749, 3), (750, 10), (751, 18), (752, 3), (753, 16), (754, 1), (755, 2), (756, 2), (757, 1), (758, 1), (759, 9), (760, 3), (761, 1), (762, 1), (763, 6), (764, 5), (765, 8), (766, 1), (767, 5), (768, 35), (769, 2), (770, 1), (771, 1), (772, 1), (773, 1), (774, 4), (775, 1), (776, 15), (777, 5), (778, 2), (779, 1), (780, 2), (781, 4), (782, 2), (783, 49), (784, 13), (785, 4), (786, 1), (787, 1), (788, 2), (789, 3), (790, 136), (791, 3), (792, 4), (793, 2), (794, 1), (795, 3), (796, 1), (797, 3), (798, 3), (799, 3), (800, 1), (801, 1), (802, 4), (803, 22), (804, 164), (805, 2), (806, 1), (807, 1), (808, 2), (809, 1), (810, 2), (811, 1), (812, 1), (813, 33), (814, 4), (815, 2), (816, 13), (817, 1), (818, 30), (819, 1), (820, 1), (821, 3), (822, 7), (823, 4), (824, 1), (825, 17), (826, 21), (827, 64), (828, 1), (829, 4), (830, 4), (831, 1), (832, 1), (833, 4), (834, 1), (835, 4), (836, 2), (837, 2), (838, 1), (839, 1), (840, 1), (841, 1), (842, 1), (843, 1), (844, 1), (845, 1), (846, 1), (847, 2), (848, 1), (849, 1), (850, 1), (851, 1), (852, 1), (853, 1), (854, 53), (855, 1), (856, 1), (857, 1), (858, 1), (859, 1), (860, 6), (861, 1), (862, 4), (863, 1), (864, 2), (865, 1), (866, 1), (867, 5), (868, 3), (869, 2), (870, 2), (871, 2), (872, 3), (873, 8), (874, 5), (875, 1), (876, 1), (877, 1), (878, 2), (879, 1), (880, 2), (881, 2), (882, 1), (883, 1), (884, 2), (885, 1), (886, 5), (887, 1), (888, 1), (889, 1), (890, 3), (891, 3), (892, 1), (893, 1), (894, 7), (895, 1), (896, 1), (897, 3), (898, 11), (899, 1), (900, 1), (901, 3), (902, 2), (903, 1), (904, 1), (905, 1), (906, 1), (907, 1), (908, 23), (909, 1), (910, 3), (911, 1), (912, 2), (913, 1), (914, 1), (915, 1), (916, 1), (917, 1), (918, 3), (919, 2), (920, 30), (921, 2), (922, 3), (923, 1), (924, 1), (925, 1), (926, 2), (927, 3), (928, 1), (929, 3), (930, 2), (931, 1), (932, 1), (933, 1), (934, 1), (935, 1), (936, 20), (937, 1), (938, 1), (939, 1), (940, 1), (941, 1), (942, 12), (943, 2), (944, 1), (945, 5), (946, 4), (947, 2), (948, 1), (949, 2), (950, 1), (951, 69), (952, 1), (953, 1), (954, 1), (955, 5), (956, 19), (957, 3), (958, 1), (959, 3), (960, 1), (961, 4), (962, 2), (963, 4), (964, 3), (965, 2), (966, 1), (967, 1), (968, 6), (969, 42), (970, 1), (971, 1), (972, 1), (973, 1), (974, 1), (975, 2), (976, 6), (977, 1), (978, 3), (979, 1), (980, 1), (981, 1), (982, 1), (983, 1), (984, 1), (985, 1), (986, 5), (987, 1), (988, 1), (989, 3), (990, 1), (991, 1), (992, 4), (993, 13), (994, 1), (995, 1), (996, 1), (997, 10), (998, 1), (999, 6), (1000, 24), (1001, 1), (1002, 1), (1003, 6), (1004, 1), (1005, 1), (1006, 3), (1007, 1), (1008, 1), (1009, 1), (1010, 2), (1011, 1), (1012, 1), (1013, 1), (1014, 2), (1015, 161), (1016, 1), (1017, 4), (1018, 1), (1019, 1), (1020, 5), (1021, 1), (1022, 118), (1023, 1), (1024, 6), (1025, 3), (1026, 1), (1027, 1), (1028, 1), (1029, 1), (1030, 7), (1031, 1), (1032, 1), (1033, 1), (1034, 3), (1035, 6), (1036, 101), (1037, 2), (1038, 5), (1039, 1), (1040, 1), (1041, 1), (1042, 2), (1043, 7), (1044, 1), (1045, 1), (1046, 1), (1047, 1), (1048, 1), (1049, 1), (1050, 1), (1051, 1), (1052, 2), (1053, 42), (1054, 1), (1055, 3), (1056, 1), (1057, 1), (1058, 1), (1059, 3), (1060, 4), (1061, 1), (1062, 1), (1063, 2), (1064, 1), (1065, 1), (1066, 1), (1067, 1), (1068, 1), (1069, 1), (1070, 1), (1071, 1), (1072, 1), (1073, 2), (1074, 1), (1075, 1), (1076, 1), (1077, 2), (1078, 70), (1079, 1), (1080, 1), (1081, 1), (1082, 2), (1083, 1), (1084, 1), (1085, 1), (1086, 1), (1087, 1), (1088, 3), (1089, 1), (1090, 1), (1091, 74), (1092, 1), (1093, 1), (1094, 1), (1095, 1), (1096, 1), (1097, 1), (1098, 1), (1099, 1), (1100, 1), (1101, 1), (1102, 1), (1103, 1), (1104, 2), (1105, 5), (1106, 2), (1107, 1), (1108, 1), (1109, 1), (1110, 1), (1111, 2), (1112, 8), (1113, 1), (1114, 7), (1115, 2), (1116, 1), (1117, 1), (1118, 5), (1119, 463), (1120, 1), (1121, 1), (1122, 2), (1123, 1), (1124, 1), (1125, 2), (1126, 1), (1127, 2), (1128, 1), (1129, 1), (1130, 1), (1131, 1), (1132, 8), (1133, 1), (1134, 12), (1135, 1), (1136, 3), (1137, 1), (1138, 3), (1139, 1), (1140, 1), (1141, 1), (1142, 3), (1143, 2), (1144, 1), (1145, 6), (1146, 11), (1147, 2), (1148, 1), (1149, 1), (1150, 6), (1151, 1), (1152, 134), (1153, 5), (1154, 1), (1155, 2), (1156, 2), (1157, 1), (1158, 1), (1159, 1), (1160, 11), (1161, 1), (1162, 1), (1163, 3), (1164, 2), (1165, 1), (1166, 1), (1167, 2), (1168, 1), (1169, 1), (1170, 2), (1171, 1), (1172, 1), (1173, 1), (1174, 12), (1175, 1), (1176, 5), (1177, 2), (1178, 1), (1179, 72), (1180, 2), (1181, 1), (1182, 2), (1183, 1), (1184, 10), (1185, 1), (1186, 1), (1187, 14), (1188, 2), (1189, 2), (1190, 11), (1191, 6), (1192, 1), (1193, 1), (1194, 1), (1195, 1), (1196, 4), (1197, 1), (1198, 2), (1199, 7), (1200, 35), (1201, 1), (1202, 13), (1203, 1), (1204, 1), (1205, 1), (1206, 105), (1207, 1), (1208, 1), (1209, 1), (1210, 1), (1211, 1), (1212, 26), (1213, 1), (1214, 1), (1215, 2), (1216, 1), (1217, 1), (1218, 2), (1219, 1), (1220, 1), (1221, 1), (1222, 1), (1223, 3), (1224, 1), (1225, 1), (1226, 29), (1227, 1), (1228, 4), (1229, 7), (1230, 1), (1231, 1), (1232, 1), (1233, 6), (1234, 1), (1235, 4), (1236, 9), (1237, 10), (1238, 9), (1239, 3), (1240, 1), (1241, 1), (1242, 1), (1243, 103), (1244, 2), (1245, 5), (1246, 1), (1247, 11), (1248, 11), (1249, 2), (1250, 2), (1251, 32), (1252, 1), (1253, 4), (1254, 1), (1255, 4), (1256, 2), (1257, 13), (1258, 1), (1259, 17), (1260, 1), (1261, 1), (1262, 2), (1263, 1), (1264, 1), (1265, 2), (1266, 5), (1267, 9), (1268, 3), (1269, 1), (1270, 1), (1271, 1), (1272, 2), (1273, 1), (1274, 1), (1275, 1), (1276, 1), (1277, 2), (1278, 1), (1279, 1), (1280, 2), (1281, 38), (1282, 1), (1283, 1), (1284, 1), (1285, 1), (1286, 1), (1287, 2), (1288, 2), (1289, 1), (1290, 1), (1291, 1), (1292, 1), (1293, 2), (1294, 1), (1295, 2), (1296, 1), (1297, 2), (1298, 1), (1299, 3), (1300, 1), (1301, 11), (1302, 2), (1303, 1), (1304, 3), (1305, 1), (1306, 1), (1307, 1), (1308, 3), (1309, 1), (1310, 3), (1311, 4), (1312, 1), (1313, 1), (1314, 44), (1315, 1), (1316, 4), (1317, 1), (1318, 40), (1319, 627), (1320, 8), (1321, 1), (1322, 4), (1323, 1), (1324, 24), (1325, 1), (1326, 1), (1327, 6), (1328, 22), (1329, 1), (1330, 11), (1331, 8), (1332, 1), (1333, 1), (1334, 2), (1335, 9), (1336, 3), (1337, 5), (1338, 2), (1339, 3), (1340, 1), (1341, 14), (1342, 1), (1343, 2), (1344, 1), (1345, 2), (1346, 1), (1347, 1), (1348, 3), (1349, 1), (1350, 2), (1351, 1), (1352, 1), (1353, 2), (1354, 1), (1355, 1), (1356, 2), (1357, 1), (1358, 1), (1359, 3), (1360, 1), (1361, 3), (1362, 1), (1363, 1), (1364, 2), (1365, 3), (1366, 2), (1367, 4), (1368, 1), (1369, 2), (1370, 1), (1371, 1), (1372, 42), (1373, 1), (1374, 1), (1375, 1), (1376, 1), (1377, 2), (1378, 1), (1379, 1), (1380, 2), (1381, 5), (1382, 1), (1383, 1), (1384, 2), (1385, 14), (1386, 1), (1387, 4), (1388, 1), (1389, 1), (1390, 4), (1391, 1), (1392, 1), (1393, 1), (1394, 2), (1395, 10), (1396, 1), (1397, 1), (1398, 1), (1399, 3), (1400, 2), (1401, 1), (1402, 48), (1403, 3), (1404, 1), (1405, 1), (1406, 4), (1407, 3), (1408, 1), (1409, 3), (1410, 2), (1411, 1), (1412, 8), (1413, 10), (1414, 1), (1415, 2), (1416, 8), (1417, 1), (1418, 1), (1419, 1), (1420, 1), (1421, 2), (1422, 2), (1423, 1), (1424, 1), (1425, 15), (1426, 1), (1427, 1), (1428, 4), (1429, 3), (1430, 2), (1431, 1), (1432, 4), (1433, 3), (1434, 1), (1435, 1), (1436, 7), (1437, 1), (1438, 2), (1439, 1), (1440, 18), (1441, 1), (1442, 1), (1443, 3), (1444, 5), (1445, 1), (1446, 76), (1447, 1), (1448, 2), (1449, 1), (1450, 2), (1451, 1), (1452, 1), (1453, 2), (1454, 15), (1455, 2), (1456, 3), (1457, 5), (1458, 4), (1459, 1), (1460, 1), (1461, 1), (1462, 1), (1463, 1), (1464, 1), (1465, 1), (1466, 2), (1467, 1), (1468, 2), (1469, 2), (1470, 6), (1471, 5), (1472, 1), (1473, 2), (1474, 2), (1475, 1), (1476, 1), (1477, 1), (1478, 1), (1479, 12), (1480, 4), (1481, 1), (1482, 1), (1483, 1), (1484, 1), (1485, 1), (1486, 2), (1487, 1), (1488, 1), (1489, 10), (1490, 1), (1491, 1), (1492, 1), (1493, 2), (1494, 1), (1495, 2), (1496, 1), (1497, 2), (1498, 1), (1499, 1), (1500, 1), (1501, 70), (1502, 1), (1503, 1), (1504, 2), (1505, 1), (1506, 2), (1507, 2), (1508, 2), (1509, 1), (1510, 9), (1511, 1), (1512, 1), (1513, 1), (1514, 21), (1515, 1), (1516, 2), (1517, 1), (1518, 1), (1519, 1), (1520, 4), (1521, 1), (1522, 2), (1523, 13), (1524, 1), (1525, 2), (1526, 1), (1527, 1), (1528, 1), (1529, 22), (1530, 2), (1531, 1), (1532, 1), (1533, 1), (1534, 9), (1535, 1), (1536, 1), (1537, 1), (1538, 13), (1539, 4), (1540, 2), (1541, 1), (1542, 2), (1543, 1), (1544, 1), (1545, 6), (1546, 1), (1547, 2), (1548, 1), (1549, 1), (1550, 1), (1551, 3), (1552, 1), (1553, 104), (1554, 1), (1555, 1), (1556, 3), (1557, 1), (1558, 3), (1559, 1), (1560, 9), (1561, 3), (1562, 2), (1563, 1), (1564, 1), (1565, 23), (1566, 1), (1567, 1), (1568, 2), (1569, 1), (1570, 1), (1571, 1), (1572, 1), (1573, 1), (1574, 1), (1575, 1), (1576, 1), (1577, 3), (1578, 1), (1579, 1), (1580, 2), (1581, 1), (1582, 1), (1583, 1), (1584, 1), (1585, 1), (1586, 10), (1587, 2), (1588, 1), (1589, 2), (1590, 1), (1591, 1), (1592, 1), (1593, 1), (1594, 1), (1595, 1), (1596, 1), (1597, 2), (1598, 1), (1599, 1), (1600, 1), (1601, 1), (1602, 1), (1603, 1), (1604, 5), (1605, 8), (1606, 1), (1607, 1), (1608, 1), (1609, 1), (1610, 2), (1611, 1), (1612, 72), (1613, 1), (1614, 109), (1615, 1), (1616, 1), (1617, 4), (1618, 1), (1619, 1), (1620, 1), (1621, 5), (1622, 2), (1623, 2), (1624, 1), (1625, 1), (1626, 1), (1627, 1), (1628, 1), (1629, 14), (1630, 59), (1631, 1), (1632, 12), (1633, 4), (1634, 1), (1635, 73), (1636, 72), (1637, 2), (1638, 2), (1639, 53), (1640, 33), (1641, 3), (1642, 2), (1643, 19), (1644, 1), (1645, 1), (1646, 1), (1647, 1), (1648, 8), (1649, 2), (1650, 1), (1651, 1), (1652, 1), (1653, 1), (1654, 3), (1655, 8), (1656, 1), (1657, 2), (1658, 18), (1659, 3), (1660, 4), (1661, 6), (1662, 4), (1663, 1), (1664, 1), (1665, 2), (1666, 1), (1667, 1), (1668, 3), (1669, 3), (1670, 1), (1671, 3), (1672, 42), (1673, 5), (1674, 2), (1675, 1), (1676, 1), (1677, 1), (1678, 1), (1679, 1), (1680, 3), (1681, 18), (1682, 180), (1683, 7), (1684, 1), (1685, 1), (1686, 1), (1687, 3), (1688, 1), (1689, 1), (1690, 5), (1691, 1), (1692, 1), (1693, 1), (1694, 2), (1695, 4), (1696, 2), (1697, 4), (1698, 1), (1699, 3), (1700, 1), (1701, 10), (1702, 1), (1703, 2), (1704, 1), (1705, 1), (1706, 18), (1707, 2), (1708, 1), (1709, 1), (1710, 2), (1711, 5), (1712, 1), (1713, 1), (1714, 1), (1715, 1), (1716, 1157), (1717, 21), (1718, 1), (1719, 2), (1720, 10), (1721, 1), (1722, 2), (1723, 3), (1724, 1), (1725, 1), (1726, 1), (1727, 1), (1728, 3), (1729, 1), (1730, 1), (1731, 1), (1732, 2), (1733, 1), (1734, 2), (1735, 1), (1736, 2), (1737, 43), (1738, 1), (1739, 4), (1740, 1), (1741, 3), (1742, 1), (1743, 1), (1744, 1), (1745, 1), (1746, 1), (1747, 1), (1748, 3), (1749, 132), (1750, 3), (1751, 16), (1752, 3), (1753, 4), (1754, 1), (1755, 1), (1756, 1), (1757, 3), (1758, 8), (1759, 1), (1760, 1), (1761, 1), (1762, 1), (1763, 1), (1764, 1), (1765, 2), (1766, 1), (1767, 1), (1768, 1), (1769, 1), (1770, 1), (1771, 2), (1772, 2), (1773, 1), (1774, 1), (1775, 3), (1776, 1), (1777, 2), (1778, 9), (1779, 1), (1780, 1), (1781, 1), (1782, 1), (1783, 1), (1784, 1), (1785, 1), (1786, 24), (1787, 1), (1788, 1), (1789, 1), (1790, 2), (1791, 1), (1792, 15), (1793, 2), (1794, 4), (1795, 1), (1796, 1), (1797, 1), (1798, 1), (1799, 1), (1800, 9), (1801, 6), (1802, 1), (1803, 10), (1804, 1), (1805, 38), (1806, 1), (1807, 22), (1808, 13), (1809, 1), (1810, 1), (1811, 2), (1812, 1), (1813, 1), (1814, 3), (1815, 2), (1816, 1), (1817, 1), (1818, 1), (1819, 2), (1820, 1), (1821, 1), (1822, 17), (1823, 8), (1824, 1), (1825, 39), (1826, 4), (1827, 3), (1828, 1), (1829, 1), (1830, 1), (1831, 1), (1832, 1), (1833, 1), (1834, 1), (1835, 4), (1836, 18), (1837, 3), (1838, 5), (1839, 1), (1840, 1), (1841, 1), (1842, 2), (1843, 2), (1844, 31), (1845, 1), (1846, 1), (1847, 1), (1848, 1), (1849, 1), (1850, 1), (1851, 2), (1852, 4), (1853, 2), (1854, 2), (1855, 13), (1856, 1), (1857, 1), (1858, 121), (1859, 2), (1860, 10), (1861, 1), (1862, 8), (1863, 1), (1864, 1), (1865, 7), (1866, 1), (1867, 2), (1868, 1), (1869, 2), (1870, 7), (1871, 1), (1872, 19), (1873, 1), (1874, 2), (1875, 3), (1876, 2), (1877, 1), (1878, 1), (1879, 1), (1880, 2), (1881, 1), (1882, 1), (1883, 1), (1884, 2), (1885, 1), (1886, 1), (1887, 19), (1888, 3), (1889, 1), (1890, 1), (1891, 1), (1892, 1), (1893, 1), (1894, 1), (1895, 9), (1896,

In [17]:
#LDA
lda_model = gensim.models.ldamodel.LdaModel(corpus=bow_corpus, 
                                            num_topics = 20, 
                                            id2word = dictionary,
                                            random_state=100,
                                            update_every=1,
                                            chunksize=100,
                                            alpha='auto',
                                            per_word_topics=True,
                                            passes = 50)

In [18]:
for idx, topic in lda_model.print_topics(-1):
    print("Topic: {} \nWords: {}".format(idx, topic ))
    print("\n")

Topic: 0
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"peopl" + 0.000*"death" + 0.000*"coronavirus" + 0.000*"report" + 0.000*"pandem" + 0.000*"time" + 0.000*"booster"


Topic: 1
Words: 0.071*"covid" + 0.014*"vaccin" + 0.011*"case" + 0.010*"coronavirus" + 0.008*"peopl" + 0.007*"death" + 0.007*"report" + 0.006*"pandem" + 0.006*"booster" + 0.005*"trump"


Topic: 2
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"death" + 0.000*"booster" + 0.000*"pandem" + 0.000*"report" + 0.000*"time"


Topic: 3
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"coronavirus" + 0.000*"booster" + 0.000*"death" + 0.000*"peopl" + 0.000*"pandem" + 0.000*"report" + 0.000*"time"


Topic: 4
Words: 0.000*"covid" + 0.000*"case" + 0.000*"peopl" + 0.000*"coronavirus" + 0.000*"vaccin" + 0.000*"booster" + 0.000*"death" + 0.000*"report" + 0.000*"time" + 0.000*"trump"


Topic: 5
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"peopl" + 0.000*"coronavirus" + 0.000*"death" + 0.000*"time" + 0.000*"report" + 0.000*"booster" + 0.000*"trump"


Topic: 6
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"peopl" + 0.000*"coronavirus" + 0.000*"pandem" + 0.000*"death" + 0.000*"report" + 0.000*"ivermectin" + 0.000*"biden"


Topic: 7
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"peopl" + 0.000*"case" + 0.000*"report" + 0.000*"death" + 0.000*"pandem" + 0.000*"ivermectin" + 0.000*"coronavirus" + 0.000*"test"


Topic: 8
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"case" + 0.000*"death" + 0.000*"report" + 0.000*"trump" + 0.000*"pandem" + 0.000*"test"


Topic: 9
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"case" + 0.000*"peopl" + 0.000*"death" + 0.000*"report" + 0.000*"ivermectin" + 0.000*"pandem" + 0.000*"booster"


Topic: 10
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"report" + 0.000*"death" + 0.000*"trump" + 0.000*"like" + 0.000*"ivermectin"


Topic: 11
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"case" + 0.000*"report" + 0.000*"death" + 0.000*"pandem" + 0.000*"booster" + 0.000*"biden"


Topic: 12
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"report" + 0.000*"pandem" + 0.000*"coronavirus" + 0.000*"death" + 0.000*"peopl" + 0.000*"trump" + 0.000*"booster"


Topic: 13
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"health" + 0.000*"report" + 0.000*"pandem" + 0.000*"death" + 0.000*"biden"


Topic: 14
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"case" + 0.000*"death" + 0.000*"report" + 0.000*"pandem" + 0.000*"peopl" + 0.000*"trump" + 0.000*"booster"


Topic: 15
Words: 0.000*"covid" + 0.000*"case" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"peopl" + 0.000*"death" + 0.000*"booster" + 0.000*"report" + 0.000*"time" + 0.000*"pandem"


Topic: 16
Words: 0.001*"asiri" + 0.001*"grtting" + 0.001*"cassielillian" + 0.001*"gennfujita" + 0.001*"volun" + 0.001*"leaki" + 0.001*"zhangzhan" + 0.001*"waxer" + 0.001*"osazu" + 0.001*"sasswasher"


Topic: 17
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"coronavirus" + 0.000*"case" + 0.000*"report" + 0.000*"peopl" + 0.000*"ivermectin" + 0.000*"booster" + 0.000*"death" + 0.000*"test"


Topic: 18
Words: 0.000*"covid" + 0.000*"case" + 0.000*"vaccin" + 0.000*"peopl" + 0.000*"death" + 0.000*"report" + 0.000*"coronavirus" + 0.000*"pandem" + 0.000*"trump" + 0.000*"booster"


Topic: 19
Words: 0.000*"covid" + 0.000*"vaccin" + 0.000*"case" + 0.000*"coronavirus" + 0.000*"death" + 0.000*"peopl" + 0.000*"report" + 0.000*"trump" + 0.000*"booster" + 0.000*"pandem"

In [19]:
import re
import numpy as np
import pandas as  pd
from pprint import pprint# Gensim
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
#from gensim.models import CoherenceModel# spaCy for preprocessing
import spacy# Plotting tools
#import pyLDAvis
#import pyLDAvis.gensim
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
!pip3 install spacy

!python3 -m spacy download en #Language model

#pip3 install gensim # For topic modeling

#pip3 install pyLDAvis # For visualizing topic models

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.4.1)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.1.2)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.9.2)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.1)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.1.1)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.8)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.9.24)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.8)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.0.2)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)
2022-10-09 12:53:49.088193: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting en-core-web-sm==3.4.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 2.0 MB/s
Requirement already satisfied: spacy<3.5.0,>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.4.0) (3.4.1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (21.3)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (8.1.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.9.2)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.1.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.3)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.3.0)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.6.2)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.10.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.11.3)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.21.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.8)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.23.0)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.4.4)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.7)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.4.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.10)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.64.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (57.4.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (5.2.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.4)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.0.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
# NLTK Stop words
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
stop_words.extend(['from', 'subject', 're', 'edu', 'use'])

In [ ]:
def sent_to_words(sentences):
  for sentence in sentences:
    yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))            #deacc=True removes punctuations

In [ ]:
data_words = list(sent_to_words(data))
print(data_words[:1])

In [ ]:
bigram = gensim.models.Phrases(data_words, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=100)
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)
print(trigram_mod[bigram_mod[data_words[0]]])

In [ ]:
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stop_words] for doc in texts]

def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]

def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]

def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

In [ ]:
data_words_nostops = remove_stopwords(data_words)
data_words_bigrams = make_bigrams(data_words_nostops)
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])
data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

In [ ]:
print(data_lemmatized[:5])

[['believe'], ['record', 'new', 'covid', 'case'], ['county', 'long', 'require', 'covid', 'vaccine', 'employee'], ['capital', 'give', 'dose', 'covid', 'vaccine', 'people'], []]

In [ ]:
id2word = corpora.Dictionary(data_lemmatized)  
texts = data_lemmatized  
corpus = [id2word.doc2bow(text) for text in texts]  
print(corpus[:1])

[[(0, 1)]]

In [ ]:
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=20, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=50,
                                           passes=50,
                                           alpha='auto',
                                           per_word_topics=True)

In [ ]:
from pprint import pprint
pprint(lda_model.print_topics())

[(0,
  '0.067*"die" + 0.051*"take" + 0.040*"want" + 0.037*"mask" + 0.026*"global" + '
  '0.025*"cause" + 0.024*"let" + 0.017*"comment" + 0.016*"issue" + '
  '0.013*"measure"'),
 (1,
  '0.055*"amp" + 0.046*"still" + 0.035*"good" + 0.029*"child" + 0.026*"week" + '
  '0.023*"month" + 0.022*"available" + 0.021*"help" + 0.020*"connect" + '
  '0.017*"repmtg"'),
 (2,
  '0.068*"work" + 0.056*"make" + 0.045*"stop" + 0.028*"read" + 0.027*"last" + '
  '0.024*"keep" + 0.023*"hard" + 0.021*"testing" + 0.021*"consider" + '
  '0.015*"enough"'),
 (3,
  '0.179*"vaccine" + 0.038*"patient" + 0.034*"long" + 0.033*"news" + '
  '0.024*"infect" + 0.019*"omicron" + 0.018*"resident" + 0.017*"warning" + '
  '0.013*"stimulus_check" + 0.013*"isolation"'),
 (4,
  '0.051*"study" + 0.042*"day" + 0.034*"lie" + 0.029*"see" + 0.020*"life" + '
  '0.020*"never" + 0.018*"lose" + 0.017*"follow" + 0.016*"home" + '
  '0.015*"look"'),
 (5,
  '0.066*"time" + 0.035*"think" + 0.032*"datum" + 0.027*"thank" + '
  '0.024*"source" + 0.021*"post" + 0.018*"recover" + 0.016*"business" + '
  '0.016*"worker" + 0.015*"benefit"'),
 (6,
  '0.283*"case" + 0.033*"believe" + 0.029*"active" + 0.023*"daily" + '
  '0.018*"current" + 0.016*"situation" + 0.016*"story" + 0.015*"obvious" + '
  '0.012*"register" + 0.012*"deaths_recovere"'),
 (7,
  '0.536*"covid" + 0.079*"people" + 0.022*"risk" + 0.018*"need" + '
  '0.015*"sky_moon" + 0.013*"bad" + 0.011*"care" + 0.011*"mangubat_support" + '
  '0.011*"school" + 0.010*"social_distance"'),
 (8,
  '0.067*"test" + 0.029*"use" + 0.022*"away" + 0.019*"service" + 0.019*"fight" '
  '+ 0.019*"price" + 0.018*"summer" + 0.015*"travel" + 0.015*"pass" + '
  '0.015*"excess"'),
 (9,
  '0.101*"go" + 0.033*"thing" + 0.026*"right" + 0.021*"response" + '
  '0.021*"accountable" + 0.021*"remember" + 0.020*"start" + '
  '0.019*"rep_marjorie" + 0.019*"taylor_greene" + 0.018*"mean"'),
 (10,
  '0.183*"report" + 0.075*"update" + 0.033*"rise" + 0.032*"certificate" + '
  '0.016*"second_day" + 0.015*"concern" + 0.014*"foreign" + 0.011*"later" + '
  '0.011*"contact" + 0.011*"msm"'),
 (11,
  '0.057*"health" + 0.054*"infection" + 0.053*"country" + 0.034*"change" + '
  '0.031*"rate" + 0.025*"do" + 0.024*"protection" + 0.021*"medium" + '
  '0.018*"ban" + 0.018*"emergency"'),
 (12,
  '0.157*"new" + 0.126*"death" + 0.073*"booster" + 0.063*"know" + 0.041*"year" '
  '+ 0.029*"kill" + 0.026*"love" + 0.022*"fall" + 0.021*"today" + '
  '0.020*"positive"'),
 (13,
  '0.101*"pandemic" + 0.054*"total" + 0.048*"find" + 0.037*"way" + '
  '0.025*"state" + 0.021*"treatment" + 0.018*"reveal" + 0.018*"include" + '
  '0.018*"approve" + 0.017*"article"'),
 (14,
  '0.056*"virus" + 0.051*"grandmother" + 0.043*"trump" + 0.043*"many" + '
  '0.035*"well_right" + 0.035*"first" + 0.033*"number" + 0.024*"back" + '
  '0.020*"confirm" + 0.019*"actually"'),
 (15,
  '0.064*"coronavirus" + 0.038*"give" + 0.035*"show" + 0.031*"high" + '
  '0.028*"world" + 0.027*"air" + 0.026*"well" + 0.023*"hit" + 0.018*"result" + '
  '0.018*"record"'),
 (16,
  '0.043*"government" + 0.029*"late" + 0.028*"due" + 0.027*"increase" + '
  '0.023*"ease" + 0.022*"rule" + 0.022*"learn" + 0.020*"impact" + '
  '0.016*"claim" + 0.016*"restriction"'),
 (17,
  '0.135*"say" + 0.024*"worry" + 0.023*"expert" + 0.023*"far" + 0.022*"figure" '
  '+ 0.022*"policy" + 0.018*"become" + 0.015*"twitter" + 0.014*"bring" + '
  '0.013*"speak"'),
 (18,
  '0.201*"get" + 0.050*"vaccination" + 0.023*"trump_maga" + '
  '0.023*"adverse_event" + 0.019*"spread" + 0.017*"sorry" + 0.017*"prevent" + '
  '0.016*"wait" + 0.013*"admit" + 0.010*"immunity"'),
 (19,
  '0.062*"come" + 0.057*"lead" + 0.037*"hospital" + 0.033*"call" + 0.030*"try" '
  '+ 0.025*"maybe" + 0.022*"ivermectin" + 0.019*"folk" + 0.017*"disease" + '
  '0.017*"regular"')]

In [ ]:
doc_lda = lda_model[corpus]

In [ ]:
# Compute Perplexity
print('\nPerplexity: ', lda_model.log_perplexity(corpus))

In [ ]:
# Compute Coherence Score
from gensim.models import CoherenceModel# spaCy for preprocessing
coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)

Coherence Score:  0.5747205099331698

In [ ]:
for idx, topic in lda_model.show_topics(formatted=False, num_topics=20,num_words= 100):
    print('Topic: {} \nWords: {}'.format(idx, '|'.join([w[0] for w in topic])))

Topic: 0
Words: die|take|want|mask|global|cause|let|comment|issue|measure|avoid|thread|app|loss|stupid|reinstate|hide|proof|mind|past|hurt|wear|arrest|like|physically|experience|brother|deliver|restaurant|teacher|economic|growth|pand|whole|page|campaign|sudden|star|message|region|blood|scare|ad|reflect|slip|murder|appropriate|shut|panel|seriously|play|car|cancer|anywhere|cost|immigrant|football|radio|game|jail|nose|exacerbate|beg|donald_trump|everywhere|morning|alone|spike|cross|insanity|plant|taste|metric|living|injection|internet|opinion|survivor|framework|smell|alternative|bubble|regional|m|smear|argue|drjbhattacharya|horn|pain|viral|jab|profile|personnel|impairment|assault|market_size|advertising|barrier|hunger|clot
Topic: 1
Words: amp|still|good|child|week|month|available|help|connect|repmtg|upon_time|safe|effective|reduction|prove|biden_ukriane|receive|doctor|family|serena_trump|ukriane|maga_biden|turn|check|booster_shot|boost|bedtime_story|filter|advise|door|flu|pretty|medicine|criminal|able|practice|legislation|second|bill|united_state|gift|vacation|view|educate|cough|book|budget_time|taxis|act|touch|finish|precaution|law|request|informed_qanta|peak|lol|pregnant|abandoned_thiland|restart|access|vi|birth|hiatus_due|setting|short|healthcare|info|system|interval|ill|shoot|crowd|xe|fatigue|serenawilliam|dictator|nhs|healthy|trial|priority|witness|zombie|unrealengine|indiegame|door_ministry|warrant|reminder|diabetes|countries_significant|expire|abuse|narrative|surpass|nurse|beach|stoolpresidente|around|mayoisspicyy|trust
Topic: 2
Words: work|make|stop|read|last|keep|hard|testing|consider|enough|shit|sure|part|test_positive|miss|hand|carry|understand|wearing_mask|refuse|evidence|physical|yesterday|hope|key|team|surprise|staff|quality|every_day|move|dumb|triple|worldwide|sector|walgreen|schedule|suggests_canadian|lab|sh|location|sense|match|pharmaceutical|entire|basic|revenue|energy|barely|fucking|wash|madness|insurance|republican|fully|opportunity|easily|engagement|poison|certain|spot|ambassador_line|australia_warn|statistical|condition|smart|risky|toronto_sun|cover|kitchen|grant|east_timor|option|coronaviru|mouth|episode|communicate|bost|appointment|bottom|irreversible|induce|peopl|upcoming|amazing|visa|print|digital_qr|colleague|closure|hero|university|without_take|recall|playbook|ridiculous|debate|association|deploy|select
Topic: 3
Words: vaccine|patient|long|news|infect|omicron|resident|warning|stimulus_check|isolation|co|face|administer|estimate|recently|monkeypox|remove|trend|pfizer|name|force|reality|county|reach|fake|own|write|true|hold|require|dip|self|fair|cov|dropping|employee|cut|issues_emergency|military|mislead|bit|medication|essential|irs_admit|inmates_receive|covidisairborne|cdc_data|retweet|effectiveness_plunge|pcr_t|pediatric|al|sub|fascism|private|wa|chinese_tech|convenient|fully_vaccinate|sue|daughter|peter_mccullough|effort|suit|adverse|strongly|hub_shenzhen|title|moderna|dilute|efficacy|controls_tighten|definition|hopefully|navigate|brief|astrazeneca|improve|incarcerate|unclear|timrunshismouth|invest|newspaper|inmate|foot|goal|deny|injury|denier|previously|inquiry|informed_qanta|aka|abandoned_thiland|disruptive|routinely|cdc_change|stevebarclay|letter|rollout
Topic: 4
Words: study|day|lie|see|life|never|lose|follow|home|look|live|job|pay|tell|reduce|also|kid|problem|medical|research|low|happen|ever|ask|peer_reviewe|outbreak|great|fact|much|almost|scientist|end|set|begin|watch|shot|account|target|man|lockdown|fail|full|open|recommend|variant|economy|age|mandate|create|sign|absolutely|soon|partner|scientists_patient|treatment_guideline|truth|drug|machine|decrease|therapy|relate|example|freedom|fund|support|big|water|place|return|researcher|winter|heart|exist|pretend|save|administration|laws_move|complete|win|suffer|rat|add|regard|website|resource|ten|stream|push|common|case_number|strong|liberal|mortality|address|pulmonary|mask_mandate|youth|race|two_year|clean
Topic: 5
Words: time|think|datum|thank|source|post|recover|business|worker|benefit|social|word|student|idea|provide|statistic|close|super|parent|program|false|brain|possible|continue|symptom|third|expand|jakeshieldsajj|share|chart|lack|leader|tonight|recession|repeat|bother|sit|ch|night|consequence|eye|significant|observe|wide|ahead|sadly|conservative|censorship|clinical|employment|senior|track|bug|protocol|pharmacist|limited|hole|national|context|antibodie|monoclonal|soul|next|think_tank|cardiovascular|scale|original|million|evolution|bottom|interview|function|black|youtube|banking|apparently|loan|enemy|bed|clarify|frontline|male|refer|surveillance|backtoschool|mid|bull|particle|prevention|distanc|campus|owner|dress|bank|commitment|channel|kingdom|ycc|cndpoli_yeg|influenza
Topic: 6
Words: case|believe|active|daily|current|situation|story|obvious|register|deaths_recovere|sharp|bullshit|dream|boostershot|promote|detect|fresh|last_hour|boy|dashboard|discharge|progressive|speed|average|stand|provincial|sake|laboratory|reuter|dangerous|quietly|image|shift|flint|rage|alert|flag|b|guideline|recovery|sample|antigen|favor|estate|graph|hhs|fuel|nationwide|area|vet|arrival|departure|australian|shortage|cope|voter|lift|surgical|labor_day|current_stat|transmitted_confirme|reported_locally|scientists_patient|laid_bare|pledge|mess|informed_qanta|xf|vermaut_share|accomplish|future_crise|fifth_wave|kong_resilience|fact_checker|june|death_toll|abandoned_thiland|countries_significant|eventually|active_tally|cent|immigration|digital_qr|without_take|behind|positivity_rate|climatechange|cz|google|trudeau|shine|brutally|aajtak|ambulance|delhi_report|disgusting|ethanjweiss|honesty|ersatz|tls
Topic: 7
Words: covid|people|risk|need|sky_moon|bad|care|mangubat_support|school|social_distance|planet_global|canadian|facebmask|attack|treat|press|dead|virginia_free|saved_richmond|dose|longcovidkid|question|important|serve|helpful|potus|nation|sentence|season|moment|lock|affect|patent|radical|scientists_patient|rest|ventilation|successfully|corona|vaccin|recent|calculation|uncertainty|circuit|china_battle|districts_locke|overturn|nationwide_injunction|washing|progress|weak|discover|peter_mccullough|weak_soap|empire|issues_emergency|liver|incorrect|competing_value|political|fac|kids_head|conspiracy_theorie|impending_wave|clown|wash_yo|finding|relax|assess|regulator|wife|inject|eight_expert|informed_qanta|asymptomatic|tie|abandoned_thiland|countries_significant|attendee|chance|hoax|digital_qr|autumn|pr|without_take|ticket|traffic|meetjess|progression|evusheld|publicly|script|discount|aussie|survival|tran|justice|announcement|smear|location_scanner
Topic: 8
Words: test|use|away|service|fight|price|summer|travel|pass|excess|free|event|effect|competition|minute|advice|group|crazy|control|vote|sad|especially|rapid|girl|compare|head|online|duty|totally|sound|primary|drop|math|award|majority|cancel|democracy|reading|pop|budget|hate|hire|picture|preventable|guy|key_worker|nightmare|marketing|apologize|spanish|accountability|ontario|los_angele|chaos|contract|tomorrow|suppress|focus|dance|apply|review|adjust|activist|participate|regime|popular|skill|kind|kit|grateful|unemployment|workplace|yea|desperate|favorite|athlete|comprehension|user|qualitative|enrich|underscore|wipe|usp|production|contrary|cheap|room|voice|network|informed_qanta|unable|routinely|attempt|immunology|meta_analysis|relevant|alarm|presentation|governance|chat
Topic: 9
Words: go|thing|right|response|accountable|remember|start|rep_marjorie|taylor_greene|mean|seem|official|hear|community|wrong|city|buy|likely|th|transmission|old|least|early|forget|large|protect|lot|ago|run|probably|send|disinformation|instead|leave|allow|other|person|wonder|tax|future|rally|put|fire|stay_home|harm|member|stay|fun|quite|cou|beer|side|whatgive|crime|headline|order|choose|notice|airborne|together|color|citizen|deadly|charge|couple|wave|stick|perhaps|indoor|gaslighte|rather|acquire|realize|violence|model|wedding|direct|combination|victim|threat|near|limit|often|design|constantly|officer|father|bless|drink|none|allege|central|immediately|bill_gate|whitehouse|mi|remain|struggle|gun|party
Topic: 10
Words: report|update|rise|certificate|second_day|concern|foreign|later|contact|msm|document|maximum|chennai|johns_hopkin|positivity|cbcnew|quarantine|cannabis|grow|small|classroom|local|entry|capital|pcr|gdp|faculty|guidance|cumulative|cold|communication|intelligence|less|widely|outcome|pos|contagious|minnesota|running_reuter|manufacturing|disingenuous|activity|consideration|digital_qr|insight|analyze|without_take|pregnant_woman|necessary|lucky|tally|northern|unknown|protester|social_media|represent|rapidly|deeply|club|summary|cdt|csse|informed_qanta|village|minister|ethnicity|fa|abandoned_thiland|throug|queen|pe|division|vein|unit|redesign|approach|russian|dept|countries_significant|unleash|webpage|date|hobby|table|trace|bleed|comparison|parrot|panel_recommend|paper_card|eventually|armendarizdi|extort|accusation|google|sleepwalk|importance|devolve|mourn|exposure
Topic: 11
Words: health|infection|country|change|rate|do|protection|medium|ban|emergency|scientists_patient|plan|adult|drive|associate|power|misinformation|individual|evil|respond|completely|depression|accord|disorder|life_expectancy|rock|toadmeister|vac|deep|remind|payer|ball|warn|rare|mccullough_issue|dr_peter|simple|surpasse|transit|study_find|fix|govt|recommendation|elderly|stress|timeline|expose|myocarditis|divide|sars_cov|feed|ppl|plague|climb|cult|acknowledge|net|extra|tech|immunization|specifically|blue|poor|heavily|processing|longcovid|rent|sentiment|highlight|elite|li|commercial|occupational|imply|tool|i|mental|conference|survival|multiple|subject|faith|hat|d|paint|sweep|clinician|hospi|circulate|responsibility|routinely|percentage|income|numbers_staye|libertarian|volunteer|governor|countries_significant|immunisation|accident
Topic: 12
Words: new|death|booster|know|year|kill|love|fall|today|positive|talk|begin_rollout|bivalent|vaccination_campaign|weekly|count|expect|hour|war|survey|prior|stat|log|develop|roll|note|clinic|novel|depopulation|intensive|fox|provider|pharmacy|tested_positive|status|hoax|subvariant|mini|discussion|reformulate|predict|vacc|assessment|district|throug|baby|interested|bei|chicken|unvaccinate|approves_pfizer|piss|received_mortgage|biontech_update|bottom|milestone|germ|related|pfizer_biontech|pray|uk_medicine|caseload|odd|kick|certify|tragic|development|scientists_patient|informed_qanta|spring|authorization|host|abandoned_thiland|could_affect|establishment|saturday|countries_significant|subscriber|ensure|process|fr|thirty|evenepoel_teste|appointme|differ|wearamask|xpress|digital_qr|scenario_say|mixed|without_take|disinfect|eventually|announcement|ally|regardless|flyover|attributable|teen|cz
Topic: 13
Words: pandemic|total|find|way|state|treatment|reveal|include|approve|article|already|level|deaths_worldwide|link|eat|little|period|course|pro|handle|break|spend|natural|history|actual|epidemic|science_table|clearly|click|massive|damn|however|interesting|maga|members_disagree|different|humanity|matter|food|personal|action|parasite|specific|friend|horse_deworm|omicron_variant|wale|manufacturer|mostly|basis|cdnpoli|robbystarbuck|disaster|oil|proportion|epidemiology|nice|join|hazard|ground|properly|scam|strain|smoking|promise|covi|occur|surface|isolation_cbc|ne|ignorance|climate|hot|dynamic|wall|success|decide|doctors_continue|unvaccinated_patient|premier|playing|combat|additional|working|hospitalise|extend|informed_qanta|tour|email|equivalent|fit|iv|abandoned_thiland|wi|aim|potential|remains_unapprove|effectively|perfectly|insider
Topic: 14
Words: virus|grandmother|trump|many|well_right|first|number|back|confirm|actually|vaccinate|even|really|thousand|top|human|unvaccinated|office|horse|double|answer|newly|base|young|stiff|search|decision|agree|side_effect|nearly|thought|achievement|proud|craft|teach|admission|huge|respiratory|authorize|annual|lung|assistance|clinical_trial|demand|thi|else|credit|attend|stage|mouse|mention|previous|experimental|defeat|guess|monitor|remote|vaxxed|right_we|discuss|idk|syndrome|acute|respon|busy|routinely|legal|collective|trip|accept|belief|protective|terrorist|suppose|wharf|biker|traveler|caus|kinda|cau|flow|min|graduate|flip|form|conversation|ongoing|forgiveness|society|exactly|dog|determine|disagree|session|west_nile|arm|scientists_patient|sometimes|handy|card
Topic: 15
Words: coronavirus|give|show|high|world|air|well|hit|result|record|science|offer|video|money|serious|damage|deal|body|reason|droplet|sick|american|inflation|tired|worth|row|consent|suggest|clear|obviously|disruption|era|shocking|nazi|normal|crisis|bet|slow|amount|surge|taxpayer|sydney|honest|mitigation|turnover|ai|commit|politician|respect|simply|hundred|mutate|contain|traitor|imagine|cure|stimulus|criticize|shutdown|disinfect|cry|peanut|sleep|md|peter_mccullough|wef|quick|past_hour|spending|silly|section|prediction|decade|par|nasty|suck|aftermath|silence|sky|pressure|aid|extreme|agenda|british|fort|balance|remarkable|morbidity|toll|panic|psychological|purchase|perspective|et|steal|shape|player|da|informed_qanta|ukraine
Topic: 16
Words: government|late|due|increase|ease|rule|learn|impact|claim|restriction|always|relief|tweet|federal|careful|wake|feel|severe|biden|yet|spare|release|twittersafety|listen|excess_mortality|ready|funding|nursing|billion|chinese|correct|useful|catch|destroy|survive|final|beginning|analysis|pump|public|highly|defense|next_week|dude|responsible|college|tune|nowplaying_live|psa_second|tax_dollar|hell|idiot|bioweapon|diagnosis|organ|stroke|democratic|enable|suspend|investment|school_closure|hashtag|debt|indian|economist|prepare|attendance|lesson|pursue|company|though|profit|delivery|seat|department|daily_thank|border|wastewater|organization|globe|condemn|rec|please|fragment|slam|empower|english|bac|salary|employ|finally|te|deliberately|informed_qanta|eventually|delete|weather|army|abandoned_thiland|financial
Topic: 17
Words: say|worry|expert|far|figure|policy|become|twitter|bring|speak|safety|point|cbc|anti|one|fear|province|animal|fatality|inform|recent_gdp|modi_mentione|rational|yo|build|mild|step|red|definitely|sum|twice|learning|celebration|laugh|briefing|funny|anxiety|hardly|index|rid|mine|med|strike|peace|fro|outgoing|former|security|bro|scrap|quackery|half|standard|supporter|affirm|lady|weird|digital|exceed|map|ignore|dem|poetry|dozen|earth|summarize|piece|implication|basically|manipulate|mitigate|housing|telemedicine|rd|glad|uncertain|coffee|disgrace|defend|conspiracy_theorist|shelf|profession|empty|secondary|regulatory|artist|pox|week_amid|forever|aka|metaphor|fly|theft|inflammatory|directly|disrupt_learne|wood|closely|informed_qanta|debut
Topic: 18
Words: get|vaccination|trump_maga|adverse_event|spread|sorry|prevent|wait|admit|immunity|literally|hospitalize|propaganda|real|toddlers_babie|term|population|conspiracy|fault|list|covidisnotover|paper|nonsense|decline|experiment|visit|explain|detail|following_mrna|mrna|shots_available|effectiveness|line|walk|vulnerable|weekend|severe_illness|pay_attention|appreciate|attention|agent|prayer|delay|threaten|thinking|data|assume|mass|blow|choice|urge|theorist|globally|smoke|indicate|street|pm|zoster_virus|persistent_varicella|follower|ship|awesome|speech|severity|deserve|statement|easy|type|randomized_trial|expensive|com|eligible|draconian|await|gene|vaxe|immune|strategy|coronaviruse|pregnancy|altogether|routinely|digital_qr|site|informed_qanta|stayathome|without_take|son|pathetic|differ|abandoned_thiland|household|series|undergo|revoke|quickly|misinfo|leadership|hobby|conclusion
Topic: 19
Words: come|lead|hospital|call|try|maybe|ivermectin|folk|disease|regular|fuck|information|woman|market|wish|elect|mortality_rate|curb|anymore|education|seek|confuse|incidence|score|opponent|illness|block|capacity|dollar|pack|lawyer|failure|light|author|bunch|kidney|retire|blame|industry|culture|bitch|community_transmission|center|store|advocate|compensation|outpatient|negative|witch|suggestion|challenge|foxnew|loom|conspiracy_theory|snap|infectious|protest|integrity|adoption|inspire|currently|ill_define|cancel_doctor|misinformation_near|phase|camp|aware|feature|stock|professional|compromise|leak|sack|legionnaire|sport|ass|informed|reutersfact|glo|beautiful|police|enter|dweller|technology|director|cash|major|election|abo|president|influence|crash|grab|flood|warm|resign|capitalist|informed_qanta|accusation|depend

In [ ]:
from gensim.parsing.preprocessing import preprocess_string, strip_punctuation, strip_numeric

lda_topics = lda_model.show_topics(num_topics=20, num_words=50)

topics = []
filters = [lambda x: x.lower(), strip_punctuation, strip_numeric]

for topic in lda_topics:
    print(topic)
    topics.append(preprocess_string(topic[1], filters))

print(topics)

(0, '0.067*"die" + 0.051*"take" + 0.040*"want" + 0.037*"mask" + 0.026*"global" + 0.025*"cause" + 0.024*"let" + 0.017*"comment" + 0.016*"issue" + 0.013*"measure" + 0.013*"avoid" + 0.012*"thread" + 0.012*"app" + 0.012*"loss" + 0.009*"stupid" + 0.008*"reinstate" + 0.008*"hide" + 0.008*"proof" + 0.008*"mind" + 0.007*"past" + 0.007*"hurt" + 0.007*"wear" + 0.007*"arrest" + 0.007*"like" + 0.007*"physically" + 0.006*"experience" + 0.006*"brother" + 0.006*"deliver" + 0.006*"restaurant" + 0.005*"teacher" + 0.005*"economic" + 0.005*"growth" + 0.005*"pand" + 0.005*"whole" + 0.005*"page" + 0.005*"campaign" + 0.005*"sudden" + 0.005*"star" + 0.005*"message" + 0.005*"region" + 0.004*"blood" + 0.004*"scare" + 0.004*"ad" + 0.004*"reflect" + 0.004*"slip" + 0.004*"murder" + 0.004*"appropriate" + 0.004*"shut" + 0.004*"panel" + 0.004*"seriously"')
(1, '0.055*"amp" + 0.046*"still" + 0.035*"good" + 0.029*"child" + 0.026*"week" + 0.023*"month" + 0.022*"available" + 0.021*"help" + 0.020*"connect" + 0.017*"repmtg" + 0.017*"upon_time" + 0.016*"safe" + 0.015*"effective" + 0.014*"reduction" + 0.014*"prove" + 0.013*"biden_ukriane" + 0.012*"receive" + 0.012*"doctor" + 0.011*"family" + 0.011*"serena_trump" + 0.011*"ukriane" + 0.011*"maga_biden" + 0.010*"turn" + 0.010*"check" + 0.009*"booster_shot" + 0.009*"boost" + 0.009*"bedtime_story" + 0.009*"filter" + 0.008*"advise" + 0.008*"door" + 0.008*"flu" + 0.008*"pretty" + 0.008*"medicine" + 0.008*"criminal" + 0.007*"able" + 0.007*"practice" + 0.007*"legislation" + 0.007*"second" + 0.007*"bill" + 0.006*"united_state" + 0.006*"gift" + 0.005*"vacation" + 0.005*"view" + 0.005*"educate" + 0.005*"cough" + 0.005*"book" + 0.004*"budget_time" + 0.004*"taxis" + 0.004*"act" + 0.004*"touch"')
(2, '0.068*"work" + 0.056*"make" + 0.045*"stop" + 0.028*"read" + 0.027*"last" + 0.024*"keep" + 0.023*"hard" + 0.021*"testing" + 0.021*"consider" + 0.015*"enough" + 0.014*"shit" + 0.014*"sure" + 0.013*"part" + 0.013*"test_positive" + 0.011*"miss" + 0.011*"hand" + 0.010*"carry" + 0.010*"understand" + 0.009*"wearing_mask" + 0.008*"refuse" + 0.008*"evidence" + 0.008*"physical" + 0.008*"yesterday" + 0.008*"hope" + 0.008*"key" + 0.008*"team" + 0.007*"surprise" + 0.007*"staff" + 0.007*"quality" + 0.007*"every_day" + 0.006*"move" + 0.006*"dumb" + 0.006*"triple" + 0.006*"worldwide" + 0.006*"sector" + 0.006*"walgreen" + 0.005*"schedule" + 0.005*"suggests_canadian" + 0.005*"lab" + 0.005*"sh" + 0.005*"location" + 0.005*"sense" + 0.005*"match" + 0.005*"pharmaceutical" + 0.005*"entire" + 0.004*"basic" + 0.004*"revenue" + 0.004*"energy" + 0.004*"barely" + 0.004*"fucking"')
(3, '0.179*"vaccine" + 0.038*"patient" + 0.034*"long" + 0.033*"news" + 0.024*"infect" + 0.019*"omicron" + 0.018*"resident" + 0.017*"warning" + 0.013*"stimulus_check" + 0.013*"isolation" + 0.013*"co" + 0.012*"face" + 0.012*"administer" + 0.011*"estimate" + 0.011*"recently" + 0.011*"monkeypox" + 0.011*"remove" + 0.011*"trend" + 0.010*"pfizer" + 0.009*"name" + 0.009*"force" + 0.009*"reality" + 0.008*"county" + 0.008*"reach" + 0.008*"fake" + 0.007*"own" + 0.007*"write" + 0.007*"true" + 0.006*"hold" + 0.006*"require" + 0.006*"dip" + 0.006*"self" + 0.005*"fair" + 0.005*"cov" + 0.005*"dropping" + 0.005*"employee" + 0.005*"cut" + 0.004*"issues_emergency" + 0.004*"military" + 0.004*"mislead" + 0.004*"bit" + 0.004*"medication" + 0.004*"essential" + 0.004*"irs_admit" + 0.004*"inmates_receive" + 0.004*"covidisairborne" + 0.004*"cdc_data" + 0.003*"retweet" + 0.003*"effectiveness_plunge" + 0.003*"pcr_t"')
(4, '0.051*"study" + 0.042*"day" + 0.034*"lie" + 0.029*"see" + 0.020*"life" + 0.020*"never" + 0.018*"lose" + 0.017*"follow" + 0.016*"home" + 0.015*"look" + 0.015*"live" + 0.014*"job" + 0.014*"pay" + 0.014*"tell" + 0.013*"reduce" + 0.013*"also" + 0.013*"kid" + 0.011*"problem" + 0.011*"medical" + 0.010*"research" + 0.010*"low" + 0.010*"happen" + 0.010*"ever" + 0.009*"ask" + 0.008*"peer_reviewe" + 0.008*"outbreak" + 0.008*"great" + 0.008*"fact" + 0.008*"much" + 0.007*"almost" + 0.007*"scientist" + 0.007*"end" + 0.007*"set" + 0.007*"begin" + 0.007*"watch" + 0.007*"shot" + 0.007*"account" + 0.007*"target" + 0.007*"man" + 0.007*"lockdown" + 0.007*"fail" + 0.006*"full" + 0.006*"open" + 0.006*"recommend" + 0.006*"variant" + 0.006*"economy" + 0.006*"age" + 0.006*"mandate" + 0.006*"create" + 0.005*"sign"')
(5, '0.066*"time" + 0.035*"think" + 0.032*"datum" + 0.027*"thank" + 0.024*"source" + 0.021*"post" + 0.018*"recover" + 0.016*"business" + 0.016*"worker" + 0.015*"benefit" + 0.015*"social" + 0.015*"word" + 0.014*"student" + 0.014*"idea" + 0.013*"provide" + 0.013*"statistic" + 0.012*"close" + 0.011*"super" + 0.011*"parent" + 0.010*"program" + 0.010*"false" + 0.010*"brain" + 0.010*"possible" + 0.009*"continue" + 0.009*"symptom" + 0.008*"third" + 0.008*"expand" + 0.008*"jakeshieldsajj" + 0.008*"share" + 0.007*"chart" + 0.007*"lack" + 0.007*"leader" + 0.006*"tonight" + 0.006*"recession" + 0.006*"repeat" + 0.006*"bother" + 0.005*"sit" + 0.005*"ch" + 0.004*"night" + 0.004*"consequence" + 0.004*"eye" + 0.004*"significant" + 0.004*"observe" + 0.004*"wide" + 0.004*"ahead" + 0.004*"sadly" + 0.004*"conservative" + 0.004*"censorship" + 0.004*"clinical" + 0.004*"employment"')
(6, '0.283*"case" + 0.033*"believe" + 0.029*"active" + 0.023*"daily" + 0.018*"current" + 0.016*"situation" + 0.016*"story" + 0.015*"obvious" + 0.012*"register" + 0.012*"deaths_recovere" + 0.011*"sharp" + 0.011*"bullshit" + 0.010*"dream" + 0.008*"boostershot" + 0.008*"promote" + 0.008*"detect" + 0.008*"fresh" + 0.007*"last_hour" + 0.007*"boy" + 0.006*"dashboard" + 0.006*"discharge" + 0.006*"progressive" + 0.006*"speed" + 0.005*"average" + 0.005*"stand" + 0.005*"provincial" + 0.005*"sake" + 0.005*"laboratory" + 0.004*"reuter" + 0.004*"dangerous" + 0.004*"quietly" + 0.004*"image" + 0.004*"shift" + 0.004*"flint" + 0.004*"rage" + 0.004*"alert" + 0.003*"flag" + 0.003*"b" + 0.003*"guideline" + 0.003*"recovery" + 0.003*"sample" + 0.003*"antigen" + 0.003*"favor" + 0.003*"estate" + 0.003*"graph" + 0.002*"hhs" + 0.002*"fuel" + 0.002*"nationwide" + 0.002*"area" + 0.002*"vet"')
(7, '0.536*"covid" + 0.079*"people" + 0.022*"risk" + 0.018*"need" + 0.015*"sky_moon" + 0.013*"bad" + 0.011*"care" + 0.011*"mangubat_support" + 0.011*"school" + 0.010*"social_distance" + 0.006*"planet_global" + 0.006*"canadian" + 0.006*"facebmask" + 0.005*"attack" + 0.005*"treat" + 0.005*"press" + 0.004*"dead" + 0.004*"virginia_free" + 0.004*"saved_richmond" + 0.004*"dose" + 0.004*"longcovidkid" + 0.004*"question" + 0.004*"important" + 0.003*"serve" + 0.003*"helpful" + 0.003*"potus" + 0.003*"nation" + 0.002*"sentence" + 0.002*"season" + 0.002*"moment" + 0.002*"lock" + 0.002*"affect" + 0.002*"patent" + 0.002*"radical" + 0.002*"scientists_patient" + 0.002*"rest" + 0.002*"ventilation" + 0.002*"successfully" + 0.002*"corona" + 0.001*"vaccin" + 0.001*"recent" + 0.001*"calculation" + 0.001*"uncertainty" + 0.001*"circuit" + 0.001*"china_battle" + 0.001*"districts_locke" + 0.001*"overturn" + 0.001*"nationwide_injunction" + 0.001*"washing" + 0.001*"progress"')
(8, '0.067*"test" + 0.029*"use" + 0.022*"away" + 0.019*"service" + 0.019*"fight" + 0.019*"price" + 0.018*"summer" + 0.015*"travel" + 0.015*"pass" + 0.015*"excess" + 0.014*"free" + 0.013*"event" + 0.013*"effect" + 0.011*"competition" + 0.010*"minute" + 0.010*"advice" + 0.010*"group" + 0.010*"crazy" + 0.010*"control" + 0.009*"vote" + 0.009*"sad" + 0.009*"especially" + 0.009*"rapid" + 0.009*"girl" + 0.009*"compare" + 0.008*"head" + 0.008*"online" + 0.007*"duty" + 0.007*"totally" + 0.007*"sound" + 0.006*"primary" + 0.005*"drop" + 0.005*"math" + 0.005*"award" + 0.005*"majority" + 0.005*"cancel" + 0.005*"democracy" + 0.005*"reading" + 0.005*"pop" + 0.005*"budget" + 0.004*"hate" + 0.004*"hire" + 0.004*"picture" + 0.004*"preventable" + 0.004*"guy" + 0.004*"key_worker" + 0.004*"nightmare" + 0.004*"marketing" + 0.004*"apologize" + 0.004*"spanish"')
(9, '0.101*"go" + 0.033*"thing" + 0.026*"right" + 0.021*"response" + 0.021*"accountable" + 0.021*"remember" + 0.020*"start" + 0.019*"rep_marjorie" + 0.019*"taylor_greene" + 0.018*"mean" + 0.017*"seem" + 0.017*"official" + 0.015*"hear" + 0.015*"community" + 0.013*"wrong" + 0.012*"city" + 0.011*"buy" + 0.011*"likely" + 0.011*"th" + 0.010*"transmission" + 0.010*"old" + 0.009*"least" + 0.009*"early" + 0.009*"forget" + 0.009*"large" + 0.009*"protect" + 0.009*"lot" + 0.009*"ago" + 0.008*"run" + 0.008*"probably" + 0.008*"send" + 0.008*"disinformation" + 0.007*"instead" + 0.007*"leave" + 0.007*"allow" + 0.007*"other" + 0.007*"person" + 0.006*"wonder" + 0.006*"tax" + 0.006*"future" + 0.006*"rally" + 0.006*"put" + 0.005*"fire" + 0.005*"stay_home" + 0.005*"harm" + 0.005*"member" + 0.005*"stay" + 0.005*"fun" + 0.004*"quite" + 0.004*"cou"')
(10, '0.183*"report" + 0.075*"update" + 0.033*"rise" + 0.032*"certificate" + 0.016*"second_day" + 0.015*"concern" + 0.014*"foreign" + 0.011*"later" + 0.011*"contact" + 0.011*"msm" + 0.010*"document" + 0.009*"maximum" + 0.009*"chennai" + 0.008*"johns_hopkin" + 0.007*"positivity" + 0.007*"cbcnew" + 0.007*"quarantine" + 0.006*"cannabis" + 0.006*"grow" + 0.006*"small" + 0.006*"classroom" + 0.005*"local" + 0.005*"entry" + 0.005*"capital" + 0.004*"pcr" + 0.004*"gdp" + 0.004*"faculty" + 0.004*"guidance" + 0.004*"cumulative" + 0.004*"cold" + 0.004*"communication" + 0.004*"intelligence" + 0.003*"less" + 0.003*"widely" + 0.003*"outcome" + 0.003*"pos" + 0.003*"contagious" + 0.003*"minnesota" + 0.003*"running_reuter" + 0.003*"manufacturing" + 0.003*"disingenuous" + 0.003*"activity" + 0.003*"consideration" + 0.003*"digital_qr" + 0.002*"insight" + 0.002*"analyze" + 0.002*"without_take" + 0.002*"pregnant_woman" + 0.002*"necessary" + 0.002*"lucky"')
(11, '0.057*"health" + 0.054*"infection" + 0.053*"country" + 0.034*"change" + 0.031*"rate" + 0.025*"do" + 0.024*"protection" + 0.021*"medium" + 0.018*"ban" + 0.018*"emergency" + 0.016*"scientists_patient" + 0.016*"plan" + 0.013*"adult" + 0.013*"drive" + 0.011*"associate" + 0.010*"power" + 0.010*"misinformation" + 0.009*"individual" + 0.009*"evil" + 0.009*"respond" + 0.009*"completely" + 0.008*"depression" + 0.008*"accord" + 0.008*"disorder" + 0.008*"life_expectancy" + 0.007*"rock" + 0.007*"toadmeister" + 0.007*"vac" + 0.006*"deep" + 0.006*"remind" + 0.006*"payer" + 0.006*"ball" + 0.006*"warn" + 0.005*"rare" + 0.005*"mccullough_issue" + 0.005*"dr_peter" + 0.005*"simple" + 0.005*"surpasse" + 0.005*"transit" + 0.005*"study_find" + 0.005*"fix" + 0.005*"govt" + 0.004*"recommendation" + 0.004*"elderly" + 0.004*"stress" + 0.004*"timeline" + 0.004*"expose" + 0.004*"myocarditis" + 0.004*"divide" + 0.003*"sars_cov"')
(12, '0.157*"new" + 0.126*"death" + 0.073*"booster" + 0.063*"know" + 0.041*"year" + 0.029*"kill" + 0.026*"love" + 0.022*"fall" + 0.021*"today" + 0.020*"positive" + 0.012*"talk" + 0.011*"begin_rollout" + 0.010*"bivalent" + 0.010*"vaccination_campaign" + 0.010*"weekly" + 0.009*"count" + 0.008*"expect" + 0.007*"hour" + 0.006*"war" + 0.004*"survey" + 0.004*"prior" + 0.004*"stat" + 0.004*"log" + 0.004*"develop" + 0.004*"roll" + 0.004*"note" + 0.003*"clinic" + 0.003*"novel" + 0.003*"depopulation" + 0.003*"intensive" + 0.003*"fox" + 0.003*"provider" + 0.003*"pharmacy" + 0.003*"tested_positive" + 0.002*"status" + 0.002*"hoax" + 0.002*"subvariant" + 0.002*"mini" + 0.002*"discussion" + 0.002*"reformulate" + 0.002*"predict" + 0.002*"vacc" + 0.002*"assessment" + 0.002*"district" + 0.002*"throug" + 0.002*"baby" + 0.002*"interested" + 0.002*"bei" + 0.002*"chicken" + 0.002*"unvaccinate"')
(13, '0.101*"pandemic" + 0.054*"total" + 0.048*"find" + 0.037*"way" + 0.025*"state" + 0.021*"treatment" + 0.018*"reveal" + 0.018*"include" + 0.018*"approve" + 0.017*"article" + 0.017*"already" + 0.016*"level" + 0.012*"deaths_worldwide" + 0.012*"link" + 0.011*"eat" + 0.011*"little" + 0.011*"period" + 0.011*"course" + 0.011*"pro" + 0.010*"handle" + 0.010*"break" + 0.010*"spend" + 0.009*"natural" + 0.009*"history" + 0.008*"actual" + 0.008*"epidemic" + 0.008*"science_table" + 0.008*"clearly" + 0.007*"click" + 0.007*"massive" + 0.006*"damn" + 0.005*"however" + 0.005*"interesting" + 0.005*"maga" + 0.005*"members_disagree" + 0.005*"different" + 0.005*"humanity" + 0.005*"matter" + 0.005*"food" + 0.004*"personal" + 0.004*"action" + 0.004*"parasite" + 0.004*"specific" + 0.004*"friend" + 0.003*"horse_deworm" + 0.003*"omicron_variant" + 0.003*"wale" + 0.003*"manufacturer" + 0.003*"mostly" + 0.003*"basis"')
(14, '0.056*"virus" + 0.051*"grandmother" + 0.043*"trump" + 0.043*"many" + 0.035*"well_right" + 0.035*"first" + 0.033*"number" + 0.024*"back" + 0.020*"confirm" + 0.019*"actually" + 0.018*"vaccinate" + 0.018*"even" + 0.018*"really" + 0.017*"thousand" + 0.015*"top" + 0.014*"human" + 0.013*"unvaccinated" + 0.011*"office" + 0.011*"horse" + 0.009*"double" + 0.008*"answer" + 0.008*"newly" + 0.008*"base" + 0.007*"young" + 0.007*"stiff" + 0.007*"search" + 0.007*"decision" + 0.006*"agree" + 0.006*"side_effect" + 0.006*"nearly" + 0.006*"thought" + 0.005*"achievement" + 0.005*"proud" + 0.005*"craft" + 0.005*"teach" + 0.005*"admission" + 0.005*"huge" + 0.004*"respiratory" + 0.004*"authorize" + 0.004*"annual" + 0.004*"lung" + 0.004*"assistance" + 0.004*"clinical_trial" + 0.004*"demand" + 0.004*"thi" + 0.004*"else" + 0.004*"credit" + 0.003*"attend" + 0.003*"stage" + 0.003*"mouse"')
(15, '0.064*"coronavirus" + 0.038*"give" + 0.035*"show" + 0.031*"high" + 0.028*"world" + 0.027*"air" + 0.026*"well" + 0.023*"hit" + 0.018*"result" + 0.018*"record" + 0.018*"science" + 0.015*"offer" + 0.014*"video" + 0.013*"money" + 0.012*"serious" + 0.010*"damage" + 0.010*"deal" + 0.010*"body" + 0.010*"reason" + 0.009*"droplet" + 0.009*"sick" + 0.009*"american" + 0.008*"inflation" + 0.008*"tired" + 0.008*"worth" + 0.008*"row" + 0.007*"consent" + 0.007*"suggest" + 0.007*"clear" + 0.007*"obviously" + 0.006*"disruption" + 0.006*"era" + 0.006*"shocking" + 0.006*"nazi" + 0.006*"normal" + 0.005*"crisis" + 0.005*"bet" + 0.005*"slow" + 0.005*"amount" + 0.005*"surge" + 0.005*"taxpayer" + 0.004*"sydney" + 0.004*"honest" + 0.004*"mitigation" + 0.004*"turnover" + 0.004*"ai" + 0.004*"commit" + 0.004*"politician" + 0.004*"respect" + 0.004*"simply"')
(16, '0.043*"government" + 0.029*"late" + 0.028*"due" + 0.027*"increase" + 0.023*"ease" + 0.022*"rule" + 0.022*"learn" + 0.020*"impact" + 0.016*"claim" + 0.016*"restriction" + 0.015*"always" + 0.014*"relief" + 0.014*"tweet" + 0.013*"federal" + 0.012*"careful" + 0.012*"wake" + 0.012*"feel" + 0.012*"severe" + 0.012*"biden" + 0.012*"yet" + 0.011*"spare" + 0.011*"release" + 0.010*"twittersafety" + 0.009*"listen" + 0.009*"excess_mortality" + 0.009*"ready" + 0.008*"funding" + 0.008*"nursing" + 0.008*"billion" + 0.007*"chinese" + 0.007*"correct" + 0.007*"useful" + 0.007*"catch" + 0.007*"destroy" + 0.006*"survive" + 0.006*"final" + 0.006*"beginning" + 0.006*"analysis" + 0.006*"pump" + 0.005*"public" + 0.005*"highly" + 0.005*"defense" + 0.005*"next_week" + 0.005*"dude" + 0.005*"responsible" + 0.005*"college" + 0.004*"tune" + 0.004*"psa_second" + 0.004*"nowplaying_live" + 0.004*"tax_dollar"')
(17, '0.135*"say" + 0.024*"worry" + 0.023*"expert" + 0.023*"far" + 0.022*"figure" + 0.022*"policy" + 0.018*"become" + 0.015*"twitter" + 0.014*"bring" + 0.013*"speak" + 0.012*"safety" + 0.011*"point" + 0.011*"cbc" + 0.010*"anti" + 0.009*"one" + 0.009*"fear" + 0.009*"province" + 0.009*"animal" + 0.008*"fatality" + 0.008*"inform" + 0.008*"recent_gdp" + 0.008*"modi_mentione" + 0.007*"rational" + 0.007*"yo" + 0.007*"build" + 0.007*"mild" + 0.007*"step" + 0.007*"red" + 0.006*"definitely" + 0.006*"sum" + 0.006*"twice" + 0.005*"learning" + 0.005*"celebration" + 0.005*"laugh" + 0.005*"briefing" + 0.005*"funny" + 0.005*"anxiety" + 0.004*"hardly" + 0.004*"index" + 0.004*"rid" + 0.004*"mine" + 0.004*"med" + 0.004*"strike" + 0.004*"peace" + 0.004*"fro" + 0.004*"outgoing" + 0.004*"former" + 0.004*"security" + 0.004*"bro" + 0.004*"scrap"')
(18, '0.201*"get" + 0.050*"vaccination" + 0.023*"trump_maga" + 0.023*"adverse_event" + 0.019*"spread" + 0.017*"sorry" + 0.017*"prevent" + 0.016*"wait" + 0.013*"admit" + 0.010*"immunity" + 0.010*"literally" + 0.009*"hospitalize" + 0.009*"propaganda" + 0.009*"real" + 0.009*"toddlers_babie" + 0.009*"term" + 0.008*"population" + 0.008*"conspiracy" + 0.008*"fault" + 0.008*"list" + 0.008*"covidisnotover" + 0.008*"paper" + 0.008*"nonsense" + 0.008*"decline" + 0.007*"experiment" + 0.007*"visit" + 0.007*"explain" + 0.007*"detail" + 0.007*"following_mrna" + 0.006*"mrna" + 0.006*"shots_available" + 0.005*"effectiveness" + 0.005*"line" + 0.005*"walk" + 0.005*"vulnerable" + 0.004*"weekend" + 0.004*"severe_illness" + 0.004*"pay_attention" + 0.004*"appreciate" + 0.004*"attention" + 0.004*"agent" + 0.004*"prayer" + 0.004*"delay" + 0.004*"threaten" + 0.004*"thinking" + 0.004*"data" + 0.004*"assume" + 0.004*"mass" + 0.004*"blow" + 0.003*"choice"')
(19, '0.062*"come" + 0.057*"lead" + 0.037*"hospital" + 0.033*"call" + 0.030*"try" + 0.025*"maybe" + 0.022*"ivermectin" + 0.019*"folk" + 0.017*"disease" + 0.017*"regular" + 0.014*"fuck" + 0.013*"information" + 0.013*"woman" + 0.011*"market" + 0.011*"wish" + 0.009*"elect" + 0.009*"mortality_rate" + 0.009*"curb" + 0.009*"anymore" + 0.008*"education" + 0.008*"seek" + 0.008*"confuse" + 0.007*"incidence" + 0.007*"score" + 0.007*"opponent" + 0.007*"illness" + 0.007*"block" + 0.006*"capacity" + 0.006*"dollar" + 0.005*"pack" + 0.005*"lawyer" + 0.005*"failure" + 0.005*"light" + 0.004*"author" + 0.004*"bunch" + 0.004*"kidney" + 0.004*"retire" + 0.004*"blame" + 0.004*"industry" + 0.004*"culture" + 0.004*"bitch" + 0.004*"community_transmission" + 0.004*"center" + 0.004*"store" + 0.004*"advocate" + 0.004*"compensation" + 0.003*"outpatient" + 0.003*"negative" + 0.003*"witch" + 0.003*"suggestion"')

In [ ]:
!pip3 install pyLDAvis==2.1.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyLDAvis==2.1.2 in /usr/local/lib/python3.7/dist-packages (2.1.2)
Requirement already satisfied: numpy>=1.9.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.21.6)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (3.6.4)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.16.0)
Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.3.5)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.8.3)
Requirement already satisfied: scipy>=0.18.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.7.3)
Requirement already satisfied: joblib>=0.8.4 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.1.0)
Requirement already satisfied: jinja2>=2.7.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.11.3)
Requirement already satisfied: wheel>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.37.1)
Requirement already satisfied: funcy in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.17)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.7.2->pyLDAvis==2.1.2) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.17.0->pyLDAvis==2.1.2) (1.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from numexpr->pyLDAvis==2.1.2) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->numexpr->pyLDAvis==2.1.2) (3.0.9)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (22.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (8.14.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (0.7.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (57.4.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.4.1)

In [ ]:
# Visualize the topics
import pyLDAvis.gensim
#import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
vis

/usr/local/lib/python3.7/dist-packages/pyLDAvis/_prepare.py:232: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  head(R).drop('saliency', 1)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
7     -0.380549  0.175858       1        1  11.051640
4     -0.160650 -0.369371       2        1   9.123652
1      0.019338  0.011984       3        1   6.187178
9     -0.004251  0.002225       4        1   6.030839
12    -0.004415 -0.007563       5        1   5.808395
3      0.016069  0.012568       6        1   4.752202
13     0.026641  0.010399       7        1   4.711831
5      0.031508  0.011646       8        1   4.651936
2      0.026067  0.011668       9        1   4.565354
14     0.011558  0.003148      10        1   4.548007
0      0.031601  0.014621      11        1   4.507710
18     0.039643  0.017722      12        1   4.436415
15     0.027102  0.007369      13        1   4.404828
16     0.040638  0.013311      14        1   4.186253
8      0.053138  0.017950      15        1   3.815061
11     0.028314  0.001875      16        1   3.723855
19     0.047261  0.014252      17        1   3.570896
6      0.042889  0.014844      18        1   3.527378
17     0.052218  0.017702      19        1   3.263361
10     0.055880  0.017793      20        1   3.133208, topic_info=               Term         Freq        Total Category  logprob  loglift
2             covid  5408.000000  5408.000000  Default  30.0000  30.0000
1              case   912.000000   912.000000  Default  29.0000  29.0000
36              get   816.000000   816.000000  Default  28.0000  28.0000
3               new   836.000000   836.000000  Default  27.0000  27.0000
9           vaccine   778.000000   778.000000  Default  26.0000  26.0000
...             ...          ...          ...      ...      ...      ...
1029           cold    10.578487    11.415709  Topic20  -5.6006   3.3869
4953  communication    10.246721    11.083953  Topic20  -5.6325   3.3846
1288   intelligence    10.232953    11.070176  Topic20  -5.6338   3.3845
9174         cbcnew    18.732808    20.542843  Topic20  -5.0292   3.3709
7181        faculty    11.497258    12.483000  Topic20  -5.5173   3.3809

[641 rows x 6 columns], token_table=      Topic      Freq         Term
term
2305     16  0.984661       accord
4894      4  0.994534  accountable
84       18  0.994345       active
2455      7  0.978381       actual
1394     10  0.990024     actually
...     ...       ...          ...
69        5  0.997599         year
1456      9  0.970704    yesterday
534      14  0.974460          yet
41       19  0.968714           yo
2097     10  0.957461        young

[654 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[8, 5, 2, 10, 13, 4, 14, 6, 3, 15, 1, 19, 16, 17, 9, 12, 20, 7, 18, 11])

In [ ]:
pyLDAvis.save_html(vis, '2022_lda.html')

In [ ]:
!unzip "/content/mallet-2.0.8.zip"

In [ ]:
mallet_path = '/content/mallet-2.0.8/bin/mallet' # update this path
#ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, 
#                                             corpus=corpus, 
#                                             num_topics=20,
#                                             id2word=id2word)

ldamallet = gensim.models.wrappers.LdaMallet(mallet_path,
                                           corpus=corpus,
                                           id2word=id2word,
                                           num_topics=20,
                                           iterations=500
                                           )

/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)

In [ ]:
pprint(ldamallet.show_topics(num_topics=20,num_words=100,formatted=False))

# Compute Coherence Score
coherence_model_ldamallet = CoherenceModel(model=ldamallet, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_ldamallet = coherence_model_ldamallet.get_coherence()

print('\n Coherence Score: ', round(coherence_ldamallet, 2))

[(0,
  [('covid', 0.05407421219466716),
   ('pandemic', 0.022002610479209397),
   ('impact', 0.012120082043632295),
   ('global', 0.01006899123624837),
   ('health', 0.00857728883087824),
   ('economic', 0.008017900428864442),
   ('market', 0.007644974827521909),
   ('world', 0.007458512026850644),
   ('lockdown', 0.006712660824165579),
   ('report', 0.0063397352228230465),
   ('social', 0.0063397352228230465),
   ('crisis', 0.006153272422151781),
   ('job', 0.005966809621480515),
   ('government', 0.005593884020137983),
   ('due', 0.005407421219466716),
   ('industry', 0.005407421219466716),
   ('state', 0.005407421219466716),
   ('analysis', 0.00522095841879545),
   ('lose', 0.00522095841879545),
   ('end', 0.004661570016781652),
   ('share', 0.004661570016781652),
   ('wave', 0.004661570016781652),
   ('country', 0.004475107216110386),
   ('support', 0.004475107216110386),
   ('low', 0.004475107216110386),
   ('amp', 0.00428864441543912),
   ('growth', 0.004102181614767854),
   ('expert', 0.003915718814096587),
   ('restriction', 0.003915718814096587),
   ('result', 0.003915718814096587),
   ('business', 0.003915718814096587),
   ('travel', 0.003915718814096587),
   ('coronavirus', 0.003915718814096587),
   ('war', 0.003915718814096587),
   ('loss', 0.003729256013425322),
   ('energy', 0.003729256013425322),
   ('effect', 0.003729256013425322),
   ('create', 0.003729256013425322),
   ('economy', 0.003729256013425322),
   ('mention', 0.0035427932127540555),
   ('view', 0.0035427932127540555),
   ('lead', 0.0035427932127540555),
   ('hire', 0.0035427932127540555),
   ('pay', 0.0035427932127540555),
   ('spread', 0.0033563304120827896),
   ('public', 0.0033563304120827896),
   ('role', 0.0033563304120827896),
   ('news', 0.0033563304120827896),
   ('service', 0.0031698676114115232),
   ('system', 0.0031698676114115232),
   ('trump', 0.0031698676114115232),
   ('big', 0.0031698676114115232),
   ('shut', 0.0029834048107402573),
   ('debt', 0.0029834048107402573),
   ('break', 0.0029834048107402573),
   ('research', 0.0029834048107402573),
   ('company', 0.0029834048107402573),
   ('trend', 0.0029834048107402573),
   ('response', 0.0029834048107402573),
   ('boost', 0.0029834048107402573),
   ('international', 0.0027969420100689914),
   ('class', 0.0027969420100689914),
   ('experience', 0.0027969420100689914),
   ('stress', 0.0027969420100689914),
   ('vaccination', 0.0027969420100689914),
   ('real', 0.0027969420100689914),
   ('give', 0.002610479209397725),
   ('freedom', 0.002610479209397725),
   ('close', 0.002610479209397725),
   ('relate', 0.002610479209397725),
   ('vaccine', 0.002610479209397725),
   ('climate', 0.002610479209397725),
   ('policy', 0.002610479209397725),
   ('level', 0.002610479209397725),
   ('science', 0.002424016408726459),
   ('mandate', 0.002424016408726459),
   ('apply', 0.002424016408726459),
   ('care', 0.002424016408726459),
   ('stock', 0.002424016408726459),
   ('activity', 0.002424016408726459),
   ('people', 0.002424016408726459),
   ('slow', 0.002237553608055193),
   ('work', 0.002237553608055193),
   ('worker', 0.002237553608055193),
   ('education', 0.002237553608055193),
   ('recession', 0.002237553608055193),
   ('stand', 0.002237553608055193),
   ('price', 0.002237553608055193),
   ('click', 0.002237553608055193),
   ('income', 0.002237553608055193),
   ('show', 0.002237553608055193),
   ('fight', 0.002237553608055193),
   ('step', 0.002237553608055193),
   ('key', 0.002237553608055193),
   ('project', 0.002237553608055193),
   ('team', 0.002237553608055193),
   ('cost', 0.002051090807383927),
   ('struggle', 0.002051090807383927),
   ('official', 0.002051090807383927),
   ('community', 0.002051090807383927)]),
 (1,
  [('covid', 0.08583860759493671),
   ('vaccine', 0.014372362869198312),
   ('year', 0.013317510548523207),
   ('vaccination', 0.012921940928270042),
   ('work', 0.012394514767932489),
   ('testing', 0.009229957805907173),
   ('child', 0.00870253164556962),
   ('health', 0.008438818565400843),
   ('pandemic', 0.007779535864978903),
   ('today', 0.007779535864978903),
   ('people', 0.007779535864978903),
   ('month', 0.007647679324894515),
   ('community', 0.007383966244725738),
   ('week', 0.006724683544303798),
   ('amp', 0.006329113924050633),
   ('time', 0.006329113924050633),
   ('back', 0.006065400843881856),
   ('early', 0.006065400843881856),
   ('vaccinate', 0.005933544303797469),
   ('follow', 0.0058016877637130804),
   ('long', 0.005669831223628692),
   ('stay', 0.005537974683544304),
   ('age', 0.005274261603375527),
   ('risk', 0.005142405063291139),
   ('show', 0.0050105485232067514),
   ('home', 0.004746835443037975),
   ('grandmother', 0.004746835443037975),
   ('datum', 0.004746835443037975),
   ('book', 0.0046149789029535865),
   ('find', 0.004483122362869198),
   ('lockdown', 0.004483122362869198),
   ('school', 0.00435126582278481),
   ('country', 0.00435126582278481),
   ('good', 0.004219409282700422),
   ('thing', 0.004087552742616034),
   ('family', 0.003955696202531646),
   ('business', 0.0038238396624472575),
   ('learn', 0.0038238396624472575),
   ('symptom', 0.0038238396624472575),
   ('support', 0.003691983122362869),
   ('part', 0.003691983122362869),
   ('patient', 0.003560126582278481),
   ('day', 0.003560126582278481),
   ('hear', 0.003560126582278481),
   ('late', 0.003560126582278481),
   ('face', 0.003560126582278481),
   ('rule', 0.003560126582278481),
   ('county', 0.003428270042194093),
   ('discuss', 0.003428270042194093),
   ('virus', 0.003428270042194093),
   ('world', 0.003428270042194093),
   ('list', 0.0032964135021097047),
   ('talk', 0.0032964135021097047),
   ('ago', 0.0032964135021097047),
   ('well_right', 0.0031645569620253164),
   ('safe', 0.0031645569620253164),
   ('change', 0.0031645569620253164),
   ('technology', 0.0031645569620253164),
   ('mask', 0.0031645569620253164),
   ('protect', 0.003032700421940928),
   ('team', 0.003032700421940928),
   ('challenge', 0.003032700421940928),
   ('man', 0.003032700421940928),
   ('write', 0.0029008438818565402),
   ('site', 0.0029008438818565402),
   ('play', 0.0029008438818565402),
   ('drive', 0.0029008438818565402),
   ('video', 0.0029008438818565402),
   ('open', 0.002768987341772152),
   ('spread', 0.002768987341772152),
   ('coronavirus', 0.002768987341772152),
   ('crisis', 0.002768987341772152),
   ('company', 0.002768987341772152),
   ('care', 0.002768987341772152),
   ('require', 0.002768987341772152),
   ('continue', 0.0026371308016877636),
   ('partner', 0.0026371308016877636),
   ('release', 0.0026371308016877636),
   ('woman', 0.0025052742616033757),
   ('offer', 0.0025052742616033757),
   ('share', 0.0025052742616033757),
   ('explain', 0.0025052742616033757),
   ('clinic', 0.0023734177215189874),
   ('begin', 0.0023734177215189874),
   ('citizen', 0.0023734177215189874),
   ('page', 0.0023734177215189874),
   ('put', 0.0023734177215189874),
   ('happen', 0.0023734177215189874),
   ('leader', 0.0023734177215189874),
   ('medical', 0.002241561181434599),
   ('link', 0.002241561181434599),
   ('service', 0.002241561181434599),
   ('end', 0.002241561181434599),
   ('story', 0.002241561181434599),
   ('bad', 0.002241561181434599),
   ('employee', 0.002109704641350211),
   ('safety', 0.002109704641350211),
   ('dose', 0.002109704641350211),
   ('fight', 0.002109704641350211),
   ('million', 0.002109704641350211)]),
 (2,
  [('covid', 0.04499540863177227),
   ('year', 0.0371900826446281),
   ('pandemic', 0.024793388429752067),
   ('result', 0.02157943067033976),
   ('find', 0.02066115702479339),
   ('door', 0.016069788797061526),
   ('test_positive', 0.015610651974288337),
   ('science_table', 0.012855831037649219),
   ('live', 0.012396694214876033),
   ('handle', 0.012396694214876033),
   ('careful', 0.011019283746556474),
   ('remember', 0.011019283746556474),
   ('death', 0.010560146923783287),
   ('due', 0.009641873278236915),
   ('show', 0.009182736455463728),
   ('witness', 0.009182736455463728),
   ('members_disagree', 0.008264462809917356),
   ('open', 0.0073461891643709825),
   ('food', 0.006887052341597796),
   ('hiatus_due', 0.006887052341597796),
   ('evidence', 0.006887052341597796),
   ('half', 0.006887052341597796),
   ('knock', 0.006427915518824609),
   ('lower_incidence', 0.006427915518824609),
   ('return', 0.006427915518824609),
   ('news', 0.005509641873278237),
   ('region', 0.005509641873278237),
   ('response', 0.005509641873278237),
   ('report', 0.005509641873278237),
   ('treatment', 0.005050505050505051),
   ('mortgage', 0.005050505050505051),
   ('rate', 0.005050505050505051),
   ('view', 0.005050505050505051),
   ('model', 0.005050505050505051),
   ('isolation', 0.005050505050505051),
   ('door_ministry', 0.005050505050505051),
   ('restart', 0.005050505050505051),
   ('received_mortgage', 0.004591368227731864),
   ('baby', 0.004591368227731864),
   ('medical', 0.004591368227731864),
   ('user', 0.004132231404958678),
   ('county', 0.004132231404958678),
   ('practice', 0.004132231404958678),
   ('deal', 0.004132231404958678),
   ('concern', 0.004132231404958678),
   ('month', 0.004132231404958678),
   ('family', 0.004132231404958678),
   ('coronavirus', 0.004132231404958678),
   ('describe', 0.004132231404958678),
   ('chat', 0.004132231404958678),
   ('bat', 0.0036730945821854912),
   ('dental', 0.0036730945821854912),
   ('resume', 0.0036730945821854912),
   ('tonight', 0.0036730945821854912),
   ('claim', 0.0036730945821854912),
   ('isolation_cbc', 0.0032139577594123047),
   ('search', 0.0032139577594123047),
   ('ne', 0.0032139577594123047),
   ('conclusion', 0.0032139577594123047),
   ('good', 0.0032139577594123047),
   ('hospital', 0.0032139577594123047),
   ('health', 0.0032139577594123047),
   ('clear', 0.0032139577594123047),
   ('care_delay', 0.0032139577594123047),
   ('mortgage_rate', 0.0032139577594123047),
   ('kill', 0.0032139577594123047),
   ('fight', 0.0032139577594123047),
   ('eye', 0.0032139577594123047),
   ('kitchen', 0.0027548209366391185),
   ('decision', 0.0027548209366391185),
   ('thing', 0.0027548209366391185),
   ('check', 0.0027548209366391185),
   ('adverse_event', 0.0027548209366391185),
   ('laboratory', 0.0027548209366391185),
   ('medical_admission', 0.0027548209366391185),
   ('suspend', 0.0027548209366391185),
   ('advise', 0.0027548209366391185),
   ('global', 0.0027548209366391185),
   ('online', 0.0027548209366391185),
   ('world', 0.0027548209366391185),
   ('stream', 0.0027548209366391185),
   ('object', 0.0027548209366391185),
   ('maximum', 0.0027548209366391185),
   ('campaign', 0.0027548209366391185),
   ('artist', 0.0027548209366391185),
   ('large_reduction', 0.0027548209366391185),
   ('tested_positive', 0.0027548209366391185),
   ('super', 0.002295684113865932),
   ('disabled', 0.002295684113865932),
   ('promise', 0.002295684113865932),
   ('german_scientist', 0.002295684113865932),
   ('japanese', 0.002295684113865932),
   ('reject', 0.002295684113865932),
   ('red', 0.002295684113865932),
   ('wedding', 0.002295684113865932),
   ('part', 0.002295684113865932),
   ('long', 0.002295684113865932),
   ('reason', 0.002295684113865932),
   ('person', 0.002295684113865932),
   ('closure', 0.002295684113865932)]),
 (3,
  [('case', 0.13720573896085805),
   ('covid', 0.12021172865301574),
   ('death', 0.059757626410363564),
   ('report', 0.050006964758322885),
   ('update', 0.023540883131355342),
   ('coronavirus', 0.01713330547430004),
   ('confirm', 0.014347402145145563),
   ('infection', 0.013929516645772392),
   ('total', 0.013650926312856944),
   ('daily', 0.012954450480568324),
   ('day', 0.0128151553141106),
   ('record', 0.01239726981473743),
   ('number', 0.011143613316617913),
   ('figure', 0.010725727817244742),
   ('policy', 0.010586432650787018),
   ('active', 0.01030784231787157),
   ('second_day', 0.009889956818498398),
   ('recovery', 0.009750661652040674),
   ('last_hour', 0.009332776152667503),
   ('log', 0.008497005153921159),
   ('modi_mentione', 0.00780052932163254),
   ('recent_gdp', 0.00780052932163254),
   ('run', 0.007382643822259368),
   ('rise', 0.007382643822259368),
   ('news', 0.007382643822259368),
   ('week', 0.006686167989970748),
   ('positive', 0.005989692157682128),
   ('today', 0.0058503969912244045),
   ('test', 0.005571806658308956),
   ('stimulus_check', 0.005571806658308956),
   ('rate', 0.005571806658308956),
   ('high', 0.005153921158935785),
   ('country', 0.005153921158935785),
   ('people', 0.005014625992478061),
   ('decline', 0.004736035659562613),
   ('hour', 0.00459674049310489),
   ('recover', 0.004318150160189441),
   ('reports_fresh', 0.004318150160189441),
   ('late', 0.004178854993731718),
   ('virus', 0.004178854993731718),
   ('state', 0.00390026466081627),
   ('county', 0.0037609694943585457),
   ('fresh', 0.0037609694943585457),
   ('receive', 0.003621674327900822),
   ('local', 0.003482379161443098),
   ('hospital', 0.003343083994985374),
   ('statistic', 0.003343083994985374),
   ('official', 0.00320378882852765),
   ('current', 0.003064493662069926),
   ('health', 0.0029251984956122023),
   ('active_tally', 0.0029251984956122023),
   ('fatality', 0.002785903329154478),
   ('register', 0.0026466081626967545),
   ('stat', 0.0026466081626967545),
   ('positivity_rate', 0.0025073129962390303),
   ('average', 0.0025073129962390303),
   ('past_hour', 0.0025073129962390303),
   ('live', 0.0025073129962390303),
   ('time', 0.0025073129962390303),
   ('sept', 0.0023680178297813066),
   ('weekly', 0.0023680178297813066),
   ('dead', 0.0023680178297813066),
   ('patient', 0.002089427496865859),
   ('bring', 0.002089427496865859),
   ('yesterday', 0.002089427496865859),
   ('delhi_report', 0.002089427496865859),
   ('month', 0.002089427496865859),
   ('drop', 0.001950132330408135),
   ('detect', 0.001950132330408135),
   ('situation', 0.001950132330408135),
   ('increase', 0.001810837163950411),
   ('reach', 0.001810837163950411),
   ('inmates_receive', 0.001810837163950411),
   ('continue', 0.001810837163950411),
   ('world', 0.001810837163950411),
   ('relate', 0.001810837163950411),
   ('accord', 0.001810837163950411),
   ('united_state', 0.001671541997492687),
   ('estimate', 0.001671541997492687),
   ('announce', 0.001671541997492687),
   ('excess', 0.001671541997492687),
   ('additional', 0.001671541997492687),
   ('irs_admit', 0.001671541997492687),
   ('remain', 0.001671541997492687),
   ('responsible', 0.001532246831034963),
   ('wave', 0.001532246831034963),
   ('government', 0.001532246831034963),
   ('count', 0.001532246831034963),
   ('pm', 0.001532246831034963),
   ('show', 0.001532246831034963),
   ('weekend', 0.001392951664577239),
   ('rolling_average', 0.001392951664577239),
   ('trend', 0.001392951664577239),
   ('infect', 0.001392951664577239),
   ('sample', 0.001392951664577239),
   ('exceed', 0.001392951664577239),
   ('decrease', 0.001392951664577239),
   ('stand', 0.001392951664577239),
   ('read', 0.0012536564981195152),
   ('covidisnotover', 0.0012536564981195152)]),
 (4,
  [('trump_maga', 0.11662726556343578),
   ('upon_time', 0.08668242710795902),
   ('biden_ukriane', 0.08353033884948778),
   ('biden', 0.04491725768321513),
   ('budget_time', 0.036249014972419225),
   ('grandma_smoke', 0.026004728132387706),
   ('fatty_serena', 0.02442868400315209),
   ('bedtime_story', 0.02442868400315209),
   ('serenawilliam', 0.019700551615445233),
   ('serenawilliams_pga', 0.018124507486209612),
   ('develop', 0.01260835303388495),
   ('system', 0.01103230890464933),
   ('ycc', 0.01024428684003152),
   ('research', 0.01024428684003152),
   ('cndpoli_yeg', 0.01024428684003152),
   ('youth', 0.008668242710795903),
   ('phone', 0.008668242710795903),
   ('little_johnny', 0.008668242710795903),
   ('dupe', 0.007880220646178092),
   ('disease_detection', 0.0070921985815602835),
   ('early_warne', 0.0070921985815602835),
   ('save_live', 0.0070921985815602835),
   ('art', 0.0070921985815602835),
   ('drug', 0.0070921985815602835),
   ('ab_covidisnotover', 0.0070921985815602835),
   ('wwe', 0.0070921985815602835),
   ('wrong_crow', 0.006304176516942475),
   ('teen_turne', 0.006304176516942475),
   ('school_hange', 0.006304176516942475),
   ('alcohol_skippe', 0.006304176516942475),
   ('stoolpresidente', 0.006304176516942475),
   ('bb', 0.006304176516942475),
   ('win', 0.006304176516942475),
   ('serena', 0.006304176516942475),
   ('story', 0.004728132387706856),
   ('intellectual', 0.004728132387706856),
   ('trump', 0.003940110323089046),
   ('ksorb', 0.003940110323089046),
   ('livgolfinv_bedtime', 0.003940110323089046),
   ('breitbartnew', 0.003940110323089046),
   ('exist', 0.003940110323089046),
   ('precaution', 0.0031520882584712374),
   ('opioid', 0.0031520882584712374),
   ('sound', 0.0031520882584712374),
   ('property', 0.0031520882584712374),
   ('time', 0.0031520882584712374),
   ('battery', 0.0031520882584712374),
   ('thedemocrat', 0.0031520882584712374),
   ('happen', 0.0031520882584712374),
   ('analogy', 0.0031520882584712374),
   ('fury', 0.0031520882584712374),
   ('curve', 0.002364066193853428),
   ('ury', 0.002364066193853428),
   ('tmz', 0.002364066193853428),
   ('sportsnet', 0.002364066193853428),
   ('thescore', 0.002364066193853428),
   ('borisjohnson', 0.002364066193853428),
   ('explosiv', 0.002364066193853428),
   ('baldwin', 0.002364066193853428),
   ('danawhite', 0.002364066193853428),
   ('mayoisspicyy', 0.002364066193853428),
   ('decrease', 0.002364066193853428),
   ('overdose', 0.002364066193853428),
   ('randyrrquaid', 0.002364066193853428),
   ('eth', 0.002364066193853428),
   ('platform', 0.002364066193853428),
   ('race', 0.002364066193853428),
   ('register', 0.0015760441292356187),
   ('mango', 0.0015760441292356187),
   ('mutual', 0.0015760441292356187),
   ('excited', 0.0015760441292356187),
   ('anitagreenworld', 0.0015760441292356187),
   ('timrunshismouth', 0.0015760441292356187),
   ('billkristol', 0.0015760441292356187),
   ('tsn', 0.0015760441292356187),
   ('realskipbayless', 0.0015760441292356187),
   ('reign', 0.0015760441292356187),
   ('perrottet', 0.0015760441292356187),
   ('sweet', 0.0015760441292356187),
   ('relation', 0.0015760441292356187),
   ('jessekellydc', 0.0015760441292356187),
   ('leronemurphy', 0.0015760441292356187),
   ('transtweetable', 0.0015760441292356187),
   ('publish', 0.0015760441292356187),
   ('buitengebieden', 0.0015760441292356187),
   ('president', 0.0015760441292356187),
   ('sport', 0.0015760441292356187),
   ('gchahal', 0.0015760441292356187),
   ('telehealth', 0.0015760441292356187),
   ('utilizati', 0.0015760441292356187),
   ('riskgetting', 0.0015760441292356187),
   ('vast_majority', 0.0015760441292356187),
   ('quickly', 0.0015760441292356187),
   ('utilization', 0.0015760441292356187),
   ('long', 0.0015760441292356187),
   ('rugby', 0.0015760441292356187),
   ('herschelwalker', 0.0015760441292356187),
   ('underutilize', 0.0007880220646178094),
   ('ambassador', 0.0007880220646178094),
   ('mocker', 0.0007880220646178094)]),
 (5,
  [('covid', 0.07605229591836735),
   ('study', 0.0314094387755102),
   ('vaccine', 0.02024872448979592),
   ('risk', 0.016900510204081634),
   ('infection', 0.015306122448979591),
   ('patient', 0.01403061224489796),
   ('increase', 0.01211734693877551),
   ('people', 0.010841836734693877),
   ('disease', 0.010522959183673469),
   ('show', 0.009088010204081632),
   ('find', 0.00860969387755102),
   ('reduce', 0.008131377551020409),
   ('death', 0.007971938775510204),
   ('datum', 0.0078125),
   ('effect', 0.0074936224489795915),
   ('rate', 0.006536989795918368),
   ('evidence', 0.006536989795918368),
   ('severe', 0.006218112244897959),
   ('associate', 0.005899234693877551),
   ('child', 0.005739795918367347),
   ('man', 0.00510204081632653),
   ('virus', 0.004942602040816327),
   ('impact', 0.004942602040816327),
   ('country', 0.004942602040816327),
   ('base', 0.0047831632653061226),

In [ ]:
mallet_lda_model = gensim.models.wrappers.ldamallet.malletmodel2ldamodel(ldamallet)

In [ ]:
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(mallet_lda_model, corpus, id2word,sort_topics=False)

/usr/local/lib/python3.7/dist-packages/pyLDAvis/_prepare.py:232: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  head(R).drop('saliency', 1)

In [ ]:
print(vis.topic_order)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
pyLDAvis.save_html(vis, '2022_lda_mallet.html')

In [ ]:
vis

PreparedData(topic_coordinates=              x         y  topics  cluster      Freq
topic
0      0.000139  0.000605       1        1  4.957729
1     -0.000130  0.000024       2        1  5.029265
2      0.000219 -0.000093       3        1  5.006057
3     -0.000439 -0.000744       4        1  4.991864
4     -0.000019 -0.000260       5        1  5.039537
5     -0.000525 -0.000214       6        1  4.985984
6      0.000105  0.000091       7        1  4.987267
7     -0.000263  0.000002       8        1  4.981474
8     -0.000210 -0.000726       9        1  5.017666
9     -0.000185  0.000236      10        1  5.008625
10     0.000787 -0.000037      11        1  5.031838
11    -0.000198  0.000487      12        1  5.008244
12     0.000004 -0.000498      13        1  4.962519
13     0.000310  0.000047      14        1  4.996444
14     0.000317 -0.000125      15        1  5.016568
15     0.000506  0.000278      16        1  4.985773
16     0.000282  0.000312      17        1  5.026882
17     0.000497 -0.000298      18        1  5.008894
18    -0.000589  0.000361      19        1  4.961389
19    -0.000609  0.000554      20        1  4.995980, topic_info=                Term      Freq     Total Category  logprob  loglift
8437       infuriate  7.000000  7.000000  Default  30.0000  30.0000
4445         propose  7.000000  7.000000  Default  29.0000  29.0000
6906        sentinel  8.000000  8.000000  Default  28.0000  28.0000
8311   dontbeasucker  7.000000  7.000000  Default  27.0000  27.0000
4564         anxiety  8.000000  8.000000  Default  26.0000  26.0000
...              ...       ...       ...      ...      ...      ...
3479          mestre  0.507382  8.127811  Topic20  -9.1045   0.2228
6921   thanniversary  0.498317  7.896691  Topic20  -9.1225   0.2336
11696        vvriter  0.504027  8.164776  Topic20  -9.1111   0.2116
5674       traumatic  0.501536  8.099455  Topic20  -9.1161   0.2147
7437     patriotsong  0.499643  8.169589  Topic20  -9.1199   0.2023

[830 rows x 6 columns], token_table=       Topic      Freq            Term
term
874        5  0.123445         abysmal
3481      20  0.128920        academia
6024      12  0.125761  accesstooxygen
2222      11  0.127246  acetylcysteine
6891      12  0.127644             ach
...      ...       ...             ...
2291       4  0.125313           worth
8599       3  0.130389             wth
8427       7  0.129107       wwecastle
6663      12  0.129735            xqdp
10643      6  0.126304            yard

[457 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])