In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# pip install gensim
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(400)

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
df = pd.read_csv("/content/2020_Sep6_154k_hydrated_tweets.csv")

In [ ]:
df.drop(columns=['id_str',"in_reply_to_screen_name","is_retweet"], inplace=True)

In [ ]:
# Function to Clean the Tweet.

import re
def clean_tweet(tweet):
    return ' '.join(re.sub('(\\\\n)|(b\"[^0-9A-Za-z A-Za-z0-9 \t]+)|(b\'[^0-9A-Za-z]+)|(b\"[A-Za-z0-9]+)|(b\'[A-Za-z0-9]+)|(b\'#[A-Za-z0-9]+)|(b\'@[A-Za-z0-9]+)|(\\\\x[A-Za-z0-9]+)|(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|([RT])', ' ', str(tweet).lower()).split())

In [ ]:
# Call function to get Clean tweets
df["CleanTweet"] = df['text'].apply(lambda x : clean_tweet(x))
df.tail()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
153749,1,Twitter for iPad,b'@theasscat I even get fooled sometimes. It\x...,Mon Sep 07 04:03:13 +0000 2020,0,theasscat i even get fooled sometimes it becom...
153750,4,COVID-19MX,b'#ACTUALIZACI\xc3\x93N GLOBAL \xf0\x9f\x8c\x8...,Mon Sep 07 04:03:15 +0000 2020,2,actualizaci global top casos 6 460 250 4 202 5...
153751,0,erased16993361,b'#Covid19 bot \n#COVID19 last 5 days stats #U...,Mon Sep 07 04:03:06 +0000 2020,0,covid19 bot covid19 last 5 days stats uttarakh...
153752,0,SocialFlow,"b""Coronavirus: What's open, what's closed in t...",Mon Sep 07 04:03:15 +0000 2020,0,what s open what s closed in the mid hudson va...
153753,0,Twitter for iPhone,b'@KellyannePolls is a very disgusting person ...,Mon Sep 07 04:03:13 +0000 2020,0,kellyannepolls is a very disgusting person

In [ ]:
df.drop(df.index[df.CleanTweet.eq("")], inplace=True)

In [ ]:
df.head()

,favorite_count,source,text,created_at,retweet_count,CleanTweet
0,1,Twitter for Android,"b""Don't believe it. https://t.co/VFfhPArn1a""",Sat Sep 03 04:09:04 +0000 2022,0,t believe it
1,0,cmssocialservice,b'Surat records 11 new Covid-19 cases https://...,Sat Sep 03 04:06:03 +0000 2022,0,records 11 new covid 19 cases
2,38,TweetDeck,b'Hennepin County will no longer require COVID...,Sat Sep 03 04:09:00 +0000 2022,6,county will no longer require covid 19 vaccine...
3,2,Twitter Web App,"b'As of Sept 1, the capital has given over 63....",Sat Sep 03 04:08:52 +0000 2022,0,of sept 1 the capital has given over 63 2 mill...
4,1,Twitter for Android,b'@KushThrough @BlazedRTs @rtsmallstreams @Rts...,Sat Sep 03 04:15:46 +0000 2022,3,kushthrough ww nowplaying x lilroyce her ev

In [ ]:
stemmer = SnowballStemmer(language='english')
def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

def preprocess(text):
    result=[]
    for token in gensim.utils.simple_preprocess(text) :
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
            
    return result

In [ ]:
complete_text = ' '.join(df["CleanTweet"])

In [ ]:
data = df.CleanTweet.values.tolist()

In [ ]:
pprint(data[:2])

Pretty printing has been turned OFF

In [ ]:
complete_text

't believe it records 11 new covid 19 cases county will no longer require covid 19 vaccines for its employees of sept 1 the capital has given over 63 2 million doses of covid19 vaccines to over 23 6 million people kushthrough ww nowplaying x lilroyce her ev can t be good for you themixmedic nowplaying x lilroyce her evil spine feat makrazy total of 174 new cases of covid 19 were reported during the last 24 hours across the state odisha odishanews appointed by the israeli moh to investigate covid 19 vaccine side effects warned the ministry it could b covid 19 closed our campuses down the idea that every student has a computer a word processing program sta thetruthsucks12 why get poked in 2021 when covid 19 has a 98 survival rate got a bridge in brooklyn for sale yo federal government is fucking trash dubai reins in hospitality as covid 19 cases rise is hilarious you can make this up the camp counselor who tried to overturn a decisive democratic election pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri fucking idiots odisha reports 174 new cases of covid19 in the last 24 hours of which 0 18 years 13 in quarantine 102 local contacts 72 invented and cured coronavirus donald trump was very smart russia bombed the lab in ukraine that was genera not a way to handle the pandemic science table members disagree with scrapping 5 day covid 19 isolation cbc ne covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity rate 1 98 in an almighty coronavirus metaphor at stechford baths station rd 19 or swine flu know how to differentiate between the geauxt17 had been in the house coronavirus task force for decades you said that right 19 journal for friday september 2 2022 records 46 new cases of coronavirus within 24 denise dewald wuhan used an unknown coronavirus test initially does argentina have access to this friday broadcast of the five fox news greg gutfeld proclaimed that he is disinformation after a co break on august 23 the botetourt county board of supervisors approved an additional 250 000 in personal pro deblvsbabygroot really does depend on the circumstances here is the workcover qld link profesterman thanks for the daily covid19 data amp i hope your dog maintains the waistline odisha covid19 report for 2nd sept new positive cases 174 of which 0 18 years 13 in quarantine 102 local c 6 months can now receive safe amp effective covid 19 vaccines talk to your child doctor amp help them is back in session but even before the first test has been given new numbers have confirmed what many teach that takes this murdering jab is just as stupid as you murderer make it stop america last is fucking with our country hard and they pull this shit again and again they xf0 assamese morning news hours 09 2022 covid19 covid19 could given that money to ukraine ashleigh roy but but you get a little excited clicking the link only to find it s a treatment you ve already tried amp didn t get mu can hear her now msmcmo trump had a cure for covid19 he said just inject disinfectant into your body covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours canmericanized if you believe that only 190 arrivecan tickets were issued since the app was made mandatory than y reptedbudd are you demanding answers from boss trump why he took top sci files why are 4 s time for our leaders to sit up pay attention and expand social security disability benefits to the millions world covid19 vaccine protection rates of 7 countries against infection in the delta amp omicron eras the avera reports first human case of west nile virus this survived covid 19 with them but we now loosing them to tumbwa records 11 new covid 19 cases blame bidentrump fuck them covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p president was just telling the god s truth you follow the evil liar con your trumpy con man demonized thous brendanjanus covid 19 vaccines available in the united states are safe and are effective a 28 2017 age 35 l 23rd last gs win vs sister age 36 9 2 22 pursuit of potus the lockdowns reduced mortality from covid 19 by just 0 2 those jobs should have never been lost in the first place happening in china this woman tried to take down jordan b peterson now she wants to take down her employer you would find the truth of the complete case file regarding the coronavirus from beginning to end imam mahdi n pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri big kristiiiii nowplaying x lilroyce her evil spine feat makrazy demise of society this administration is insane managed to beat covid19 for almost two years then one day newsom in laws moved to florida during the coronavirus hampshire covid 19 updates numbers for cases hospitalizations vaccinations 211 fresh covid 19 cases in india in the last 24 hours covid19 mask mandates are too much to ask for pres biden on covid 19 funds for local economies 2 after words sen tammy duckworth d il every day is a gift cdc director signs off on new covid 19 boosters quietly adds ivermectin to covid 19 treatment guidelines as antiviral therapy big league politics messiah s didthatchokeyou that s almost as stupid as getting the covid 19 vaccination new covid19 variants could emerge this winter the european union drug agency has said but existing va is stupid asean family newsfrommalaysia covid19 malaysia as 2 september 2022 confirmed cases 2 328 research pandemic telehealth utilization related to decrease opioid overdose riskgetting opioid utilizati t co tgmsvs5p8l covid 19 outbreak declared over at bethammi nursing home 3rd floor tbay thunderbay middaynews mumbai sees 402 new covid 19 cases as virus kills 3 mumbainews covid19 covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p i have contacted the clix as well your partner they said we don t have any problem the account is opened only y are living through an intense drought with water resources at all time low scientists may have found a way jon o90 why are you lying about this dems are saving lives republicans were against the gshodl brics also announce that americans are evil and project whatever problems they themselves c serehfas covid surely must be one of the most familiar medical pathogens ever studied by now if this is not ident administration has been shuffling money from other pockets to pay for the new shots after congress failed t another example of the laptop classes hypocrisy who wants to be he supported vaccine mandates and people lo sleepy look after yourself and don t overdo it on the caffeine covid19 socialdistancing emotionalconnection in our icu with frontal contusion gcs full absolutely doing fine for 5 days desaturated one day and his truly do have the biggest fucking joke of a government to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di medicaldevice regulatory daily stories via icis cdnhealth covid19 your unique nft covid 19 colorful variant 6280 now do you already own nfts gracelp they may still be good for a couple months hk watch how great ex cop ce mr lee to use smokescreen of covid to curb freedom n surveillance little kids aged korea reports less than 80 000 new covid 19 cases covid19 southkorea arirang news california gov gavin newsom in laws moved to florida during the chinese coronavirus pandemic 2 0 realdailywire covid19 return to work rebound isn t creating jobs stop distorting the facts pushing inaccurate covid 19 boosters that target the most common omicron strains are set to begin soon 19 update 84 new covid 19 cases reported on september 2 uptown c the website says covid 19 vaccine update cdc now recommends the new updated tucson area coronavirus developments sept 3 what we know billion of tax payer money went to people in prison k datastudio tells us covid has been the 3 cause of death in canada for three years running and yeah county will no longer require covid 19 vaccines for its decontamination and cleaning of their patrol vehicle 66 to prevent the transmission of the deadly covid 1 demands rs 1 000 crore from covid 19 vaccine makers for daughter s death bombay hc issues notice to sii bill friendlycovid19 it s a booster so what doesn t mean the people won t get a visit from our friendly neighborhood covid 19 jeffrey kaami mobile patrol pnco of ozamiz cps under the direct supervision of pmaj dennis pe tano offi officials ordered a lockdown thursday for 21 million people in the southwestern city of chengdu citing an insomniacsmarty oh wow the movie was on tv years ago then i remembered it when the pandemic started one common locks down 21 million people in chengdu over covid 19 outbreak times of a j christ nowplaying x lilroyce her evil spine new coronavirus cases reported in punjab newspaper all this money them niggas better capture moscow and give to us as compensation 19 update india reports 7 219 new covid 19 cases in the last 24 hours personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted pr huffpost she probably most likely got the covid 19 vax it s designed to kill murder elderly and poc persons of it is mandatory for you to wear a face mask at all times at the station or on board the train together le are still other ways to get free covid 19 tests although they may be less convenient than the white house s covid19 india covid 19 update last 24 hours new cases 7 219 recoveries 9 651 active cases 56 745 covid bonginoreport cdc panel votes in favor of recommending new covid 19 boosters that were never tested on human beings redesigned covid 19 booster shots could be available in minnesota as early as alaayous3 way officials are allowing one person in each household to go out to buy necessities once a day the person must pre s covid 19 positivity rate 7 times national average medical surgical laboratory rehabilitation equipments coronavirus preventive kits machines machine s acc tuvillanofv nowplaying x lilroyce her evil spine feat makrazy s covid 19 positivity rate 7 times national average odisha reports 174 new covid19 cases in the last 24 hours 0 18 years 13 in quarantine 102 local contacts 72 s money for everything amp everyone except the peasants it on my 5 year old to protect herself rather than modeling for her how communities protect one another that mile marker 0 cnn has mostly stayed on the right side of things although they can be cr nikkihaley nikki you mean the man who encouraged citizens to drink bleach to kill the covid 19 virus words just disgusted that money should never have been sent to prisoners give to the victims of crime of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic pminmangaluru pm modi mentioned the recent gdp figures and said that policies that india made during covid 19 peri safe stay indoor please follow guidelines issued by authorities save yourself to save others michrajah dr ananda rajah what are your thoughts as a doctor on the proposal to scrap isolation in covid19 managem robytweet sadly i wonder how often it projection it seemed like a lot of the early wave of antivax coronavirus cases in china stayed at elevated levels following the lockdown of a mega city of 21 million as th our presentation of the arctic covid 19 gender response tracker at arctic circle arctic circle assembly s me out why does it say here that people should choose mrna as 3rd boosters when people only need tw josephs26340531 i survived this long by not listening to an orange overlord ar in india live updates india reports 7 219 fresh cases and 9 651 recoveries in the last 24 fda approves the new covid 19 booster before doing human trials instead opting to judge it safe for huma should be put on unpaid leave and then quietly fired like the unvaccinated were personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer i m not happy with biden either on this but at least i historical precedents impeded recognition of airborne covid 19 transmission bonginoreport cdc panel voters in favor of recommending covid 19 boosters that never been tested on human beings want to see your real vaccinations nobody in their right mind would get all of these murdering injections a j christ nowplaying x lilroyce tstorm05 live guyton don t get your issue your boy likes vaccines too trump s latest tweet on coronavirus might be his dumbest yet the borders have opened up human trafficking has increased how do you wash billions of dollars por 19 response plan la county department of public personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re glennhamer he s part of the labor participation problem by hyping u xe2 fda authorized updated covid 19 booster shots are effective experts say personnel of ozamiz cps under the direct supervision of pmaj dennis pe tano officer in charge conducted re just gonna be this over and over until we finally collapse in on ourselves the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p 19 vaccines didn work so cdc changed the definition of vaccines via the first redesigned covid 19 vaccine since 2020 the new bivalent boosters were developed to generate an immu 1 000 reports of adverse events after covid 19 vaccination in toddlers babies covid 19 test has been stopped by south korea for inbound travellers covid19 to coronavirus indian people are worst sufferer since 22 03 2020 crores of people affected lakhs of people di yorlyx s weekly covid 19 cases 27 august 1 september 2022 trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc case wasn aware for newly authorized covid 19 boosters based on mice not humans via the church then audit the hell out of them failed gop candidate says god will end covid 19 if u s condemns hold out the longest got an appt for sunday bivalentbooster oregon freeman and matt hancock argued at first covid 19 cobra the national have the right to refuse unsafe work but do not have the right to determine what is considered unsafe good l kuyashii desu whyyyy but haru yo koi that program saved me during my lonely nights working at covid 19 facility 219 infections india s covid 19 tally of cases to 44 49 726 death toll climbs to 27 965 govt have injected 70m of our people of sub par wages occasional violence denial of the toilet inside the home separate utensils for domestic lie friska adv eliz dara0 abidin l1e adv gateway lease waived rent waived rent reduced financial relief due to covid 19 sign the petition covid19 india reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily p wonder what irving city council member al zapanta is doing about covid 19 in their district company profits are collapsing like its 2020 again news social impact the perfect enemy reports 7 219 fresh cases and 9 651 recoveries in the last 24 hours active cases 56 745 daily positivity r xf0 for more details visit india india profawpeet does the fact and its affiliates get over 10 000 000 in funding yearly from the nih make you l promotes sex heavy heavy heavy like most women in the industry but she never really says nothing for you to l this blog from dra pat testing keep your staff homes safe from coronavirus if they working from home suemidd58863059 really not hard start your reading here there are now new booster appointments available at cvs and walgreens just scheduled mine at the first avail suspends chinese airline flights in covid 19 19 vaccine effectiveness plunges against omicron cdc data via you believe this two elderly men theirselves saying the elderly should voluntarily die to save the economy nile virus 2nd human case this year found in massachusetts t co rrjxht8t4g xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp am sure they won stop u from wearing a mask if u choose to wear one trudeaufortreason duped crimesagainsthumanity covid19ab covidisnotover abpoli ableg cndpoli yeg ycc xe2 the alarm bells are ringing for jobseeker so why is there now room in the budget covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates who coronavirus disease covid 19 dashboard with vaccination data 2 september 2022 there have been 515 30 covid 19 is real mockingbird msm singing from same hymn sheet effective brainwashing used with covid19 and vaccine expectancy drops in america due to covid 19 courtesy of david flickr cc0 in 2021 the life expectancy dropped requirements south korea travel advice irs is not randomly giving away 782 as covid 19 disaster relief clicking on the link in the email will lead hello all greetings from the breadbasket states we are alive and well without masks here um serious quest covid19 now by going to your local and eating a handful of little powerful hot peppers they wil vanessa10009 the lancet covid 19 commission is headed by jeffrey sachs a person with no domain expertise in any r can we have a report on covid19 handling in india for 2021 please you get a new covid 19 booster if so when android app reviews iot flutter javascript serverless cybersecurity seosmmworld 19 gave new urgency to the science of restoring has evolved to make you sicker quicker new study finds marshablackburn biden inherited a total mess from trump who just lost his job because of his gross negligence in orla9000 the massive levels of government spending that congress threw at the pandemic including vax camps to be held on all sundays in september tn health minister source the new indian express vaxcamp stuyvesantanna yeah the study that cites the covid19 vaccine works against relaxbdg nowplaying x lilroyce her evil spine feat makrazy google maps reviews datascience python ai 100daysofcode iot truck group is hiring in elmhurst for a hr benefits administrator click now to apply rpbreakingnews new covid 19 boosters that target today most common omicron strains are set to begin soon i am fr latest the vaccines worldcourts science daily thanks to schofield covid19 science covid 19 outcomes increase in latest manitoba report cbc news xf0 denmark royal house released a brief schedule celebrating queen margrethe ii goldenjubilee which was postp governors gave lucrative no bid covid 19 deals to utah firms who then gave 1m to gop campaigns if people want to see the end of mask wearing then we need to replace masks with other public health measures that updates unionhealthministry coronavirus patientsundertreatment deathofpatients covid19 infectionrate the 51 deaths in august are more than the june and july fatalities doctors say most of these cases are among lead stories in major taiwan dailies on saturday covid19 vaccine local government elections stock picks covid19 india reports 7 219 fresh cases in last 24 hours active cases reduce to 56 745 coronavirusupdates wyonaf we have a friend whose maga husband was an ardent trump er an antimask amp antivax er he was lucky an 19 jammu and kashmir reports 152 new cases of the new cases 40 were reported from jammu and 112 from kashmi right now wakeuplagos w 176 days to nigeria s general election whose camp currently h demands rs 1 000 crore from covid19 vaccine makers for daughter s death bombay hc issues notice to sii bill authorizes updated covid 19 boosters despite lack of clinical data via t co tnexyq4klr the fda and cdc have approved new bivalent vaccines by pfizer and moderna that target both tppatriots cdc panel votes in favor of recommendi

In [ ]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
processed_docs = preprocess(complete_text)

In [ ]:
dictionary = gensim.corpora.Dictionary([processed_docs])

In [ ]:
count = 0
for k, v in dictionary.iteritems():
    print(k, v)
    count += 1
    if count > 10:
        break

0 aaaaaaaaa
1 aajtak
2 aapi
3 aapl
4 aarogya
5 aaron
6 aarondodd
7 aaronla
8 aaronparna
9 aarospeir
10 aayeff

In [ ]:
#dictionary.filter_extremes(no_below=20, no_above=0.1, keep_n= 1000000)
#dictionary.filter_extremes(no_above=0.70)

In [ ]:
dictionary

In [ ]:
#bow_corpus = dictionary.doc2bow(processed_docs)

bow_corpus = [dictionary.doc2bow(processed_docs),]
#bow_corpus = [dictionary.doc2bow(text) for text in processed_docs]
print(bow_corpus[:1])

[[]]

In [ ]:
#LDA
lda_model = gensim.models.ldamodel.LdaModel(corpus=bow_corpus, 
                                            num_topics = 20, 
                                            id2word = dictionary,
                                            random_state=100,
                                            update_every=1,
                                            chunksize=100,
                                            alpha='auto',
                                            per_word_topics=True,
                                            passes = 50)

In [ ]:
for idx, topic in lda_model.print_topics(-1):
    print("Topic: {} \nWords: {}".format(idx, topic ))
    print("\n")

In [ ]:
import re
import numpy as np
import pandas as  pd
from pprint import pprint# Gensim
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
#from gensim.models import CoherenceModel# spaCy for preprocessing
import spacy# Plotting tools
#import pyLDAvis
#import pyLDAvis.gensim
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
!pip3 install spacy

!python3 -m spacy download en #Language model

#pip3 install gensim # For topic modeling

#pip3 install pyLDAvis # For visualizing topic models

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.7/dist-packages (3.4.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.21.6)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (8.1.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.1.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.3)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.11.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.0.7)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy) (57.4.0)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.4.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.0.8)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy) (1.9.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (21.3)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy) (0.6.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (4.64.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.23.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy) (2.0.6)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy) (5.2.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.24.3)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy) (2.0.1)
2022-10-06 08:42:33.861063: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting en-core-web-sm==3.4.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.4.0/en_core_web_sm-3.4.0-py3-none-any.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 7.4 MB/s
Requirement already satisfied: spacy<3.5.0,>=3.4.0 in /usr/local/lib/python3.7/dist-packages (from en-core-web-sm==3.4.0) (3.4.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.4.4)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.64.1)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.0.8)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.6.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.10.0,>=1.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.9.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (57.4.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (21.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.7)
Requirement already satisfied: thinc<8.2.0,>=8.1.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (8.1.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.23.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.6)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.3.0)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.21.6)
Requirement already satisfied: wasabi<1.1.0,>=0.9.1 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.10.1)
Requirement already satisfied: typer<0.5.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.11.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.8)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.9 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.10)
Requirement already satisfied: typing-extensions<4.2.0,>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.6->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.9)
Requirement already satisfied: smart-open<6.0.0,>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pathy>=0.3.5->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (5.2.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.10)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.7/dist-packages (from thinc<8.2.0,>=8.1.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (0.7.8)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer<0.5.0,>=0.3.0->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy<3.5.0,>=3.4.0->en-core-web-sm==3.4.0) (2.0.1)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
# NLTK Stop words
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
stop_words.extend(['from', 'subject', 're', 'edu', 'use'])

In [ ]:
def sent_to_words(sentences):
  for sentence in sentences:
    yield(gensim.utils.simple_preprocess(str(sentence), deacc=True))            #deacc=True removes punctuations

In [ ]:
data_words = list(sent_to_words(data))
print(data_words[:1])

[['and', 'we', 'should', 'panic', 'and', 'not', 'send', 'the', 'kids', 'to', 'school', 'cbc', 'presstitutes', 'all', 'imho']]

In [ ]:
bigram = gensim.models.Phrases(data_words, min_count=5, threshold=100) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=100)
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)
print(trigram_mod[bigram_mod[data_words[0]]])

/usr/local/lib/python3.7/dist-packages/gensim/models/phrases.py:598: UserWarning: For a faster implementation, use the gensim.models.phrases.Phraser class
  warnings.warn("For a faster implementation, use the gensim.models.phrases.Phraser class")

['and', 'we', 'should', 'panic', 'and', 'not', 'send', 'the', 'kids', 'to', 'school', 'cbc', 'presstitutes', 'all', 'imho']

In [ ]:
def remove_stopwords(texts):
    return [[word for word in simple_preprocess(str(doc)) if word not in stop_words] for doc in texts]

def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]

def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]

def lemmatization(texts, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV']):
    """https://spacy.io/api/annotation"""
    texts_out = []
    for sent in texts:
        doc = nlp(" ".join(sent)) 
        texts_out.append([token.lemma_ for token in doc if token.pos_ in allowed_postags])
    return texts_out

In [ ]:
data_words_nostops = remove_stopwords(data_words)

data_words_bigrams = make_bigrams(data_words_nostops)

nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

data_lemmatized = lemmatization(data_words_bigrams, allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV'])

In [ ]:
print(data_lemmatized[:5])

[['panic', 'send', 'kid', 'school', 'cbc', 'presstitute', 'imho'], ['say', 'last', 'forever', 'maybe', 'go', 'away'], ['explain'], ['ericcolumbus', 'article', 'say', 'positivity'], ['thedailybeast', 'surprise', 'absurd', 'think', 'expect', 'university', 'student', 'stay']]

In [ ]:
id2word = corpora.Dictionary(data_lemmatized)  
texts = data_lemmatized  
corpus = [id2word.doc2bow(text) for text in texts]  
print(corpus[:1])

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)]]

In [ ]:
lda_model = gensim.models.ldamodel.LdaModel(corpus=corpus,
                                           id2word=id2word,
                                           num_topics=20, 
                                           random_state=100,
                                           update_every=1,
                                           chunksize=100,
                                           passes=50,
                                           alpha='auto',
                                           per_word_topics=True)

In [ ]:
# Print the keyword of topics
from pprint import pprint
pprint(lda_model.print_topics())

[(0,
  '0.142*"get" + 0.035*"student" + 0.023*"lie" + 0.022*"talk" + 0.021*"return" '
  '+ 0.021*"public" + 0.017*"pay" + 0.016*"rule" + 0.015*"part" + '
  '0.015*"hold"'),
 (1,
  '0.074*"news" + 0.063*"year" + 0.053*"think" + 0.046*"way" + 0.027*"turn" + '
  '0.026*"result" + 0.025*"expect" + 0.022*"order" + 0.018*"fuck" + '
  '0.018*"stay"'),
 (2,
  '0.487*"covid" + 0.052*"test" + 0.043*"day" + 0.034*"positive" + '
  '0.034*"state" + 0.030*"update" + 0.017*"rise" + 0.016*"testing" + '
  '0.015*"high" + 0.013*"right"'),
 (3,
  '0.148*"death" + 0.069*"amp" + 0.055*"number" + 0.042*"late" + '
  '0.029*"reopen" + 0.028*"infection" + 0.022*"run" + 0.020*"travel" + '
  '0.020*"already" + 0.017*"seem"'),
 (4,
  '0.316*"case" + 0.156*"coronavirus" + 0.131*"new" + 0.058*"report" + '
  '0.029*"first" + 0.017*"hospital" + 0.016*"recovery" + 0.012*"quarantine" + '
  '0.010*"away" + 0.009*"supply"'),
 (5,
  '0.065*"mask" + 0.062*"make" + 0.046*"lockdown" + 0.033*"tell" + '
  '0.027*"strategy" + 0.020*"doctor" + 0.018*"hard" + 0.017*"expert" + '
  '0.016*"learn" + 0.016*"shutdown"'),
 (6,
  '0.088*"total" + 0.066*"today" + 0.050*"good" + 0.050*"country" + '
  '0.036*"really" + 0.033*"lead" + 0.031*"recover" + 0.030*"stat" + '
  '0.027*"daily" + 0.025*"job"'),
 (7,
  '0.096*"pandemic" + 0.066*"die" + 0.053*"health" + 0.043*"live" + '
  '0.038*"come" + 0.033*"worker" + 0.030*"change" + 0.018*"city" + '
  '0.017*"become" + 0.015*"concern"'),
 (8,
  '0.162*"confirm" + 0.119*"last" + 0.052*"week" + 0.038*"trend_sep" + '
  '0.028*"restriction" + 0.021*"resume" + 0.021*"post" + 0.020*"postpone" + '
  '0.018*"research" + 0.017*"days_stat"'),
 (9,
  '0.154*"people" + 0.043*"help" + 0.041*"back" + 0.039*"face" + 0.030*"much" '
  '+ 0.029*"wear" + 0.021*"safe" + 0.016*"do" + 0.014*"human" + 0.013*"man"'),
 (10,
  '0.121*"time" + 0.087*"record" + 0.043*"realdonaldtrump" + 0.038*"patient" + '
  '0.034*"kill" + 0.026*"link" + 0.022*"community" + 0.022*"situation" + '
  '0.019*"push" + 0.018*"sure"'),
 (11,
  '0.042*"work" + 0.031*"well" + 0.030*"still" + 0.023*"thing" + 0.020*"give" '
  '+ 0.020*"business" + 0.020*"family" + 0.020*"call" + 0.019*"also" + '
  '0.017*"increase"'),
 (12,
  '0.136*"say" + 0.035*"even" + 0.026*"pos" + 0.026*"outbreak" + 0.024*"end" + '
  '0.022*"election" + 0.022*"mean" + 0.021*"never" + 0.019*"article" + '
  '0.016*"protect"'),
 (13,
  '0.061*"need" + 0.057*"school" + 0.040*"home" + 0.032*"close" + 0.030*"let" '
  '+ 0.026*"potential" + 0.019*"put" + 0.019*"fall" + 0.018*"hit" + '
  '0.018*"hear"'),
 (14,
  '0.043*"plan" + 0.038*"global" + 0.030*"follow" + 0.024*"service" + '
  '0.023*"create" + 0.023*"child" + 0.023*"date" + 0.022*"rate" + 0.017*"try" '
  '+ 0.016*"important"'),
 (15,
  '0.093*"trump" + 0.041*"virus" + 0.040*"look" + 0.038*"bad" + 0.025*"cause" '
  '+ 0.025*"dead" + 0.021*"happen" + 0.019*"story" + 0.019*"share" + '
  '0.017*"add"'),
 (16,
  '0.068*"due" + 0.065*"government" + 0.036*"active" + 0.036*"download" + '
  '0.036*"spread" + 0.034*"stop" + 0.030*"keep" + 0.024*"datum" + '
  '0.022*"medium" + 0.020*"contain"'),
 (17,
  '0.147*"vaccine" + 0.066*"know" + 0.033*"show" + 0.033*"find" + '
  '0.025*"start" + 0.021*"use" + 0.020*"early" + 0.019*"leave" + '
  '0.017*"response" + 0.014*"sign"'),
 (18,
  '0.104*"go" + 0.052*"see" + 0.051*"many" + 0.040*"month" + 0.040*"want" + '
  '0.029*"life" + 0.020*"lose" + 0.020*"open" + 0.016*"person" + 0.016*"risk"'),
 (19,
  '0.074*"take" + 0.067*"world" + 0.035*"great" + 0.030*"care" + '
  '0.025*"support" + 0.017*"hope" + 0.017*"study" + 0.015*"set" + '
  '0.014*"stock_market" + 0.014*"money"')]

In [ ]:
doc_lda = lda_model[corpus]

In [ ]:
# Compute Perplexity
print('\nPerplexity: ', lda_model.log_perplexity(corpus))  
# a measure of how good the model is. lower the better.

Perplexity:  -9.5473275827816

In [ ]:
# Compute Coherence Score
from gensim.models import CoherenceModel# spaCy for preprocessing
coherence_model_lda = CoherenceModel(model=lda_model, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_lda = coherence_model_lda.get_coherence()
print('\nCoherence Score: ', coherence_lda)

Coherence Score:  0.32399096642698055

In [ ]:
!pip3 install pyLDAvis==2.1.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyLDAvis==2.1.2
  Downloading pyLDAvis-2.1.2.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 8.2 MB/s
Requirement already satisfied: wheel>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.37.1)
Requirement already satisfied: numpy>=1.9.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.21.6)
Requirement already satisfied: scipy>=0.18.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.7.3)
Requirement already satisfied: pandas>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.3.5)
Requirement already satisfied: joblib>=0.8.4 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (1.1.0)
Requirement already satisfied: jinja2>=2.7.2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.11.3)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (2.8.3)
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (3.6.4)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis==2.1.2) (0.16.0)
Collecting funcy
  Downloading funcy-1.17-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.7.2->pyLDAvis==2.1.2) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.0->pyLDAvis==2.1.2) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.17.0->pyLDAvis==2.1.2) (1.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from numexpr->pyLDAvis==2.1.2) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->numexpr->pyLDAvis==2.1.2) (3.0.9)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (57.4.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (1.4.1)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (22.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->pyLDAvis==2.1.2) (8.14.0)
Building wheels for collected packages: pyLDAvis
  Building wheel for pyLDAvis (setup.py) ... done
  Created wheel for pyLDAvis: filename=pyLDAvis-2.1.2-py2.py3-none-any.whl size=97738 sha256=b2f5ee9b2ab4de43e7701464186c6d653535194e70c0b9291c57afd8007bd629
  Stored in directory: /root/.cache/pip/wheels/3b/fb/41/e32e5312da9f440d34c4eff0d2207b46dc9332a7b931ef1e89
Successfully built pyLDAvis
Installing collected packages: funcy, pyLDAvis
Successfully installed funcy-1.17 pyLDAvis-2.1.2

In [ ]:
for index, topic in lda_model.show_topics(formatted=False, num_words= 50):
    print('Topic: {} \nWords: {}'.format(index, [w[0] for w in topic]))

Topic: 8
Words: ['confirm', 'last', 'week', 'trend_sep', 'restriction', 'resume', 'post', 'postpone', 'research', 'days_stat', 'move', 'soar', 'donaldjtrumpjr', 'funny', 'pressure', 'overall', 'past', 'position', 'strain', 'church', 'lag', 'johns_hopkin', 'currently', 'film', 'obsess', 'lost_control', 'straw', 'fix', 'ad', 'experiment', 'south_wale', 'domestic', 'customer', 'size', 'daddy', 'hrs', 'politicize', 'temporarily', 'rooker_detail', 'verify', 'grant', 'minute', 'forward', 'yo', 'encourage', 'user', 'playoff', 'updates_globally', 'fox', 'zoom']
Topic: 10
Words: ['time', 'record', 'realdonaldtrump', 'patient', 'kill', 'link', 'community', 'situation', 'push', 'sure', 'trend', 'play', 'page', 'citizen', 'gossip', 'last_hour', 'fresh', 'politic', 'forever', 'combat', 'yesterday', 'form', 'bank', 'partner', 'wave', 'golf', 'misinformation', 'requirement', 'theory', 'maine_wedding', 'review', 'typical', 'scott_morrison', 'plague', 'twitter', 'face_bleak', 'takes_toll', 'describe', 'fill', 'instance', 'perhaps', 'chennai', 'awareness', 'discharge', 'diabetes', 'everyday', 'lowest', 'common', 'thug', 'flood']
Topic: 6
Words: ['total', 'today', 'good', 'country', 'really', 'lead', 'recover', 'stat', 'daily', 'job', 'big', 'official', 'bring', 'reach', 'game', 'second', 'other', 'course', 'age', 'united_state', 'action', 'average', 'labor_day', 'epidemic', 'decline', 'forecast_predict', 'sir', 'mental_health', 'present', 'sit', 'else', 'success', 'amazing', 'complete', 'andrew', 'pe', 'cop', 'identify', 'region', 'secondwave', 'around', 'dumb', 'corrupt', 'shame', 'winter', 'concert', 'manufacture', 'probable', 'rank', 'mountain']
Topic: 16
Words: ['due', 'government', 'active', 'download', 'spread', 'stop', 'keep', 'datum', 'medium', 'contain', 'ever', 'remember', 'party', 'reveal', 'join', 'actually', 'base', 'future', 'war', 'percent', 'handle', 'credit', 'strong', 'exist', 'metro_service', 'income', 'resident', 'petition', 'girl', 'cross', 'attack', 'poll', 'cancel_student', 'unable', 'live_update', 'taste', 'bulletin', 'brilliant', 'prepare', 'deliver', 'disappear', 'waste', 'dear_viewer', 'western', 'estimate', 'tomorrow', 'celebrate', 'movie', 'smell', 'hyderabad']
Topic: 5
Words: ['mask', 'make', 'lockdown', 'tell', 'strategy', 'doctor', 'hard', 'expert', 'learn', 'shutdown', 'transmission', 'point', 'effective', 'police', 'social_distance', 'researcher', 'hoax', 'demand', 'fear', 'cost', 'guideline', 'employer', 'avoid', 'air', 'seriously', 'instead', 'education', 'campus', 'condition', 'remain', 'jump', 'throw', 'walk', 'idea', 'current', 'advise', 'attend', 'bit', 'victorian', 'essential', 'possibly', 'wedding', 'statement', 'goal', 'nurse', 'sense', 'staysafe', 'introduce', 'unofficial', 'enjoy']
Topic: 12
Words: ['say', 'even', 'pos', 'outbreak', 'end', 'election', 'mean', 'never', 'article', 'protect', 'vote', 'top', 'lot', 'receive', 'nation', 'least', 'team', 'video', 'ahead', 'member', 'drug', 'publish', 'price', 'approve', 'major', 'stupid', 'threat', 'miss', 'cope', 'require', 'digital', 'negative', 'player', 'info', 'mail', 'gdp', 'growth', 'lock', 'interview', 'reuter', 'touch', 'choose', 'cov', 'promise', 'interested', 'million', 'house', 'funding', 'court', 'recommend']
Topic: 18
Words: ['go', 'see', 'many', 'month', 'want', 'life', 'lose', 'open', 'person', 'risk', 'check', 'long', 'break', 'ask', 'fight', 'worry', 'surge', 'infect', 'far', 'weekend', 'accord', 'true', 'system', 'delay', 'speak', 'area', 'grow', 'shit', 'visit', 'test_kit', 'teacher', 'compare', 'project', 'allow', 'cancel', 'treat', 'half', 'industry', 'exceed', 'site', 'export', 'predict', 'detail', 'answer', 'moment', 'trace', 'folk', 'era', 'suppose', 'truth']
Topic: 4
Words: ['case', 'coronavirus', 'new', 'report', 'first', 'hospital', 'recovery', 'quarantine', 'away', 'supply', 'announce', 'line', 'staff', 'law', 'stand', 'note', 'admit', 'worldwide', 'healthcare_worker', 'ass', 'fake', 'york_time', 'notice', 'college_town', 'trend_sep', 'past_hour', 'district', 'regional', 'delhi', 'village', 'strike', 'file', 'ipswich_hospital', 'database', 'days_stat', 'grade', 'donald_tr', 'shirish', 'web', 'assistance', 'writer', 'exempt', 'conspiracy', 'representative', 'pandem', 'gov_admit', 'saudi_arabia', 'middle_class', 'verge', 'wyoming']
Topic: 11
Words: ['work', 'well', 'still', 'thing', 'give', 'business', 'family', 'call', 'also', 'increase', 'economy', 'thank', 'continue', 'impact', 'crisis', 'place', 'free', 'real', 'track', 'woman', 'watch', 'safety', 'include', 'fund', 'medical', 'friend', 'govt', 'challenge', 'young', 'blame', 'additional', 'head', 'level', 'season', 'australian', 'likely', 'history', 'summer', 'cover', 'effect', 'mistake', 'wish', 'toll', 'huge', 'climate', 'old', 'exactly', 'book', 'slow', 'source']
Topic: 2
Words: ['covid', 'test', 'day', 'positive', 'state', 'update', 'rise', 'testing', 'high', 'right', 'read', 'next', 'soon', 'hour', 'force', 'th', 'deal', 'lakh', 'science', 'mark', 'trust', 'alone', 'single', 'employee', 'conduct', 'clear', 'sewage', 'count', 'park', 'production', 'death_toll', 'adequate', 'auspol', 'sept', 'covi', 'fatality', 'tourist', 'simply', 'tally', 'alert', 'register', 'triple', 'priority', 'later', 'bengaluru', 'perform', 'coro', 'please', 'reinfection', 'crosse']

In [ ]:
for idx, topic in lda_model.show_topics(formatted=False, num_topics=20, num_words= 100):
    print('Topic: {} \nWords: {}'.format(idx, '|'.join([w[0] for w in topic])))

Topic: 0
Words: get|student|lie|talk|return|public|pay|rule|part|hold|warn|guy|college|app|social|reduce|labor|forget|food|sick|large|act|write|eat|finally|rest|suspend|contact|experience|emergency|opportunity|explain|front|smartnew|fan|football|search|nyu_student|energy|design|ban|centre|wit|endless|critical|dream|elect|bill|indeed|kick|violate|trip|gather|drink|hotel|enter|weather|weak|operate|restaurant|maintain|flight|crazy|hotspot|task|lawsuit|property|opt|rent|comfort|trumpvirus|celebration|usopen|joy|adapt|joebiden|famine|democracy|potus|sort|detect|endure|university_dismisse|enforce|shelter|necessary|dis|stay_safe|shoot|housing|op|smh|insurance|signed_petition|tuition_fee|stock|value|respect|phone|degree
Topic: 1
Words: news|year|think|way|turn|result|expect|order|fuck|stay|believe|low|university|feel|american|event|figure|especially|serious|quite|holiday|address|exam|thousand|whole|tax|indian|governor|responsible|fool|management|appear|passenger|surprise|covidiot|conversation|example|definitely|direct|actual|maga|evil|complain|arrest|stinky_savior|couple|pack|proud|suck|view|valuation|birthday|busy|loved_one|society|meanwhile|mess|solution|infected|capacity|looking_forward|labordayweekend|second_wave|assume|modi|plane|session|anyway|ridiculous|lifestyle|executive|rape|announcement|hell|tiny|pregnant|disinformation|ride|ipl|valley|hot|association|pair|misery|upgrade|ago|excellent|strange|receive_astrazeneca|swear|mindful|terrible|asset|editor|everywhere|corruption|trick|cas|angry|downtown
Topic: 2
Words: covid|test|day|positive|state|update|rise|testing|high|right|read|next|soon|hour|force|th|deal|lakh|science|mark|trust|alone|single|employee|conduct|clear|sewage|count|park|production|death_toll|adequate|auspol|sept|covi|fatality|tourist|simply|tally|alert|register|triple|priority|later|bengaluru|perform|coro|please|reinfection|crosse|nsw|voice|trend_sep|health_ministry|hospitalize|civil|delhi_capital|assure|ease_delay|sydney_healthcare|clown|apology|lawyers_warn|airport|characteristic|pen|pattinson|succumb|self_isolate|morrison|solely|nationally|physiotherapist|halt|ff|rat|genetic|days_stat|receive_astrazeneca|speedy_recovery|student_athlete|inspire|scrap|staff_member|sputnikupdate|capitals_assistant|robert_pattinson|kellyannepoll|cm|tomlinson_tomlinson|widespread|spark|sing|grace|tamil_nadu|market_mayhe|unabated_global|dear_viewer|cou|patients_discharge
Topic: 3
Words: death|amp|number|late|reopen|infection|run|travel|already|seem|almost|list|thread|leader|available|center|operation|asymptomatic|wrong|beat|different|matter|access|headline|easy|battle|sound|launch|refuse|individual|statistic|retweet|vacation|dangerous|brother|town|corona|brain|officer|general|voluntary|frontline_worker|subscribe|traveler|sa|attention|sell|dog|location|abo|paper|biden|disaster|trouble|balance|fr|ppl|involve|origin|deck|lucky|dashboard|praise|rd|near|board|sydney_healthcare|earth|discover|reduction|data|indoor|decrease|confuse|saddest|fatality_rate|heal|los_angele|tha|denier|congratulation|faith|sister|accurate|senior|increasingly|trend_sep|rapidly|raising_hope|marxist|college_campuse|match|judge|denial|stfu|own|edition|humble|favorite|solidarity
Topic: 4
Words: case|coronavirus|new|report|first|hospital|recovery|quarantine|away|supply|announce|line|staff|law|stand|note|admit|worldwide|healthcare_worker|ass|fake|york_time|notice|college_town|trend_sep|past_hour|district|regional|delhi|village|strike|file|ipswich_hospital|database|days_stat|grade|donald_tr|shirish|web|assistance|writer|exempt|conspiracy|representative|pandem|gov_admit|saudi_arabia|middle_class|verge|wyoming|queensland|could_demolish|took_decade|sweep|unabated_global|market_mayhe|olympic|birth|highest|gamble|wildfire|stimulus_package|fro|chemical|dear_viewer|lobby|rush|recov|red_zone|minor|hole|thankfully|unitedstate|colorado|tally_crosse|newly|lakh_mark|thus|morrison|duty|recoverie|war_ii|mask_mandate|brilliant_marketing|ideology|repair|dedicated|auckland|rise_sharply|pod|others_cousin|receive_astrazeneca|patriotic|sydney|ndtv|finalised_deal|m|confirmed|lago|france
Topic: 5
Words: mask|make|lockdown|tell|strategy|doctor|hard|expert|learn|shutdown|transmission|point|effective|police|social_distance|researcher|hoax|demand|fear|cost|guideline|employer|avoid|air|seriously|instead|education|campus|condition|remain|jump|throw|walk|idea|current|advise|attend|bit|victorian|essential|possibly|wedding|statement|goal|nurse|sense|staysafe|introduce|unofficial|enjoy|foot|sars_cov|startup|hurt|often|preventive_measure|room|confident|retail|highly|finish|store|unexpected|finger|supply_chain|wide|card|wedding_guest|minnesota_countie|soldier|entitle|agenda|lift|bs|exercise|fellow|alarm|marketing|convince|taxpayer|software|behaviour|brilliant_marketing|owner|suit|permanent|fintech|trend_sep|mandatory|prediction|grand_fork|herald|deem|cult|desk|disposable|recipe|first_union|without_prescription|gun
Topic: 6
Words: total|today|good|country|really|lead|recover|stat|daily|job|big|official|bring|reach|game|second|other|course|age|united_state|action|average|labor_day|epidemic|decline|forecast_predict|sir|mental_health|present|sit|else|success|amazing|complete|andrew|pe|cop|identify|region|secondwave|around|dumb|corrupt|shame|winter|concert|manufacture|probable|rank|mountain|contribute|sc|planet|winner|summary|bankrupt|hammer|pandemi|harm|nancy|cash|appreciate|small_businesse|tout|worst|appoint|error|irony|commute|expensive|well_soon|closing|expire|gain|pelosi|unprecedented|pr|grateful|utter|kerala|ramp|haircut|plunge|arrogance|hav|sop|investor|storm|king|front_line|gov|thief|factor|brexit|sturgis|shatter|superspreader|trend_sep|reinfecte|lion
Topic: 7
Words: pandemic|die|health|live|come|worker|change|city|become|concern|parent|control|extend|viewer|disease|protocol|normal|develop|treatment|together|fact|stage|several|probably|struggle|simple|step|measure|suggest|photo|contact_trace|department|technology|local|floridian|beach|blunder|survey|fatal_math|xe|experts_cause|strict|sex|seek|urge|melbourne|nearly|brilliant_marketing|totally|amount|two_week|induce|approval|anti|prison|order_lock|advice|herd_immunity|pledge|danger|guardian|basic|roadmap|religious|containment|distribution|wa|inform|vic|mayor|carry|culture|silent|particularly|item|survival|developer|pop|underlie|pune|organization|grapple|optimism|trajectory|adhere|sanction|seemingly|chronic|furlough|undermine|guest|al_jazeera|purpose|re|mine|global_warming|depend|drug_companie|equipment|brave
Topic: 8
Words: confirm|last|week|trend_sep|restriction|resume|post|postpone|research|days_stat|move|soar|donaldjtrumpjr|funny|pressure|overall|past|position|strain|church|lag|johns_hopkin|currently|film|obsess|lost_control|straw|fix|ad|experiment|south_wale|domestic|customer|size|daddy|hrs|politicize|temporarily|rooker_detail|verify|grant|minute|forward|yo|encourage|user|playoff|updates_globally|fox|zoom|mortality_rate|officially|cook|breath|extent|rate_drop|hide|empty|dairy|hot_spot|affected|conservative|scroll|punch|steady|bbnaijalockdown|nytime|hug|farm|adoption|slap|fourth|tier|complication|brand|theater|negotiation|hawaii|conflict|de|cricket|convention|preparation|da|absence|exit|curb|gateway_pundit|hariri_confirm|died_fro|accept|consecutive|drain|patient_rape|mock|attach|ancient|leg|san_antonio|timely
Topic: 9
Words: people|help|back|face|much|wear|safe|do|human|man|flu|yet|co|sad|shut|affect|deadly|oil|fast|county|mind|little|status|lack|wh|failure|sport|hero|idiot|trade|vaccinate|earn|joke|none|budget|fun|rather|mother|deserve|memory|charge|family_letter|highlight|anymore|picture|bitch|apparently|violence|correct|donation|song|version|worried|middle|presidential|immediately|fucking|piece|illness|honor|imagine|criminal|evict|bet|explain_puzzle|initial|spending|liberal|trend_sep|bu|legal|gas|minimise|choice|spring|nature|main|behavior|ignorance|poison|safely|contagious|slam|thinking|pan|family_member|awesome|sleep|worship|quote|drugmaker|ward|upset|anticipate|immoral|comprehensive|ignorant|propaganda|eject|market_mayhe
Topic: 10
Words: time|record|realdonaldtrump|patient|kill|link|community|situation|push|sure|trend|play|page|citizen|gossip|last_hour|fresh|politic|forever|combat|yesterday|form|bank|partner|wave|golf|misinformation|requirement|theory|maine_wedding|review|typical|scott_morrison|plague|twitter|face_bleak|takes_toll|describe|fill|instance|perhaps|chennai|awareness|discharge|diabetes|everyday|lowest|common|thug|flood|successfully|successful|boat|uses_debunked|vi|lung_damage|caseload|rapid|bury|study_find|maine|outcome|golfing|seriousness|maharashtra|pope|ra|incompetence|related|row|expand|trend_sep|parenting|tiktok|sand|killer|supercomputer_analyze|border_closure|jobkeeper|bee|globaltimesnew|comorbiditie|reception|racial_injustice|focused|parking|sovereign|wea|myth|cuomo|deb|frequent|dedicate|clarity|fin|days_stat|moon|vaping|gaming|rajasthan
Topic: 11
Words: work|well|still|thing|give|business|family|call|also|increase|economy|thank|continue|impact|crisis|place|free|real|track|woman|watch|safety|include|fund|medical|friend|govt|challenge|young|blame|additional|head|level|season|australian|likely|history|summer|cover|effect|mistake|wish|toll|huge|climate|old|exactly|book|slow|source|black|sale|feature|meet|spend|street|ease|light|destroy|ignore|massive|authority|facility|financial|one|astrazeneca|benefit|build|completely|prime_minister|recent|side|isolation|realjameswood|power|race|chance|road|selfish|rich|violation|healthcare|military|remind|gopchairwoman|immunity|sorry|blow|spy|assist|bed|profit|account|racism|promote|pretty|art|careful|bus|realize
Topic: 12
Words: say|even|pos|outbreak|end|election|mean|never|article|protect|vote|top|lot|receive|nation|least|team|video|ahead|member|drug|publish|price|approve|major|stupid|threat|miss|cope|require|digital|negative|player|info|mail|gdp|growth|lock|interview|reuter|touch|choose|cov|promise|interested|million|house|funding|court|recommend|ongoing|double|literally|mile|roll|extra|gap|coronaviru|unit|learning|respond|burn|mate|aim|short|accelerate|crime|dan_andrew|ai|restore|payment|nursing_home|enhance|basis|scientific|thought|infectious|print|save_live|speed|voter|b|trust_donald|standard|pretend|box|title|facebook|supplement|plot|investigation|republican|round|peak|relief_package|desperate|spin|rhea|finding|criterion
Topic: 13
Words: need|school|home|close|let|potential|put|fall|hit|hear|enough|market|kid|love|provide|population|decision|reason|panic|win|discuss|sometimes|full|drive|save|model|bubble|podcast|diagnose|practice|boy|night|loss|self|odd|regard|donate|distance|limit|third|send|tie|private|side_effect|opening|fiscal|ruin|entire|episode|stuff|lung|inside|schools_reopen|mondaythought|special|hong_kong|non|happy|defense|retire|chapter|vulnerable|import|cold|score|eye|educate|tough|distribute|fit|sanitize|serve|hire|regardless|brazilian|maker|salary|debut|rip|seal|topic|proof|water|materials_get|complete_project|project_topic|station|apply|maine_wedde|fair|thehill|tired|youth|achieve|youtube|secure|teesside|guide|block|hungry
Topic: 14
Words: plan|global|follow|service|create|child|date|rate|try|important|federal|drop|question|information|class|fail|economic|word|national|maybe|catch|program|wonder|body|pass|hate|trial|progress|cut|unicef|administration|buy|hardly|raise|small|unemployment|focus|manage|former|blog|survive|positivity_rate|relief|protection|wake|website|contract|afraid|household|type|publicly|hundred|eviction|climb|development|vitamin|crowd|advocate|nice|arrive|globally|weekly|father|hang|poverty|various|journalist|clinical|super|planning|agency|animal|aka|gear|cooperation|closure|homeless|contagion|dude|either|downturn|train_service|shrink|threaten|recovered_critical|sadly|phase|defeat|skyrocket|neighborhood|hopefully|aware|aviation|obviously|extremely|preserve|capital|face_shield|consequence|suspect
Topic: 15
Words: trump|virus|look|bad|cause|dead|happen|story|share|add|pm|issue|office|key|claim|spike|lesson|improve|protest|surpass|heart|ready|leadership|train|gathering|poor|political|loan|false|campaign|victim|death_certificate|riot|online_learne|stimulus|pick|shortage|green|professional|reminder|candle|car|fly|meeting|rally|message|shameful|bear|white|process|racist|downplay|supporter|pre|wear_mask|cancer|cell|eliminate|straight|bunch|fatigue|disconnect|tv|mumbai|vital|debate|spot|airline|crisis_shatter|scene|syndrome_severely|soup|conspiracy_theorie|controversial|briefing|advance|exchange|nyt|evening|dem|cumulative|con|trend_sep|veteran|opinion|survivor|terrorist|command|big_dream|mix|exponential|pathetic|particle|economist|popping|defend|horse|remark|subsidy|blue
Topic: 16
Words: due|government|active|download|spread|stop|keep|datum|medium|contain|ever|remember|party|reveal|join|actually|base|future|war|percent|handle|credit|strong|exist|metro_service|income|resident|petition|girl|cross|attack|poll|cancel_student|unable|live_update|taste|bulletin|brilliant|prepare|deliver|disappear|waste|dear_viewer|western|estimate|tomorrow|celebrate|movie|smell|hyderabad|premier|pet|central|shock|quickly|heat|wi|allege|boom|emulate|enterprise|door|confidence|belief|reasoning|outdoor|weapon|window|gross|wonderful|consistent|playbook|heart_damage|platform|plastic|diagnostic|resilient|abroad|plandemic|kellyannepoll|residential|prevention|insight|living|evaluate|prepared|perpetrate|package|lady|visa|unite|behave|obvious|territory|terrorism|invite|brilliant_marketing|voluntarily|denounce|sufferer
Topic: 17
Words: vaccine|know|show|find|start|use|early|leave|response|sign|begin|scientist|analysis|candidate|guess|less|possible|name|always|able|group|hand|chinese|kind|oppression|cure|south_korean|leaders_urge|blood|offer|bar|however|unlock|novel|produce|mild|suicide|boost|tip|damage|map|com|pull|rock|fire|doubt|term|network|aid|stress|antibody|incompetent|host|dose|russian|recently|approach|politician|mass|welcome|heavy|load|facilitates_development|cage|explore|revenue|severity|agreement|shield|physical|crew|medicine|beer|viral|ab|alternative|reporting|shincheonji_church|experimental|awful|hcq|closed|participate|accuse|request|nail|unproven|horrible|xf|scale|clean|detection|helpful|protein|award|humanitarian|neighbor|preventable|skeptical|receive_astrazeneca
Topic: 18
Words: go|see|many|month|want|life|lose|open|person|risk|check|long|break|ask|fight|worry|surge|infect|far|weekend|accord|true|system|delay|speak|area|grow|shit|visit|test_kit|teacher|compare|project|allow|cancel|treat|half|industry|exceed|site|export|predict|detail|answer|moment|trace|folk|era|suppose|truth|jail|sector|vaccination|remove|overseas|memorial|hair|quick|exposure|worth|justice|role|dad|debt|reply|certain|majority|prove|chart|tr|music|ability|lab|s|schedule|whitehouse|circumstance|significant|cast|apple|cry|alive|elderly|fully|rail|cluster|mom|freedom|grandma|venue|suddenly|impose|bird|holiday_weekend|section|disagree|invisible|metric|po|importance
Topic: 19
Words: take|world|great|care|support|hope|study|set|stock_market|money|tweet|understand|wait|company|policy|educate_talk|hello_co|effort|suffer|online|evidence|relate|problem|remote|morning|release|symptom|agree|fine|mount|prevent|interesting|sucker|international|emerge|daniel_andrew|resource|final|expose|damn|president|ensure|pray|consider|tech|precaution|click|stigma|curve|chief|bullshit|severe|annual|loser|club|teach|decide|shot|democratic|prayer|quarter|climate_change|activity|like|similar|minister|flatten|market_mayhe|unabated_global|philippine|comment|letter|border|championship|antibodie|virtual|absolutely|investigate|liar|tree|personal|pro|multiple|mention|period|grave|six_month|target|breach|clinic|recommendation|slump|master|listen|protester|commit|clearly|transmit|method|blm

In [ ]:
from gensim.parsing.preprocessing import preprocess_string, strip_punctuation, strip_numeric

lda_topics = lda_model.show_topics(num_topics=20, num_words=50)

topics = []
filters = [lambda x: x.lower(), strip_punctuation, strip_numeric]

for topic in lda_topics:
    print(topic)
    topics.append(preprocess_string(topic[1], filters))

print(topics)

(0, '0.142*"get" + 0.035*"student" + 0.023*"lie" + 0.022*"talk" + 0.021*"return" + 0.021*"public" + 0.017*"pay" + 0.016*"rule" + 0.015*"part" + 0.015*"hold" + 0.014*"warn" + 0.013*"guy" + 0.012*"college" + 0.011*"app" + 0.011*"social" + 0.011*"reduce" + 0.011*"labor" + 0.010*"forget" + 0.010*"food" + 0.010*"sick" + 0.009*"large" + 0.008*"act" + 0.008*"write" + 0.008*"eat" + 0.007*"finally" + 0.007*"rest" + 0.007*"suspend" + 0.007*"contact" + 0.007*"experience" + 0.006*"emergency" + 0.006*"opportunity" + 0.006*"explain" + 0.005*"front" + 0.005*"smartnew" + 0.005*"fan" + 0.005*"football" + 0.005*"search" + 0.005*"nyu_student" + 0.004*"energy" + 0.004*"design" + 0.004*"ban" + 0.004*"centre" + 0.004*"wit" + 0.004*"endless" + 0.004*"critical" + 0.004*"dream" + 0.004*"elect" + 0.004*"bill" + 0.004*"indeed" + 0.004*"kick"')
(1, '0.074*"news" + 0.063*"year" + 0.053*"think" + 0.046*"way" + 0.027*"turn" + 0.026*"result" + 0.025*"expect" + 0.022*"order" + 0.018*"fuck" + 0.018*"stay" + 0.018*"believe" + 0.017*"low" + 0.013*"university" + 0.012*"feel" + 0.011*"american" + 0.011*"event" + 0.009*"figure" + 0.009*"especially" + 0.008*"serious" + 0.008*"quite" + 0.008*"holiday" + 0.007*"address" + 0.007*"exam" + 0.006*"thousand" + 0.006*"whole" + 0.006*"tax" + 0.006*"indian" + 0.006*"governor" + 0.005*"responsible" + 0.005*"fool" + 0.005*"management" + 0.005*"appear" + 0.005*"passenger" + 0.005*"surprise" + 0.005*"covidiot" + 0.005*"conversation" + 0.005*"example" + 0.005*"definitely" + 0.004*"direct" + 0.004*"actual" + 0.004*"maga" + 0.004*"evil" + 0.004*"complain" + 0.004*"arrest" + 0.004*"stinky_savior" + 0.003*"couple" + 0.003*"pack" + 0.003*"proud" + 0.003*"suck" + 0.003*"view"')
(2, '0.487*"covid" + 0.052*"test" + 0.043*"day" + 0.034*"positive" + 0.034*"state" + 0.030*"update" + 0.017*"rise" + 0.016*"testing" + 0.015*"high" + 0.013*"right" + 0.012*"read" + 0.009*"next" + 0.007*"soon" + 0.007*"hour" + 0.006*"force" + 0.005*"th" + 0.005*"deal" + 0.005*"lakh" + 0.004*"science" + 0.004*"mark" + 0.003*"trust" + 0.003*"alone" + 0.003*"single" + 0.003*"employee" + 0.003*"conduct" + 0.003*"clear" + 0.003*"sewage" + 0.003*"count" + 0.003*"park" + 0.002*"production" + 0.002*"death_toll" + 0.002*"adequate" + 0.002*"auspol" + 0.002*"sept" + 0.001*"covi" + 0.001*"fatality" + 0.001*"tourist" + 0.001*"simply" + 0.001*"tally" + 0.001*"alert" + 0.001*"register" + 0.001*"triple" + 0.001*"priority" + 0.001*"later" + 0.001*"bengaluru" + 0.001*"perform" + 0.001*"coro" + 0.001*"please" + 0.001*"reinfection" + 0.001*"crosse"')
(3, '0.148*"death" + 0.069*"amp" + 0.055*"number" + 0.042*"late" + 0.029*"reopen" + 0.028*"infection" + 0.022*"run" + 0.020*"travel" + 0.020*"already" + 0.017*"seem" + 0.014*"almost" + 0.012*"list" + 0.012*"thread" + 0.011*"leader" + 0.010*"available" + 0.009*"center" + 0.009*"operation" + 0.008*"asymptomatic" + 0.008*"wrong" + 0.008*"beat" + 0.008*"different" + 0.007*"matter" + 0.006*"access" + 0.006*"headline" + 0.006*"easy" + 0.006*"battle" + 0.006*"sound" + 0.006*"launch" + 0.005*"refuse" + 0.005*"individual" + 0.005*"statistic" + 0.005*"retweet" + 0.005*"vacation" + 0.005*"dangerous" + 0.004*"brother" + 0.004*"town" + 0.004*"corona" + 0.004*"brain" + 0.004*"officer" + 0.004*"general" + 0.004*"voluntary" + 0.004*"frontline_worker" + 0.004*"subscribe" + 0.003*"traveler" + 0.003*"sa" + 0.003*"attention" + 0.003*"sell" + 0.003*"dog" + 0.003*"location" + 0.003*"abo"')
(4, '0.316*"case" + 0.156*"coronavirus" + 0.131*"new" + 0.058*"report" + 0.029*"first" + 0.017*"hospital" + 0.016*"recovery" + 0.012*"quarantine" + 0.010*"away" + 0.009*"supply" + 0.008*"announce" + 0.006*"line" + 0.006*"staff" + 0.005*"law" + 0.005*"stand" + 0.005*"note" + 0.004*"admit" + 0.004*"worldwide" + 0.004*"healthcare_worker" + 0.004*"ass" + 0.004*"fake" + 0.003*"york_time" + 0.003*"notice" + 0.003*"college_town" + 0.003*"trend_sep" + 0.003*"past_hour" + 0.003*"district" + 0.003*"regional" + 0.002*"delhi" + 0.002*"village" + 0.002*"strike" + 0.002*"file" + 0.002*"ipswich_hospital" + 0.002*"database" + 0.002*"days_stat" + 0.001*"grade" + 0.001*"donald_tr" + 0.001*"shirish" + 0.001*"web" + 0.001*"assistance" + 0.001*"writer" + 0.001*"exempt" + 0.001*"conspiracy" + 0.001*"representative" + 0.001*"pandem" + 0.001*"gov_admit" + 0.001*"saudi_arabia" + 0.001*"middle_class" + 0.001*"verge" + 0.001*"wyoming"')
(5, '0.065*"mask" + 0.062*"make" + 0.046*"lockdown" + 0.033*"tell" + 0.027*"strategy" + 0.020*"doctor" + 0.018*"hard" + 0.017*"expert" + 0.016*"learn" + 0.016*"shutdown" + 0.014*"transmission" + 0.013*"point" + 0.013*"effective" + 0.013*"police" + 0.013*"social_distance" + 0.012*"researcher" + 0.012*"hoax" + 0.012*"demand" + 0.012*"fear" + 0.010*"cost" + 0.010*"guideline" + 0.009*"employer" + 0.009*"avoid" + 0.009*"air" + 0.008*"seriously" + 0.008*"instead" + 0.008*"education" + 0.007*"campus" + 0.007*"condition" + 0.007*"remain" + 0.007*"jump" + 0.006*"throw" + 0.006*"walk" + 0.006*"idea" + 0.006*"current" + 0.006*"advise" + 0.006*"attend" + 0.006*"bit" + 0.005*"victorian" + 0.005*"essential" + 0.005*"possibly" + 0.005*"wedding" + 0.005*"statement" + 0.005*"goal" + 0.005*"nurse" + 0.004*"sense" + 0.004*"staysafe" + 0.004*"introduce" + 0.004*"unofficial" + 0.004*"enjoy"')
(6, '0.088*"total" + 0.066*"today" + 0.050*"good" + 0.050*"country" + 0.036*"really" + 0.033*"lead" + 0.031*"recover" + 0.030*"stat" + 0.027*"daily" + 0.025*"job" + 0.020*"big" + 0.018*"official" + 0.017*"bring" + 0.014*"reach" + 0.013*"game" + 0.011*"second" + 0.011*"other" + 0.010*"course" + 0.009*"age" + 0.008*"united_state" + 0.008*"action" + 0.007*"average" + 0.007*"labor_day" + 0.007*"epidemic" + 0.007*"decline" + 0.006*"forecast_predict" + 0.006*"sir" + 0.006*"mental_health" + 0.006*"present" + 0.006*"sit" + 0.006*"else" + 0.006*"success" + 0.005*"amazing" + 0.005*"complete" + 0.005*"andrew" + 0.004*"pe" + 0.004*"cop" + 0.004*"identify" + 0.004*"region" + 0.004*"secondwave" + 0.003*"around" + 0.003*"dumb" + 0.003*"corrupt" + 0.003*"shame" + 0.003*"winter" + 0.003*"concert" + 0.003*"manufacture" + 0.003*"probable" + 0.002*"rank" + 0.002*"mountain"')
(7, '0.096*"pandemic" + 0.066*"die" + 0.053*"health" + 0.043*"live" + 0.038*"come" + 0.033*"worker" + 0.030*"change" + 0.018*"city" + 0.017*"become" + 0.015*"concern" + 0.013*"parent" + 0.013*"control" + 0.012*"extend" + 0.012*"viewer" + 0.012*"disease" + 0.011*"protocol" + 0.011*"normal" + 0.011*"develop" + 0.009*"treatment" + 0.009*"together" + 0.009*"fact" + 0.008*"stage" + 0.008*"several" + 0.008*"probably" + 0.008*"struggle" + 0.007*"simple" + 0.007*"step" + 0.006*"measure" + 0.006*"suggest" + 0.006*"photo" + 0.006*"contact_trace" + 0.005*"department" + 0.005*"technology" + 0.005*"local" + 0.005*"floridian" + 0.005*"beach" + 0.005*"blunder" + 0.005*"survey" + 0.005*"fatal_math" + 0.004*"xe" + 0.004*"experts_cause" + 0.004*"strict" + 0.004*"sex" + 0.004*"seek" + 0.004*"urge" + 0.004*"melbourne" + 0.004*"nearly" + 0.004*"brilliant_marketing" + 0.003*"totally" + 0.003*"amount"')
(8, '0.162*"confirm" + 0.119*"last" + 0.052*"week" + 0.038*"trend_sep" + 0.028*"restriction" + 0.021*"resume" + 0.021*"post" + 0.020*"postpone" + 0.018*"research" + 0.017*"days_stat" + 0.016*"move" + 0.013*"soar" + 0.011*"donaldjtrumpjr" + 0.010*"funny" + 0.009*"pressure" + 0.008*"overall" + 0.008*"past" + 0.007*"position" + 0.007*"strain" + 0.007*"church" + 0.005*"lag" + 0.005*"johns_hopkin" + 0.005*"currently" + 0.005*"film" + 0.005*"obsess" + 0.005*"lost_control" + 0.004*"straw" + 0.004*"fix" + 0.004*"ad" + 0.003*"experiment" + 0.003*"south_wale" + 0.003*"domestic" + 0.003*"customer" + 0.003*"size" + 0.003*"daddy" + 0.003*"hrs" + 0.003*"politicize" + 0.003*"temporarily" + 0.003*"rooker_detail" + 0.003*"verify" + 0.003*"grant" + 0.003*"minute" + 0.003*"forward" + 0.003*"yo" + 0.003*"encourage" + 0.002*"user" + 0.002*"playoff" + 0.002*"updates_globally" + 0.002*"fox" + 0.002*"zoom"')
(9, '0.154*"people" + 0.043*"help" + 0.041*"back" + 0.039*"face" + 0.030*"much" + 0.029*"wear" + 0.021*"safe" + 0.016*"do" + 0.014*"human" + 0.013*"man" + 0.012*"flu" + 0.011*"yet" + 0.011*"co" + 0.010*"sad" + 0.010*"shut" + 0.010*"affect" + 0.009*"deadly" + 0.009*"oil" + 0.008*"fast" + 0.008*"county" + 0.008*"mind" + 0.008*"little" + 0.007*"status" + 0.006*"lack" + 0.006*"wh" + 0.006*"failure" + 0.006*"sport" + 0.005*"hero" + 0.005*"idiot" + 0.005*"trade" + 0.005*"vaccinate" + 0.004*"earn" + 0.004*"joke" + 0.004*"none" + 0.004*"budget" + 0.004*"fun" + 0.004*"rather" + 0.004*"mother" + 0.004*"deserve" + 0.004*"memory" + 0.004*"charge" + 0.004*"family_letter" + 0.004*"highlight" + 0.003*"anymore" + 0.003*"picture" + 0.003*"bitch" + 0.003*"apparently" + 0.003*"violence" + 0.003*"correct" + 0.003*"donation"')
(10, '0.121*"time" + 0.087*"record" + 0.043*"realdonaldtrump" + 0.038*"patient" + 0.034*"kill" + 0.026*"link" + 0.022*"community" + 0.022*"situation" + 0.019*"push" + 0.018*"sure" + 0.016*"trend" + 0.014*"play" + 0.013*"page" + 0.012*"citizen" + 0.012*"gossip" + 0.010*"last_hour" + 0.010*"fresh" + 0.010*"politic" + 0.008*"forever" + 0.008*"combat" + 0.007*"yesterday" + 0.007*"form" + 0.006*"bank" + 0.006*"partner" + 0.006*"wave" + 0.006*"golf" + 0.006*"misinformation" + 0.006*"requirement" + 0.005*"theory" + 0.005*"maine_wedding" + 0.005*"review" + 0.005*"typical" + 0.005*"scott_morrison" + 0.004*"plague" + 0.004*"twitter" + 0.004*"face_bleak" + 0.004*"takes_toll" + 0.004*"describe" + 0.003*"fill" + 0.003*"instance" + 0.003*"perhaps" + 0.003*"chennai" + 0.003*"awareness" + 0.003*"discharge" + 0.003*"diabetes" + 0.003*"everyday" + 0.003*"lowest" + 0.003*"common" + 0.003*"thug" + 0.003*"flood"')
(11, '0.042*"work" + 0.031*"well" + 0.030*"still" + 0.023*"thing" + 0.020*"give" + 0.020*"business" + 0.020*"family" + 0.020*"call" + 0.019*"also" + 0.017*"increase" + 0.017*"economy" + 0.017*"thank" + 0.016*"continue" + 0.016*"impact" + 0.015*"crisis" + 0.013*"place" + 0.012*"free" + 0.011*"real" + 0.011*"track" + 0.010*"woman" + 0.010*"watch" + 0.010*"safety" + 0.010*"include" + 0.010*"fund" + 0.008*"medical" + 0.008*"friend" + 0.007*"govt" + 0.007*"challenge" + 0.007*"young" + 0.006*"blame" + 0.006*"additional" + 0.006*"head" + 0.006*"level" + 0.006*"season" + 0.006*"australian" + 0.006*"likely" + 0.006*"history" + 0.005*"summer" + 0.005*"cover" + 0.005*"effect" + 0.005*"mistake" + 0.005*"wish" + 0.005*"toll" + 0.005*"huge" + 0.004*"climate" + 0.004*"old" + 0.004*"exactly" + 0.004*"book" + 0.004*"slow" + 0.004*"source"')
(12, '0.136*"say" + 0.035*"even" + 0.026*"pos" + 0.026*"outbreak" + 0.024*"end" + 0.022*"election" + 0.022*"mean" + 0.021*"never" + 0.019*"article" + 0.016*"protect" + 0.015*"vote" + 0.015*"top" + 0.013*"lot" + 0.012*"receive" + 0.011*"nation" + 0.011*"least" + 0.011*"team" + 0.010*"video" + 0.010*"ahead" + 0.009*"member" + 0.007*"drug" + 0.007*"publish" + 0.007*"price" + 0.007*"approve" + 0.006*"major" + 0.006*"stupid" + 0.006*"threat" + 0.006*"miss" + 0.006*"cope" + 0.006*"require" + 0.005*"digital" + 0.005*"negative" + 0.005*"player" + 0.005*"info" + 0.004*"mail" + 0.004*"gdp" + 0.004*"growth" + 0.004*"lock" + 0.004*"interview" + 0.004*"reuter" + 0.004*"touch" + 0.004*"choose" + 0.004*"cov" + 0.004*"promise" + 0.004*"interested" + 0.004*"million" + 0.004*"house" + 0.004*"funding" + 0.004*"court" + 0.004*"recommend"')
(13, '0.061*"need" + 0.057*"school" + 0.040*"home" + 0.032*"close" + 0.030*"let" + 0.026*"potential" + 0.019*"put" + 0.019*"fall" + 0.018*"hit" + 0.018*"hear" + 0.016*"enough" + 0.016*"market" + 0.015*"kid" + 0.013*"love" + 0.012*"provide" + 0.011*"population" + 0.009*"decision" + 0.008*"reason" + 0.008*"panic" + 0.008*"win" + 0.008*"discuss" + 0.008*"sometimes" + 0.008*"full" + 0.007*"drive" + 0.007*"save" + 0.007*"model" + 0.007*"bubble" + 0.007*"podcast" + 0.006*"diagnose" + 0.006*"practice" + 0.006*"boy" + 0.006*"night" + 0.006*"loss" + 0.006*"self" + 0.006*"odd" + 0.005*"regard" + 0.005*"donate" + 0.005*"distance" + 0.005*"limit" + 0.005*"third" + 0.005*"send" + 0.005*"tie" + 0.005*"private" + 0.004*"side_effect" + 0.004*"opening" + 0.004*"fiscal" + 0.004*"ruin" + 0.004*"entire" + 0.004*"episode" + 0.004*"stuff"')
(14, '0.043*"plan" + 0.038*"global" + 0.030*"follow" + 0.024*"service" + 0.023*"create" + 0.023*"child" + 0.023*"date" + 0.022*"rate" + 0.017*"try" + 0.016*"important" + 0.015*"federal" + 0.014*"drop" + 0.014*"question" + 0.013*"information" + 0.012*"class" + 0.011*"fail" + 0.011*"economic" + 0.011*"word" + 0.011*"national" + 0.011*"maybe" + 0.010*"catch" + 0.010*"program" + 0.009*"wonder" + 0.008*"body" + 0.008*"pass" + 0.008*"hate" + 0.008*"trial" + 0.008*"progress" + 0.008*"cut" + 0.006*"unicef" + 0.006*"administration" + 0.006*"buy" + 0.006*"hardly" + 0.006*"raise" + 0.006*"small" + 0.006*"unemployment" + 0.005*"focus" + 0.005*"manage" + 0.005*"former" + 0.005*"blog" + 0.005*"survive" + 0.005*"positivity_rate" + 0.005*"relief" + 0.004*"protection" + 0.004*"wake" + 0.004*"website" + 0.004*"contract" + 0.004*"afraid" + 0.004*"household" + 0.004*"type"')
(15, '0.093*"trump" + 0.041*"virus" + 0.040*"look" + 0.038*"bad" + 0.025*"cause" + 0.025*"dead" + 0.021*"happen" + 0.019*"story" + 0.019*"share" + 0.017*"add" + 0.016*"pm" + 0.015*"issue" + 0.015*"office" + 0.014*"key" + 0.013*"claim" + 0.012*"spike" + 0.011*"lesson" + 0.011*"improve" + 0.011*"protest" + 0.010*"surpass" + 0.009*"heart" + 0.009*"ready" + 0.008*"leadership" + 0.008*"train" + 0.008*"gathering" + 0.007*"poor" + 0.007*"political" + 0.007*"loan" + 0.007*"false" + 0.006*"campaign" + 0.006*"victim" + 0.006*"death_certificate" + 0.006*"riot" + 0.005*"online_learne" + 0.005*"stimulus" + 0.005*"pick" + 0.005*"shortage" + 0.005*"green" + 0.005*"professional" + 0.004*"reminder" + 0.004*"candle" + 0.004*"car" + 0.004*"fly" + 0.004*"meeting" + 0.004*"rally" + 0.004*"message" + 0.004*"shameful" + 0.004*"bear" + 0.004*"white" + 0.003*"process"')
(16, '0.068*"due" + 0.065*"government" + 0.036*"active" + 0.036*"download" + 0.036*"spread" + 0.034*"stop" + 0.030*"keep" + 0.024*"datum" + 0.022*"medium" + 0.020*"contain" + 0.018*"ever" + 0.018*"remember" + 0.013*"party" + 0.012*"reveal" + 0.011*"join" + 0.010*"actually" + 0.010*"base" + 0.010*"future" + 0.008*"war" + 0.008*"percent" + 0.007*"handle" + 0.007*"credit" + 0.007*"strong" + 0.007*"exist" + 0.006*"metro_service" + 0.006*"income" + 0.006*"resident" + 0.006*"petition" + 0.006*"girl" + 0.006*"cross" + 0.006*"attack" + 0.005*"poll" + 0.005*"cancel_student" + 0.005*"unable" + 0.005*"live_update" + 0.004*"taste" + 0.004*"bulletin" + 0.004*"brilliant" + 0.004*"prepare" + 0.004*"deliver" + 0.004*"disappear" + 0.004*"waste" + 0.004*"dear_viewer" + 0.004*"western" + 0.004*"estimate" + 0.003*"tomorrow" + 0.003*"celebrate" + 0.003*"movie" + 0.003*"smell" + 0.003*"hyderabad"')
(17, '0.147*"vaccine" + 0.066*"know" + 0.033*"show" + 0.033*"find" + 0.025*"start" + 0.021*"use" + 0.020*"early" + 0.019*"leave" + 0.017*"response" + 0.014*"sign" + 0.014*"begin" + 0.011*"scientist" + 0.011*"analysis" + 0.010*"candidate" + 0.009*"guess" + 0.009*"less" + 0.009*"possible" + 0.009*"name" + 0.008*"always" + 0.008*"able" + 0.007*"group" + 0.007*"hand" + 0.006*"chinese" + 0.006*"kind" + 0.006*"oppression" + 0.006*"cure" + 0.006*"south_korean" + 0.006*"leaders_urge" + 0.005*"blood" + 0.005*"offer" + 0.005*"bar" + 0.005*"however" + 0.005*"unlock" + 0.005*"novel" + 0.005*"produce" + 0.005*"mild" + 0.005*"suicide" + 0.005*"boost" + 0.005*"tip" + 0.004*"damage" + 0.004*"map" + 0.004*"com" + 0.004*"pull" + 0.004*"rock" + 0.004*"fire" + 0.004*"doubt" + 0.004*"term" + 0.003*"network" + 0.003*"aid" + 0.003*"stress"')
(18, '0.104*"go" + 0.052*"see" + 0.051*"many" + 0.040*"month" + 0.040*"want" + 0.029*"life" + 0.020*"lose" + 0.020*"open" + 0.016*"person" + 0.016*"risk" + 0.015*"check" + 0.015*"long" + 0.014*"break" + 0.014*"ask" + 0.014*"fight" + 0.013*"worry" + 0.013*"surge" + 0.012*"infect" + 0.011*"far" + 0.010*"weekend" + 0.010*"accord" + 0.008*"true" + 0.008*"system" + 0.007*"delay" + 0.007*"speak" + 0.007*"area" + 0.007*"grow" + 0.007*"shit" + 0.006*"visit" + 0.006*"test_kit" + 0.006*"teacher" + 0.006*"compare" + 0.006*"project" + 0.006*"allow" + 0.005*"cancel" + 0.005*"treat" + 0.005*"half" + 0.005*"industry" + 0.005*"exceed" + 0.005*"site" + 0.004*"export" + 0.004*"predict" + 0.004*"detail" + 0.004*"answer" + 0.004*"moment" + 0.004*"trace" + 0.004*"folk" + 0.004*"era" + 0.003*"suppose" + 0.003*"truth"')
(19, '0.074*"take" + 0.067*"world" + 0.035*"great" + 0.030*"care" + 0.025*"support" + 0.017*"hope" + 0.017*"study" + 0.015*"set" + 0.014*"stock_market" + 0.014*"money" + 0.014*"tweet" + 0.014*"understand" + 0.013*"wait" + 0.012*"company" + 0.010*"policy" + 0.010*"educate_talk" + 0.010*"hello_co" + 0.010*"effort" + 0.010*"suffer" + 0.009*"online" + 0.009*"evidence" + 0.009*"relate" + 0.009*"problem" + 0.008*"remote" + 0.008*"morning" + 0.008*"release" + 0.008*"symptom" + 0.007*"agree" + 0.007*"fine" + 0.006*"mount" + 0.006*"prevent" + 0.006*"interesting" + 0.006*"sucker" + 0.006*"international" + 0.005*"emerge" + 0.005*"daniel_andrew" + 0.005*"resource" + 0.005*"final" + 0.005*"expose" + 0.005*"damn" + 0.005*"president" + 0.005*"ensure" + 0.005*"pray" + 0.004*"consider" + 0.004*"tech" + 0.004*"precaution" + 0.004*"click" + 0.004*"stigma" + 0.004*"curve" + 0.004*"chief"')

In [ ]:
# Visualize the topics
import pyLDAvis.gensim
#import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

vis = pyLDAvis.gensim.prepare(lda_model, corpus, id2word)
vis

/usr/local/lib/python3.7/dist-packages/past/types/oldstr.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
/usr/local/lib/python3.7/dist-packages/pyLDAvis/_prepare.py:232: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  head(R).drop('saliency', 1)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2     -0.419772  0.099648       1        1  10.394471
11    -0.073429 -0.415107       2        1   7.378781
4     -0.040852  0.027444       3        1   6.528569
18    -0.018938 -0.014618       4        1   6.092853
12     0.022138  0.019429       5        1   4.944869
3      0.023005  0.016846       6        1   4.914258
7      0.008746 -0.008724       7        1   4.900220
19     0.012027  0.010083       8        1   4.853266
17     0.010580  0.013499       9        1   4.795449
0      0.036529  0.023238      10        1   4.686930
9      0.039458  0.012830      11        1   4.683331
15     0.041419  0.021055      12        1   4.477242
13     0.038851  0.020857      13        1   4.438821
1      0.037674  0.024291      14        1   4.385196
14     0.033280  0.021632      15        1   4.367525
5      0.049171  0.021977      16        1   4.202023
16     0.042730  0.021997      17        1   3.987820
6      0.037225  0.023594      18        1   3.966856
10     0.058528  0.026904      19        1   3.421439
8      0.061629  0.033125      20        1   2.580081, topic_info=               Term          Freq         Total Category  logprob  loglift
26            covid  45437.000000  45437.000000  Default  30.0000  30.0000
25             case  18518.000000  18518.000000  Default  29.0000  29.0000
73      coronavirus   9130.000000   9130.000000  Default  28.0000  28.0000
74              new   7666.000000   7666.000000  Default  27.0000  27.0000
57           people   6492.000000   6492.000000  Default  26.0000  26.0000
...             ...           ...           ...      ...      ...      ...
8711           size     70.826796     71.747709  Topic20  -5.7908   3.6444
21664         straw     96.595508    100.830849  Topic20  -5.4805   3.6144
21435  lost_control    106.977541    114.328729  Topic20  -5.3784   3.5909
38        trend_sep    885.050472   2155.385873  Topic20  -3.2654   2.7673
264       days_stat    391.304050   1176.930060  Topic20  -4.0815   2.5562

[635 rows x 6 columns], token_table=      Topic      Freq       Term
term
846       9  0.997676       able
3324      6  0.998108     access
92        4  0.997412     accord
2344     10  0.998477        act
613      18  0.996670     action
...     ...       ...        ...
317      14  0.999700       year
2457     19  0.993929  yesterday
3462     11  0.998031        yet
2956      3  0.992734  york_time
586       2  0.998514      young

[644 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 12, 5, 19, 13, 4, 8, 20, 18, 1, 10, 16, 14, 2, 15, 6, 17, 7, 11, 9])

In [ ]:
pyLDAvis.save_html(vis, '2020_lda.html')

In [ ]:
!unzip "/content/mallet-2.0.8.zip"

In [ ]:
mallet_path = '/content/mallet-2.0.8/bin/mallet' # update this path
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, 
                                             corpus=corpus, 
                                             num_topics=20,
                                             id2word=id2word,
                                             iterations=1000,
                                             optimize_interval=10)

/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/smart_open/smart_open_lib.py:494: DeprecationWarning: This function is deprecated.  See https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst for more information
  warnings.warn(message, category=DeprecationWarning)

In [ ]:
pprint(ldamallet.show_topics(num_topics=20,num_words=100,formatted=False))

# Compute Coherence Score
coherence_model_ldamallet = CoherenceModel(model=ldamallet, texts=data_lemmatized, dictionary=id2word, coherence='c_v')
coherence_ldamallet = coherence_model_ldamallet.get_coherence()

print('\n Coherence Score: ', round(coherence_ldamallet, 2))

[(0,
  [('amp', 0.10911680911680911),
   ('job', 0.02773892773892774),
   ('home', 0.02584822584822585),
   ('change', 0.024294224294224294),
   ('lie', 0.022584822584822584),
   ('stay', 0.021756021756021756),
   ('love', 0.016524216524216526),
   ('lose', 0.016083916083916083),
   ('time', 0.015591815591815592),
   ('due', 0.013752913752913752),
   ('nation', 0.0114996114996115),
   ('hear', 0.010463610463610464),
   ('big', 0.010282310282310282),
   ('food', 0.009867909867909868),
   ('family', 0.009634809634809635),
   ('air', 0.009194509194509195),
   ('safe', 0.00909090909090909),
   ('season', 0.009013209013209013),
   ('football', 0.008650608650608651),
   ('lack', 0.008547008547008548),
   ('truth', 0.008495208495208495),
   ('order', 0.008262108262108263),
   ('law', 0.00821030821030821),
   ('listen', 0.0077182077182077185),
   ('speak', 0.007381507381507382),
   ('buy', 0.007070707070707071),
   ('thing', 0.006915306915306916),
   ('expose', 0.006785806785806786),
   ('include', 0.006526806526806527),
   ('governor', 0.006500906500906501),
   ('gossip', 0.0062678062678062675),
   ('american', 0.005982905982905983),
   ('app', 0.005931105931105931),
   ('strong', 0.00562030562030562),
   ('black', 0.005309505309505309),
   ('absolutely', 0.005231805231805232),
   ('bit', 0.004921004921004921),
   ('line', 0.004765604765604766),
   ('stay_safe', 0.00473970473970474),
   ('hope', 0.004480704480704481),
   ('damn', 0.004377104377104377),
   ('responsible', 0.004144004144004144),
   ('program', 0.004066304066304066),
   ('realdonaldtrump', 0.004066304066304066),
   ('full', 0.003962703962703963),
   ('deny', 0.0039368039368039365),
   ('clean', 0.0038073038073038073),
   ('blow', 0.0038073038073038073),
   ('essential', 0.003651903651903652),
   ('income', 0.0034706034706034707),
   ('labor', 0.003418803418803419),
   ('roll', 0.003418803418803419),
   ('waste', 0.003418803418803419),
   ('fool', 0.003392903392903393),
   ('million', 0.003367003367003367),
   ('threaten', 0.0033152033152033153),
   ('mother', 0.0032634032634032634),
   ('great', 0.0031339031339031338),
   ('criminal', 0.003108003108003108),
   ('corruption', 0.0030821030821030822),
   ('direct', 0.0030821030821030822),
   ('bar', 0.0029526029526029526),
   ('brother', 0.002874902874902875),
   ('plague', 0.002823102823102823),
   ('radio', 0.0027713027713027714),
   ('liar', 0.0027454027454027453),
   ('narrative', 0.0027454027454027453),
   ('encourage', 0.0027195027195027195),
   ('wash_hand', 0.0026677026677026676),
   ('fit', 0.002615902615902616),
   ('proof', 0.002615902615902616),
   ('wit', 0.002615902615902616),
   ('stick', 0.0024605024605024606),
   ('prevention', 0.0024346024346024345),
   ('download', 0.0024087024087024087),
   ('weather', 0.002382802382802383),
   ('sister', 0.0023051023051023052),
   ('consumer', 0.002279202279202279),
   ('draw', 0.002279202279202279),
   ('unable', 0.0022015022015022014),
   ('surprise', 0.0022015022015022014),
   ('press', 0.00214970214970215),
   ('briefing', 0.00214970214970215),
   ('site', 0.00214970214970215),
   ('brand', 0.002097902097902098),
   ('ticket', 0.002072002072002072),
   ('sort', 0.00202020202020202),
   ('refund', 0.00202020202020202),
   ('afford', 0.0019943019943019944),
   ('sc', 0.0019684019684019683),
   ('ability', 0.0019425019425019425),
   ('webinar', 0.0019425019425019425),
   ('staysafe', 0.0019166019166019165),
   ('song', 0.0018907018907018908),
   ('load', 0.0018907018907018908),
   ('awful', 0.0018907018907018908),
   ('occur', 0.0018648018648018648),
   ('cry', 0.0018648018648018648),
   ('invest', 0.0018648018648018648),
   ('agenda', 0.0018389018389018388)]),
 (1,
  [('life', 0.030779071254957144),
   ('give', 0.029295126007419726),
   ('long', 0.02128693872329538),
   ('story', 0.019393629269540743),
   ('video', 0.01936804400665217),
   ('feel', 0.018395804016886272),
   ('family', 0.018319048228220544),
   ('friend', 0.015811692465140078),
   ('real', 0.015095305104259946),
   ('problem', 0.012767046181399514),
   ('tweet', 0.012485608289625177),
   ('time', 0.011513368299859281),
   ('hold', 0.011411027248304976),
   ('save', 0.010950492516310605),
   ('comment', 0.010669054624536267),
   ('experience', 0.01064346936164769),
   ('watch', 0.009620058846104644),
   ('lose', 0.0086989893821159),
   ('remember', 0.008136113598567226),
   ('human', 0.008059357809901496),
   ('battle', 0.007905846232570039),
   ('shit', 0.007803505181015735),
   ('sense', 0.007163873608801331),
   ('night', 0.006856850454138416),
   ('head', 0.006345145196366892),
   ('sad', 0.006319559933478316),
   ('channel', 0.006242804144812588),
   ('idea', 0.006191633619035436),
   ('critical', 0.005935780990149674),
   ('make', 0.005654343098375336),
   ('reminder', 0.0056287578354867595),
   ('loss', 0.005526416783932455),
   ('restaurant', 0.0052705641550466935),
   ('kind', 0.005244978892158117),
   ('water', 0.005040296789049508),
   ('distance', 0.0050147115261609315),
   ('piece', 0.0048867852117180505),
   ('folk', 0.004784444160163746),
   ('contract', 0.0047588588972751695),
   ('sound', 0.004733273634386593),
   ('remove', 0.00455417679416656),
   ('matter', 0.00455417679416656),
   ('crowd', 0.00455417679416656),
   ('thought', 0.00455417679416656),
   ('request', 0.004426250479723679),
   ('hell', 0.004426250479723679),
   ('hate', 0.00434949469105795),
   ('finally', 0.00434949469105795),
   ('issue', 0.004323909428169375),
   ('ago', 0.004298324165280799),
   ('meet', 0.0042727389023922225),
   ('attention', 0.003991301010617884),
   ('stress', 0.003940130484840732),
   ('holiday', 0.003863374696175003),
   ('busy', 0.003837789433286427),
   ('opinion', 0.00368427785595497),
   ('amazing', 0.003505181015734937),
   ('anxiety', 0.003505181015734937),
   ('realize', 0.003505181015734937),
   ('fall', 0.0034795957528463606),
   ('club', 0.0034540104899577844),
   ('bullshit', 0.003428425227069208),
   ('movie', 0.003377254701292056),
   ('ass', 0.0033260841755149034),
   ('need_youtube', 0.0032237431239605986),
   ('views_likes', 0.0032237431239605986),
   ('video_promotion', 0.0032237431239605986),
   ('mess', 0.0032237431239605986),
   ('hurt', 0.0032237431239605986),
   ('add_subscriber', 0.0031981578610720224),
   ('mind', 0.003172572598183446),
   ('drink', 0.00314698733529487),
   ('journalist', 0.003121402072406294),
   ('spot', 0.003095816809517718),
   ('pull', 0.0030702315466291418),
   ('deep', 0.0030702315466291418),
   ('taste', 0.0030190610208519894),
   ('volunteer', 0.002993475757963413),
   ('perfect', 0.0028911347064091084),
   ('twitter', 0.0028911347064091084),
   ('burn', 0.0027887936548548035),
   ('wife', 0.0027887936548548035),
   ('status', 0.0027632083919662273),
   ('smell', 0.0027632083919662273),
   ('speak', 0.0027632083919662273),
   ('youtube', 0.0026864526033004987),
   ('discussion', 0.0026352820775233468),
   ('defeat', 0.0025841115517461944),
   ('hear', 0.0025073557630804657),
   ('daughter', 0.0024817705001918895),
   ('proud', 0.0024817705001918895),
   ('beautiful', 0.002430599974414737),
   ('board', 0.002430599974414737),
   ('reflect', 0.0023538441857490085),
   ('afraid', 0.0023282589228604323),
   ('describe', 0.002302673659971856),
   ('suck', 0.002302673659971856),
   ('guess', 0.0022515031341947037),
   ('perform', 0.0022515031341947037),
   ('colleague', 0.0022259178713061275)]),
 (2,
  [('lockdown', 0.05288633918967372),
   ('continue', 0.030374430159299286),
   ('follow', 0.028632894534651437),
   ('hit', 0.022307022486298213),
   ('restriction', 0.021436254673974288),
   ('travel', 0.019131281053116837),
   ('weekend', 0.018875172873021564),
   ('hard', 0.018798340418992983),
   ('place', 0.017517799518516623),
   ('city', 0.01669825334221175),
   ('free', 0.016006761255954516),
   ('put', 0.015955539619935462),
   ('coronavirus', 0.015878707165906877),
   ('safety', 0.015827485529887823),
   ('leader', 0.015520155713773498),
   ('post', 0.014470112175382882),
   ('measure', 0.013701787635097065),
   ('protest', 0.013599344363058955),
   ('fall', 0.012472468370639759),
   ('extend', 0.01244685755263023),
   ('remain', 0.010935819290068125),
   ('cost', 0.01060287865594427),
   ('guideline', 0.008656456487220202),
   ('resident', 0.008502791579163038),
   ('safe', 0.008169850945039185),
   ('two_week', 0.007760077856886749),
   ('major', 0.007529580494801004),
   ('stage', 0.006991753316600932),
   ('survive', 0.006966142498591405),
   ('fine', 0.0065819802284484965),
   ('local', 0.0065307585924294425),
   ('summer', 0.0065307585924294425),
   ('aid', 0.006249039594324643),
   ('wait', 0.005941709778210316),
   ('anti', 0.005762434052143626),
   ('ensure', 0.005557547508067408),
   ('humanity', 0.00553193669005788),
   ('amount', 0.005378271782000717),
   ('employer', 0.0052246068739435535),
   ('authority', 0.0051477744199149725),
   ('ease', 0.004686779695743482),
   ('alert', 0.0046099472417149),
   ('town', 0.004584336423705373),
   ('notice', 0.004379449879629156),
   ('throw', 0.004353839061619628),
   ('protocol', 0.004225784971571992),
   ('action', 0.004072120063514829),
   ('car', 0.004046509245505301),
   ('set', 0.003892844337448138),
   ('strict', 0.003764790247400502),
   ('charge', 0.0037391794293909746),
   ('long', 0.0036111253393433388),
   ('maintain', 0.003431849613276648),
   ('tip', 0.0033806279772575936),
   ('guide', 0.0032781847052194848),
   ('covid', 0.0032781847052194848),
   ('protester', 0.0032269630692004303),
   ('melbourne', 0.003201352251190903),
   ('decrease', 0.003175741433181376),
   ('ahead', 0.0031245197971623215),
   ('guardian', 0.0030220765251242126),
   ('customer', 0.002970854889105158),
   ('regulation', 0.0029452440710956308),
   ('herd_immunity', 0.002842800799057522),
   ('training', 0.0028171899810479945),
   ('full', 0.002740357527019413),
   ('meet', 0.0027147467090098856),
   ('hair', 0.002637914254981304),
   ('labor_day', 0.0026123034369717768),
   ('platform', 0.0026123034369717768),
   ('roadmap', 0.0025354709829431953),
   ('resign', 0.0025354709829431953),
   ('victorian', 0.0025354709829431953),
   ('andrew', 0.002509860164933668),
   ('raising_hope', 0.002484249346924141),
   ('australian', 0.0024586385289146135),
   ('location', 0.0024330277109050865),
   ('surely', 0.0024330277109050865),
   ('rent', 0.0022793628028479227),
   ('cash', 0.0022793628028479227),
   ('breach', 0.0022281411668288683),
   ('mayor', 0.0022281411668288683),
   ('daniel_andrew', 0.0022281411668288683),
   ('athlete', 0.0022281411668288683),
   ('prime_minister', 0.002176919530809814),
   ('series', 0.0021256978947907595),
   ('lift', 0.0021000870767812325),
   ('warning', 0.002048865440762178),
   ('doctor_went', 0.0020232546227526506),
   ('drive', 0.0019976438047431236),
   ('major_streaming', 0.0019976438047431236),
   ('top', 0.001946422168724069),
   ('tourist', 0.0019208113507145417),
   ('owner', 0.0019208113507145417),
   ('capital', 0.0018952005327050145),
   ('rt', 0.0018952005327050145),
   ('cop', 0.0018695897146954873),
   ('table', 0.0018183680786764329),
   ('melbourne_lockdown', 0.0017415356246478512),
   ('enforce', 0.001715924806638324)]),
 (3,
  [('covid', 0.1555250265688587),
   ('month', 0.03901086083102206),
   ('fight', 0.02579123357266907),
   ('find', 0.022006791259493508),
   ('work', 0.021929028746209077),
   ('due', 0.01848155732393271),
   ('part', 0.017781694704372845),
   ('vote', 0.01599315689883097),
   ('important', 0.013893569040151378),
   ('treatment', 0.013323310609398896),
   ('pm', 0.011819902019233261),
   ('money', 0.010757147671012728),
   ('receive', 0.009253739080847093),
   ('today', 0.009098214054278235),
   ('eat', 0.00839835143471837),
   ('raise', 0.008087301381580652),
   ('exam', 0.007983618030534746),
   ('conduct', 0.0076207263018740765),
   ('poor', 0.00751704295082817),
   ('stand', 0.007361517924259312),
   ('curve', 0.00723191373545193),
   ('issue', 0.006946784520075689),
   ('easy', 0.006635734466937972),
   ('unemployment', 0.006454288602607636),
   ('researcher', 0.006376526089323207),
   ('happy', 0.006117317711708443),
   ('flatten', 0.006039555198424013),
   ('guess', 0.0059099510096166305),
   ('financial', 0.005728505145286296),
   ('resume', 0.0054174550921485785),
   ('forget', 0.005210088390056766),
   ('touch', 0.005158246714533814),
   ('price', 0.004924959174680526),
   ('donate', 0.004873117499157573),
   ('healthcare', 0.00482127582363462),
   ('suppose', 0.004769434148111667),
   ('relate', 0.004717592472588714),
   ('worth', 0.004665750797065761),
   ('manage', 0.004613909121542808),
   ('mail', 0.00445838409497395),
   ('postpone', 0.00445838409497395),
   ('share', 0.004432463257212473),
   ('difficult', 0.004406542419450997),
   ('solution', 0.00438062158168952),
   ('four_month', 0.0042769382306436145),
   ('situation', 0.004043650690790326),
   ('shock', 0.00401772985302885),
   ('play', 0.003965888177505897),
   ('private', 0.003888125664221468),
   ('vitamin', 0.0038103631509370382),
   ('medicine', 0.0037844423131755617),
   ('paper', 0.003732600637652609),
   ('tv', 0.0035511547733222738),
   ('pledge', 0.003395629746753415),
   ('voice', 0.0033437880712304624),
   ('note', 0.0033437880712304624),
   ('shop', 0.0032141838824230797),
   ('fill', 0.0031882630446616036),
   ('multiple', 0.0031364213691386506),
   ('rich', 0.0031364213691386506),
   ('middle', 0.0030586588558542214),
   ('respond', 0.003032738018092745),
   ('light', 0.002980896342569792),
   ('disappear', 0.0029031338292853626),
   ('feed', 0.0027994504782394565),
   ('astrazeneca', 0.002695767127193551),
   ('projection', 0.0026698462894320743),
   ('housing', 0.0026180046139091216),
   ('fraud', 0.002592083776147645),
   ('sink', 0.0025661629383861686),
   ('schedule', 0.002514321262863216),
   ('nightmare', 0.0023328753985328806),
   ('alive', 0.002306954560771404),
   ('contribute', 0.002255112885248451),
   ('boat', 0.002229192047486975),
   ('philippine', 0.002125508696441069),
   ('illegal', 0.002125508696441069),
   ('boss', 0.002125508696441069),
   ('operation', 0.002021825345395163),
   ('nonsense', 0.0019959045076336866),
   ('nigerian', 0.0019959045076336866),
   ('voting', 0.0019959045076336866),
   ('wh', 0.0019181419943492574),
   ('golden_corral', 0.0019181419943492574),
   ('finish', 0.0018663003188263045),
   ('personnel', 0.0018144586433033515),
   ('study_find', 0.0017626169677803986),
   ('eat_buffet', 0.0017626169677803986),
   ('clinical', 0.0017366961300189223),
   ('admit', 0.0017366961300189223),
   ('first_batch', 0.0016330127789730164),
   ('team', 0.0016330127789730164),
   ('pre', 0.0016070919412115399),
   ('bet', 0.0015811711034500635),
   ('tank', 0.0015811711034500635),
   ('rip', 0.001555250265688587),
   ('clinic', 0.0015293294279271107),
   ('province', 0.0015293294279271107),
   ('neet', 0.0014256460768812048),
   ('manager', 0.0014256460768812048)]),
 (4,
  [('mask', 0.07094489817016437),
   ('spread', 0.04856301044143492),
   ('stop', 0.035692132740618214),
   ('face', 0.03352114132120335),
   ('wear', 0.02899824253075571),
   ('bad', 0.026051897032978392),
   ('covid', 0.015429546159412798),
   ('people', 0.014421585857541611),
   ('science', 0.013491160963506669),
   ('social_distance', 0.013439470691615838),
   ('event', 0.013206864468107102),
   ('challenge', 0.012043833350563424),
   ('fear', 0.010622350873565596),
   ('prevent', 0.010260518970329783),
   ('hand', 0.010234673834384369),
   ('avoid', 0.009898687067093973),
   ('situation', 0.009045797580895276),
   ('act', 0.008839036493331955),
   ('contact', 0.008425514318205313),
   ('play', 0.008425514318205313),
   ('limit', 0.008011992143078673),
   ('ignore', 0.00697818670526207),
   ('message', 0.00687480616148041),
   ('fast', 0.006668045073917089),
   ('refuse', 0.006668045073917089),
   ('half', 0.006409593714462938),
   ('policy', 0.0055825493642096555),
   ('walk', 0.005324098004755505),
   ('model', 0.005324098004755505),
   ('practice', 0.005272407732864675),
   ('hero', 0.005065646645301354),
   ('precaution', 0.004910575829628864),
   ('role', 0.004910575829628864),
   ('literally', 0.004574589062338468),
   ('wear_mask', 0.004471208518556808),
   ('disaster', 0.004367827974775147),
   ('address', 0.004316137702884317),
   ('remind', 0.004290292566938902),
   ('protection', 0.004161066887211827),
   ('important', 0.004135221751266412),
   ('close', 0.004083531479375581),
   ('doubt', 0.0040059960715393365),
   ('music', 0.003928460663703091),
   ('image', 0.00356662876046728),
   ('bus', 0.003489093352631035),
   ('picture', 0.003489093352631035),
   ('side', 0.0034115579447947897),
   ('mandatory', 0.003308177401013129),
   ('passenger', 0.003204796857231469),
   ('pressure', 0.003178951721286054),
   ('wale', 0.003178951721286054),
   ('recommend', 0.003127261449395224),
   ('treat', 0.0030755711775043936),
   ('secondwave', 0.0030755711775043936),
   ('sex', 0.0030497260415589785),
   ('indoor', 0.0030238809056135634),
   ('idea', 0.002713739274268583),
   ('offer', 0.0026103587304869224),
   ('save_live', 0.0025845135945415073),
   ('proper', 0.002532823322650677),
   ('assume', 0.002506978186705262),
   ('patriot_wear', 0.002429442778869017),
   ('implement', 0.002403597642923602),
   ('foot', 0.0023777525069781868),
   ('quality', 0.0023777525069781868),
   ('yo', 0.0023519073710327717),
   ('selfish', 0.0023519073710327717),
   ('fauci', 0.0023260622350873565),
   ('bubble', 0.0023002170991419414),
   ('pe', 0.0022743719631965263),
   ('properly', 0.0021968365553602814),
   ('household', 0.0021968365553602814),
   ('forward', 0.0021968365553602814),
   ('wash', 0.0021968365553602814),
   ('mandate', 0.002145146283469451),
   ('pro', 0.002093456011578621),
   ('animal', 0.002067610875633206),
   ('wearamask', 0.0020417657396877907),
   ('misinformation', 0.0020417657396877907),
   ('fun', 0.0020159206037423756),
   ('requirement', 0.0020159206037423756),
   ('suit', 0.0019900754677969605),
   ('brave', 0.0019900754677969605),
   ('small', 0.0019383851959061304),
   ('facemask', 0.0019125400599607153),
   ('mile', 0.0019125400599607153),
   ('temperature', 0.0019125400599607153),
   ('justice', 0.0019125400599607153),
   ('nose', 0.0018866949240153002),
   ('cough', 0.0018866949240153002),
   ('light', 0.0018608497880698853),
   ('urge', 0.0018350046521244702),
   ('stupidity', 0.0018350046521244702),
   ('afternoon', 0.001809159516179055),
   ('smoke', 0.00178331438023364),
   ('driver', 0.00178331438023364),
   ('directly', 0.0017574692442882249),
   ('prepare', 0.00173162410834281),
   ('regular', 0.0016799338364519797),
   ('folk', 0.0016540887005065646)]),
 (5,
  [('people', 0.1665040817374339),
   ('die', 0.0763978025363249),
   ('care', 0.03563177080659239),
   ('risk', 0.03511834471427838),
   ('great', 0.02526056374184936),
   ('covid', 0.02433639677568414),
   ('woman', 0.021820608923345485),
   ('symptom', 0.017302459310982184),
   ('disease', 0.01576218103404015),
   ('young', 0.014375930584792319),
   ('catch', 0.01129537403090825),
   ('slow', 0.01034553576012733),
   ('cure', 0.010242850541664527),
   ('heart', 0.010088822713970325),
   ('affect', 0.008856600092416697),
   ('watch', 0.008317502695486985),
   ('patient', 0.008291831390871284),
   ('sale', 0.008240488781639884),
   ('citizen', 0.007983775735482878),
   ('suffer', 0.007573034861631668),
   ('change', 0.007059608769317657),
   ('body', 0.006648867895466448),
   ('identify', 0.006597525286235047),
   ('condition', 0.006238127021615239),
   ('worldwide', 0.00585305745237973),
   ('severe', 0.005776043538532628),
   ('girl', 0.0056733583200698256),
   ('cancer', 0.005570673101607024),
   ('forever', 0.005236946141602916),
   ('remember', 0.005159932227755815),
   ('attack', 0.005082918313908713),
   ('victim', 0.00495456179083021),
   ('build', 0.00492889048621451),
   ('xe', 0.004672177440057504),
   ('brain', 0.004107408738512091),

In [ ]:
mallet_lda_model = gensim.models.wrappers.ldamallet.malletmodel2ldamodel(ldamallet)

In [ ]:
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(mallet_lda_model, corpus, id2word,sort_topics=False)

In [ ]:
print(vis.topic_order)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
pyLDAvis.save_html(vis, '2020_lda_mallet.html')

In [ ]:
vis

PreparedData(topic_coordinates=              x         y  topics  cluster      Freq
topic
0     -0.000264  0.000099       1        1  5.012854
1      0.000291 -0.000436       2        1  5.007553
2     -0.000028 -0.000379       3        1  4.994728
3      0.000461  0.000354       4        1  4.992379
4      0.000268 -0.000135       5        1  5.008141
5     -0.000023  0.000329       6        1  5.005779
6     -0.000088  0.000582       7        1  4.989459
7     -0.000171 -0.000448       8        1  4.968436
8     -0.000479  0.000234       9        1  4.994311
9     -0.000542 -0.000165      10        1  4.981681
10     0.000095  0.000053      11        1  5.024642
11    -0.000102 -0.000461      12        1  5.086722
12    -0.000945  0.000127      13        1  5.020679
13     0.000296 -0.000391      14        1  4.978748
14    -0.000083  0.000150      15        1  4.977159
15     0.000185  0.000245      16        1  5.022591
16     0.000593  0.000832      17        1  4.965526
17    -0.000048  0.000099      18        1  4.985264
18     0.000588 -0.000541      19        1  4.980900
19    -0.000004 -0.000150      20        1  5.002448, topic_info=                    Term       Freq      Total Category  logprob  loglift
10755            doubter  20.000000  20.000000  Default  30.0000  30.0000
18911             shroud  20.000000  20.000000  Default  29.0000  29.0000
37996                vmt  21.000000  21.000000  Default  28.0000  28.0000
14655      abigailmarone  20.000000  20.000000  Default  27.0000  27.0000
4467                 goi  20.000000  20.000000  Default  26.0000  26.0000
...                  ...        ...        ...      ...      ...      ...
11763       superstition   1.375044  20.991722  Topic20 -10.3946   0.2696
42382    contentcreation   1.375518  21.196554  Topic20 -10.3943   0.2602
10992           integral   1.368845  20.850532  Topic20 -10.3992   0.2718
20554  overseas_filipino   1.370942  21.420728  Topic20 -10.3976   0.2464
6891                copd   1.370305  21.374703  Topic20 -10.3981   0.2481

[834 rows x 6 columns], token_table=       Topic      Freq           Term
term
35983      1  0.049765         abantu
35983      2  0.049765         abantu
35983      3  0.049765         abantu
35983      4  0.049765         abantu
35983      5  0.049765         abantu
...      ...       ...            ...
20636     16  0.047263  zziwafredrick
20636     17  0.047263  zziwafredrick
20636     18  0.047263  zziwafredrick
20636     19  0.047263  zziwafredrick
20636     20  0.047263  zziwafredrick

[16380 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])